"""Full native integrity read inside read-only mounts, paired with host proof.

ga-x7lx r11 terminal observer: a rebind of the reviewed ga-y49e observe-platform-integrity-r2.py.
It verifies the terminal suspension lineage in the window root, admits the window's accepted
restoration (restored.json, bound by the window executor digest and restore-pass.json), and
bounds the cache clock from the window before.json. Generated by make_round2b.py.
"""
import json
import os
from pathlib import Path
import sys
import types

HERE=Path('/home/loucmane/gas-city-ops-worktrees/ga-e0t1-orchestrator-bootstrap/docs/ai/work-tracking/active/20260903-ga-e0t1-orchestrator-bootstrap-ACTIVE/designs/ga-x7lx-window')
ROOT=Path('/var/tmp/ga-x7lx-terminal-20260926-r1')
WINDOW=Path('/var/tmp/ga-x7lx-window-20260926-r1')
WINDOW_SHA='f41ca25a584492be7b695907bc9a47cae9ce637955135127e7057fc43294dbe6'
BUILD=Path('/var/tmp/ga-e0t1.18-platform-inspector-m9-20260926')
W_SHA='5c8899074b108d80f8952320058726cc5ab2ed8589fcc50a32a591faeda57dbf'
BINARY_SHA='9e29e45dd465dd0397525c5a2d8aa929e65a32bffa7a69787842a23c99a55549'
MANIFEST=Path('/home/loucmane/gascity/city/.gc/platform/install-manifest.json')
MANIFEST_SHA='5a29dc596af192e0f314391453d25d6be548695a0defd64bdfc2fa76554e4993'

def load_window():
    import hashlib
    path=HERE/'window-obs-r11.py';raw=path.read_bytes()
    if hashlib.sha256(raw).hexdigest()!=W_SHA:raise RuntimeError('observer source drift')
    w=types.ModuleType('frozen_window');w.__file__=str(path)
    exec(compile(raw,str(path),'exec'),w.__dict__)
    return w

def verify_preservation(r,before,after):
    w=r.w
    r.preservation(before,after,w.CITY_SHA[0],w.RECEIPT_SHA[0])
    accounting=r.p.compare(before['cache'],after['cache'],
        before['cache_access_clock'],after['cache_access_clock'])
    w.require(not accounting['deltas'],'read-only integrity changed cache atime')

def provider_pins(w,o):
    m=json.loads(w.read(MANIFEST,MANIFEST_SHA))
    providers=m['integrity']['providers']
    # M9 (manifest file 5a29dc59) pins the candidate wrapper as a second claude provider, keyed by path.
    w.require([p['name'] for p in providers]==['claude-native','codex','claude','claude'],'provider inventory')
    w.require([p['path'] for p in providers[2:]]==['/home/loucmane/gas-city-template/bin/gct-claude-signing-worker',
        '/home/loucmane/gas-city-template/bin/gct-claude-candidate-worker']
        and providers[3]['sha256']=='e4442971fd3188208eaf22974aaaf55f949b8f51041775f041ecb00a66de92a3',
        'M9 provider pins')
    for p in providers:
        w.require(p['version_args']==['--version'],'only version probes')
        w.require(str(Path(p['path']).resolve(strict=True))==p['resolved_path'],'provider resolution')
        pin,_=o.read_file(p['resolved_path'])
        w.require(pin['sha256']==p['sha256'],'provider bytes drift before invocation')
        w.require(pin['metadata']['uid']==1000 and pin['metadata']['gid']==1000
            and pin['metadata']['mode']==0o755,'provider authority')

def main():
    r=load_window();w=r.w;w.require(globals().get('_SOURCE_SHA'),'bound entry')
    w.read(Path(__file__),_SOURCE_SHA)
    b,o,owned=w.load_support();w.pins()
    w.read(BUILD/'platform-inspect',BINARY_SHA)
    result=json.loads(w.read(BUILD/'build-result.json','87e12b94b8f60d729826e7d8dd7ce96932e337a9f668ea686517339af0939e3a'))
    w.require(result['binary_sha256']==BINARY_SHA and result['core_commit']=='deefb98b2aed07875df31351d081fbac195cb1cd'
        and result['core_tree']=='af5c3f045c1f50cd62c859f6dc58fa613e5f2f99'
        and result['entrypoint_sha256']=='1fa212cead41bbdb998ec24146d119b69edb9c5a446f8a9ac1ea9ad50af7b3a5',
        'build binding')
    provider_pins(w,o)
    if sys.argv[1:]==['inner']:
        w.ROOT=ROOT;w.mount_proof(None)
        os.execve(BUILD/'platform-inspect',[str(BUILD/'platform-inspect')],dict(b.ENV,BD_DISABLE_METRICS='1'))
    w.require(sys.argv[1:]==[],'unknown action')
    w.host(o);w.read(w.CITY/'city.toml',w.CITY_SHA[0]);w.read(w.RECEIPT,w.RECEIPT_SHA[0])
    # The terminal suspension lineage and the accepted restoration are in the window root.
    w.ROOT=WINDOW
    w.verified_lifecycle(terminal=True)
    w.require(w.record('restore-consumed.json')==dict(executor_sha256=WINDOW_SHA)
        and w.record('restore-pass.json')==dict(ok=True,full_platform_integrity_still_required=True),
        'accepted window restoration')
    accepted=w.record('restored.json');original=w.record('before.json')
    # The window layer adds route-regeneration keys; no reload happens after restore, and this layer
    # compares every other field.
    for key in ('generated_routes','generated_route_chain'):accepted.pop(key)
    ROOT.mkdir(mode=0o700);w.ROOT=ROOT
    w.save('intent.json',dict(executor_sha256=_SOURCE_SHA,binary_sha256=BINARY_SHA,
        version_probes_only=True,worker_launch=False))
    w.snapshot('observed-before.json',b,o)
    before=w.record('observed-before.json')
    verify_preservation(r,accepted,before)
    r.p.bounds(original['cache_access_clock'],before['cache_access_clock'])
    argv=['/usr/bin/bwrap','--ro-bind','/','/','--unshare-net','--unshare-pid',
        '--new-session','--die-with-parent','--proc','/proc','--dev','/dev','--',
        '/usr/bin/python3','-I','-S','-B',str(w.LAUNCH),__file__,_SOURCE_SHA,'inner']
    try:
        phase=w.phase('integrity',argv,b,owned,timeout=90)
        report=json.loads(phase['stdout'])
        w.require(report['schema']=='ga.platform-inspect-observation.v1' and report['ok'] is True
            and report['report']['Drifts'] in (None,[]),'integrity drift')
    except BaseException as exc:
        w.save('primary-failure.json',dict(error=str(exc),preservation_proven=False))
        raise
    finally:
        # Preserve the first failure above. Missing/uncertain terminal containment
        # stops here without treating a snapshot as successful containment.
        w.complete_containment()
        w.snapshot('observed-after.json',b,o)
        after=w.record('observed-after.json')
        verify_preservation(r,before,after)
        r.p.bounds(original['cache_access_clock'],after['cache_access_clock'])
        w.save('preservation.json',dict(window_preservation=True,cache_atime_deltas=0,
            runtime_child_metadata_policy='unchanged pinned R6',timestamp_writes=False))
    w.save('result.json',dict(ok=True,report=report,actual_host_verified=True,
        root_cache_protected_read_only=True,window_preservation=True,worker_launched=False,
        terminal_suspension_endpoint_bound=True,accepted_restoration_bound=True))
    print(json.dumps(dict(ok=True,worker_launched=False,full_native_integrity=True)))

if __name__=='__main__':main()
