"""Read-only sole eligible native task audit after route, before resume.

ga-gegx r11: a rebind of the reviewed ga-y49e audit-routed-queue-r2.py. Mode `route` runs right after
the route (every rig suspended). Mode `resume` runs after rig-resume and before city-resume (only
the gascity rig resumed). Generated by make_round2b.py.
"""
import hashlib
import json
import os
from pathlib import Path
import sys
import types

MODE = sys.argv[1] if len(sys.argv) == 2 else None
assert MODE in ('route', 'resume'), 'audit mode'
ROOT = Path('/var/tmp/ga-gegx-audit-%s-20260923-r1' % MODE)
RUNNER = Path('/var/tmp/ga-ecwh-preflight-diagnostic-20260920-r1/phase_runner.py')
raw = RUNNER.read_bytes()
assert hashlib.sha256(raw).hexdigest() == 'eddf5e1174a7b275abe280e91ea5c8ea0762600d38524ba9631f53fb4874cdf3'
owned = types.ModuleType('owned')
exec(compile(raw, str(RUNNER), 'exec', dont_inherit=True), owned.__dict__)
SUPPORT=Path('/home/loucmane/gas-city-ops-worktrees/ga-e0t1-orchestrator-bootstrap/docs/ai/work-tracking/active/20260903-ga-e0t1-orchestrator-bootstrap-ACTIVE/designs/gct-m1wh-p6/p6-observe-compose.py')
raw=SUPPORT.read_bytes()
assert hashlib.sha256(raw).hexdigest()=='43b94ce677dcaa80b6937f7205362063da151f0608a99874b18b692ab8f2c8d6'
support=types.ModuleType('queue_environment');support.__file__=str(SUPPORT)
exec(compile(raw,str(SUPPORT),'exec',dont_inherit=True),support.__dict__)
ENV=dict(support.ENV,BD_DISABLE_METRICS='1')
GC = ['/home/loucmane/gascity/bin/gc', '--city', '/home/loucmane/gascity/city']
TARGET = 'gascity/gc.implementation-worker'
ALIASES = {TARGET, 'gc.implementation-worker', 'gc__implementation-worker'}
ROOT.mkdir(mode=0o700)
def run(name, args):
    r = owned._run_owned_phase(name=name, argv=GC+args, environment=ENV,
                              cwd=ROOT, timeout=45, evidence_path=ROOT/(name+'.json'))
    c = r['cleanup']
    assert r['exit_code'] == 0 and not r['timed_out'] and not r['primary_error'], name
    assert c['direct_child_reaped'] and c['owned_process_group_gone'], name
    assert not c['failures'] and not c['unexpected_survivors'], name
    return json.loads(r['stdout'])
observations = {}
for store, scope in [('core', ['--rig', 'gascity']), ('city', [])]:
    cases = {
        'routed': ['bd', 'ready', '--metadata-field', 'gc.routed_to='+TARGET, '--unassigned', '--exclude-type=epic', '--json', '--limit', '0'],
        'legacy': ['bd', 'ready', '--metadata-field', 'gc.run_target='+TARGET, '--metadata-field', 'gc.kind=workflow', '--unassigned', '--exclude-type=epic', '--json', '--sort', 'oldest', '--limit', '0'],
        'ephemeral-open': ['bd', 'query', '--json', 'ephemeral=true AND status=open', '--limit=0'],
        'ephemeral-progress': ['bd', 'query', '--json', 'ephemeral=true AND status=in_progress', '--limit=0'],
        'in-progress': ['bd', 'list', '--status', 'in_progress', '--json', '--limit=0'],
        'open': ['bd', 'list', '--status', 'open', '--json', '--limit=0'],
    }
    values = {name: run(store+'-'+name, scope+args) for name, args in cases.items()}
    assert all(isinstance(rows, list) for rows in values.values())
    assert [v['id'] for v in values['routed']] == (['ga-gegx'] if store=='core' else []), store+' routed'
    assert not [v for v in values['legacy'] if not v.get('metadata', {}).get('gc.routed_to')], store+' legacy'
    for name in ('ephemeral-open', 'ephemeral-progress', 'in-progress', 'open'):
        for v in values[name]:
            m = v.get('metadata') or {}
            a = v.get('assignee') or ''
            routed = m.get('gc.routed_to') == TARGET
            legacy = not m.get('gc.routed_to') and m.get('gc.run_target') == TARGET and m.get('gc.kind') == 'workflow'
            assigned = a in ALIASES or a.startswith(('ci-', TARGET+'-', 'gc.implementation-worker-', 'gc__implementation-worker-'))
            if name=='open' and store=='core' and v['id']=='ga-gegx':
                assert routed and not a and v['status']=='open', 'expected open task drift'
                continue
            # Conservatively stop on any matching row; do not silently assume
            # dependency blocking or apply broad List(open) normalization.
            assert not (routed or legacy or assigned), (store, name, v['id'])
    for i, alias in enumerate(sorted(ALIASES)):
        rows = run(store+'-assigned-ready-'+str(i), scope+['bd', 'ready', '--assignee='+alias, '--json', '--limit=0'])
        assert rows == [], (store, alias)
    observations[store] = {name: len(rows) for name, rows in values.items()}
sessions = run('all-historical-sessions', ['bd', 'list', '--type', 'session', '--include-infra', '--all', '--json', '--limit', '0'])
assert isinstance(sessions, list)
for v in sessions:
    m = v.get('metadata') or {}
    if m.get('template') == TARGET or m.get('gc.trigger_bead_id') == 'ga-gegx' or m.get('gc.work_dir') == '/home/loucmane/gascity-core-worktrees/ga-gegx-typed-route-cycles':
        assert v['status'] == 'closed', v['id']
live = run('live-sessions', ['session', 'list', '--json'])
state = run('city-status', ['status', '--json'])
assert live['ok'] and live['sessions'] == []
assert state['suspended'] and state['summary']['running_agents'] == 0
# route mode: every rig suspended. resume mode: only the gascity rig resumed.
assert len(state['rigs']) == 4 and all(r['suspended'] == (MODE == 'route' or r['name'] != 'gascity')
                                       for r in state['rigs'])
result = dict(ok=True, mode=MODE, observations=observations, historical_sessions=len(sessions),
              sole_eligible_target_task='ga-gegx', lifecycle_changed=False,
              mutation=False, worker_launched=False,
              limitation='Actual new session identities must be checked again after creation/claim.')
with (ROOT/'result.json').open('x') as f:
    json.dump(result, f, sort_keys=True, indent=2)
    f.write('\n')
print(json.dumps(result))
