"""Generate s2_transition.py (broker sequence 15) from the executed sequence 14 transition.

  python3 -I -B make_s2.py [output]

Source: designs/ga-e0t1.15-deploy/s2_transition.py (sha 9ce041ec), the file that ran the sequence 14 adoption of
b2760ea4 (attempt t1, then its read-only recovery acceptance). Every change is one of the exact, count-checked
substitutions below. Reviewers diff s2_transition.py against the source; test_s2.py proves that the committed
file equals this generator's output.

What sequence 15 changes, and why:
- Identity: Core b2760ea4 -> fce2e9a0 (S1 of ga-e0t1.18, build source deefb98b / tree af5c3f04 = merge f3856bd1,
  artifact blob e6e9ac57), broker sequence 15, fresh ROOT, attempt and accept root.
- Metadata preimages: the M6 pair (install manifest 7f335ad8, install receipt 123a0181) replaces M5.
- Cache: the new Core embeds the same pack content (S1b provenance), so no synthetic directory may appear except
  the optional 9c8c14fc under the same exact-content rule; 69fe9a2e already exists and must stay exact.
- City: the shim stays a7bcaa7c and every live-key link and manifest stays exactly on 69fe9a2e (the inventory is
  re-derived for this package by live_key_inventory.py; S2 of ga-e0t1.15 repointed them).
- Dolt: the watchdog survived sequence 14 and still maps the deleted pre-sequence-14 image 69d00186. The
  predecessor may therefore have a deleted watchdog image, which must hash to 69d00186 or to OLD; the transition
  admits exactly fresh or exactly survived, as before.
- Broker: it stayed active after sequence 14 (socket activation), so the predecessor broker is active and running
  and the transition admits the unchanged broker record or, exactly as before, a fresh activation epoch.
- Postflight: sequence 14's postflight1 refused on a transient supervisor-scope member during initialization.
  Before each postflight capture the scope must now pass on two consecutive reads 5 s apart (bounded 180 s); the
  capture then checks it again exactly.
- The sequence 14 recovery phase is removed; a sequence 15 recovery would be its own reviewed change.
"""
import hashlib
import json
from pathlib import Path

HERE = Path(__file__).parent
SOURCE = HERE.parent/'ga-e0t1.15-deploy'/'s2_transition.py'
SOURCE_SHA = '9ce041ec48aa9efae057a0af4783882647bf9c60157e8e37a62044ed4c926583'
OUT = HERE/'s2_transition.py'
if __name__ == '__main__':
    import sys as _sys
    if len(_sys.argv) == 2:
        OUT = Path(_sys.argv[1])

OLD = 'b2760ea407d8a5853fb7fbb3c184870ad4b6e9ccd763241a8ec59a8c3201d489'
OLD_SIZE = 134052980
NEW = 'fce2e9a0bea6c79f257e55b6424cf9271405d58f916a1017f3c14e232ad5d13b'
NEW_SIZE = 134062284
PRIOR_IMAGE = '69d00186c098b84efe6658c03d888ce07f6d6528d6c446671b53d92f7bde89f9'
KEY = '69fe9a2e6239743677a6e13188096df34d6eb6d41fad171af58671ef288fdd3f'
SHIM = 'a7bcaa7cce9261b987bb766fba19db46cc7f4ae8d8b22b6d8059bb884d8788d2'
MANIFEST = 'f51ef6490bbc3ae9c595b2fe0aaf5a4d825c0db4e5edbc56c59d315e6dc3cf10'


def sha(raw):
    return hashlib.sha256(raw).hexdigest()


def retry():
    """Optional retry.json {"retry": N, "reaccept": bool}, as in ga-e0t1.15 make_s2: N > 0 gives a fresh ROOT
    (-tN) and attempt; reaccept also gives a fresh accept root."""
    path = HERE/'retry.json'
    value = json.loads(path.read_text()) if path.exists() else {'retry': 0, 'reaccept': False}
    assert set(value) == {'retry', 'reaccept'} and type(value['retry']) is int and value['retry'] >= 0
    assert type(value['reaccept']) is bool and (value['retry'] > 0 or not value['reaccept'])
    return value


def inventory_shas():
    return (sha((HERE/'live-key-links.tsv').read_bytes()), sha((HERE/'live-key-manifests.tsv').read_bytes()))


def header(accepted, r):
    n = r['retry']
    root = '/var/tmp/ga-e0t1.18-seq15-20260926' + ('-t%d' % n if n else '')
    return [
        ('"""ga-e0t1.15 sequence 14 adoption of Core b2760ea4 (generated by make_s2.py from the seq13 successor)."""',
         '"""ga-e0t1.18 sequence 15 adoption of Core fce2e9a0 (generated by make_s2.py from the executed sequence 14 file)."""'),
        ("ROOT=Path('/var/tmp/ga-e0t1.15-seq14-20260925-t1')", 'ROOT=Path(%r)' % root),
        ("ATTEMPT='ga-mutg-adoption-20260925-r15'", "ATTEMPT='ga-mutg-adoption-20260926-r%d'" % (16 + n)),
        ("ACCEPTED=Path('/var/tmp/ga-e0t1.15-predecessor-20260925-r3/second.json')", 'ACCEPTED=Path(%r)' % accepted['path']),
        ("ACCEPTED_SHA='16af7c5eacd8a366c516d071b563af512474488b634eec47d124aaa814eb7809'",
         'ACCEPTED_SHA=%r' % accepted['sha256']),
        ("ARTIFACT=Path('/var/tmp/ga-e0t1.15-build-20260925/gc-a')", "ARTIFACT=Path('/var/tmp/ga-e0t1.18-build-20260926/gc-a')"),
        ("c.OLD='69d00186c098b84efe6658c03d888ce07f6d6528d6c446671b53d92f7bde89f9'", 'c.OLD=%r' % OLD),
        ("c.NEW='b2760ea407d8a5853fb7fbb3c184870ad4b6e9ccd763241a8ec59a8c3201d489'", 'c.NEW=%r' % NEW),
        ('c.NEW_SIZE=134052980', 'c.NEW_SIZE=%d' % NEW_SIZE),
        ("            commit='9faeabc2892d8c7133111e13ad55af66790a2ac6',",
         "            commit='deefb98b2aed07875df31351d081fbac195cb1cd',"),
        ("            tree='c9f19d215d271a5dda0bce296dc72c32dfc35499',",
         "            tree='af5c3f045c1f50cd62c859f6dc58fa613e5f2f99',"),
        ("            blob='db752a382a3c28336d4ddaa370d9d9e58d1c604a')",
         "            blob='e6e9ac576162bcdbde8fc05ecbb1943f55f0ce41')"),
        ("m['sequence']==14", "m['sequence']==15"),
        ("receipt['sequence']==14", "receipt['sequence']==15"),
        ("receipt['before']==dict(sha256=c.OLD,size=134048098,", "receipt['before']==dict(sha256=c.OLD,size=%d," % OLD_SIZE),
        ("os.memfd_create('ga-e0t1.15-reviewed-envelope'", "os.memfd_create('ga-e0t1.18-reviewed-envelope'"),
    ]


def overrides(r):
    links_sha, manifests_sha = inventory_shas()
    n = r['retry']
    accept_root = '/var/tmp/ga-e0t1.18-predecessor-20260926-r%d' % (1 + (n if r['reaccept'] else 0))
    return [
        ('# ===================== ga-e0t1.15 sequence 14 overrides (make_s2.py) =====================\n',
         '# ===================== ga-e0t1.15 sequence 14 overrides (make_s2.py) =====================\n'
         '# ga-e0t1.18 sequence 15: these blocks are rebound by ga-e0t1.18-deploy/make_s2.py; see its docstring.\n'),
        ("S14_HERE=Path('/home/loucmane/gas-city-ops-worktrees/ga-e0t1-orchestrator-bootstrap/docs/ai/work-tracking/active/20260903-ga-e0t1-orchestrator-bootstrap-ACTIVE/designs/ga-e0t1.15-deploy')",
         "S14_HERE=Path('/home/loucmane/gas-city-ops-worktrees/ga-e0t1-orchestrator-bootstrap/docs/ai/work-tracking/active/20260903-ga-e0t1-orchestrator-bootstrap-ACTIVE/designs/ga-e0t1.18-deploy')"),
        ("S14_LIVE_KEY='a21cc0a2fbf22c14fbe59cf508d05bcc230774f5c0d9cd386215369d43a2410a'",
         "# sequence 15: the live key is already 69fe9a2e (S2 of ga-e0t1.15 repointed every link) and does not change.\n"
         "S14_LIVE_KEY=%r" % KEY),
        ("S14_SHIM_BEFORE='2e0a1f7462a913c2c5fab1078d2837a272b225b09f3b500f2df971427c2eaa6e'", 'S14_SHIM_BEFORE=%r' % SHIM),
        ("S14_MANIFEST_BEFORE='7739092947074ba1cdcb389657baf41623efb12ab50944a97bc9b2d53de92b34'",
         'S14_MANIFEST_BEFORE=%r' % MANIFEST),
        ("S14_M5_MANIFEST=dict(sha256='2d7eadce62c4e567697813cc9122414f1e94c3bd9d389aef92015adef7f36319',mode=0o644,uid=1000,gid=1000,size=127269)",
         "# sequence 15: the M6 pair (ga-e0t1.15 S3 part 1) replaces M5; the names keep the sequence 14 spelling.\n"
         "S14_M5_MANIFEST=dict(sha256='7f335ad83091a1a907b628fa5813c7daf6a530340a2ed404476797b5db90fefb',mode=0o644,uid=1000,gid=1000,size=127719)"),
        ("S14_M5_RECEIPT=dict(sha256='9342b33eb7b0fd4e68a34c8cee3b8a89b9011a091d7121d249b88c84378fed94',mode=0o644,uid=1000,gid=1000,size=2546)",
         "S14_M5_RECEIPT=dict(sha256='123a01818b86f977ceabab1207c57795a3780261e39599019aa37f7609febaac',mode=0o644,uid=1000,gid=1000,size=2552)"),
        ("        o.require(s14_sha(Path('/proc/'+str(w)+'/exe').read_bytes())==c.OLD,'surviving watchdog image is not OLD')\n",
         "        # sequence 15: the watchdog that survived sequence 14 still maps 69d00186; after this adoption a\n"
         "        # surviving watchdog maps that image or OLD. Nothing else is admitted.\n"
         "        o.require(s14_sha(Path('/proc/'+str(w)+'/exe').read_bytes()) in (%r,c.OLD),'surviving watchdog image is not a known prior image')\n"
         % PRIOR_IMAGE),
        ("    c.o.require(S14_NEW_KEY in tops and tops<={S14_NEW_KEY,S14_OPTIONAL_KEY},'unexpected cache additions')\n",
         "    # sequence 15: the embedded pack content is unchanged, so no required directory appears.\n"
         "    c.o.require(tops<={S14_OPTIONAL_KEY},'unexpected cache additions')\n"),
        ("        o.require(bool(admitted) and S14_NEW_KEY in admitted,'candidate cache not admitted')\n",
         "        o.require(admitted is not None and set(admitted)<={S14_OPTIONAL_KEY},'candidate cache not admitted')\n"),
        ("    c.o.require(old_dolt['watchdog_image']=='live','predecessor watchdog not live')\n",
         "    # sequence 15: the predecessor watchdog may be live or the survivor mapping a known prior image.\n"
         "    c.o.require(old_dolt['watchdog_image'] in ('live','deleted-old'),'predecessor watchdog image')\n"),
        ("    c.o.require(nb['ActiveState']=='active' and nb['SubState']=='running' and int(nb['MainPID'])>1\n"
         "                and nb['MainPID']!=ob['MainPID']\n"
         "                and int(nb['ExecMainStartTimestampMonotonic'])>int(ob['ExecMainStartTimestampMonotonic']),\n"
         "                'broker activation epoch')\n",
         "    # sequence 15: the broker stayed active after sequence 14; the submission may reach the running process\n"
         "    # (record unchanged) or, exactly as before, a fresh activation epoch.\n"
         "    c.o.require(nb==ob or (nb['ActiveState']=='active' and nb['SubState']=='running' and int(nb['MainPID'])>1\n"
         "                and nb['MainPID']!=ob['MainPID']\n"
         "                and int(nb['ExecMainStartTimestampMonotonic'])>int(ob['ExecMainStartTimestampMonotonic'])),\n"
         "                'broker epoch')\n"),
        ("S14_LINKS_TSV_SHA='2dfb117b850b0472e8da333bc9a6b73181ee2162d3085f92bfe5357e10e87bff'", 'S14_LINKS_TSV_SHA=%r' % links_sha),
        ("S14_MANIFESTS_TSV_SHA='940d382e1f9aee2b64ce405f692e1ec8ffea53653d2183b5183f5feb9129dfe2'",
         'S14_MANIFESTS_TSV_SHA=%r' % manifests_sha),
        ("    c.o.require(False,'runtime not initialized within bound: '+str(last))\n",
         "    c.o.require(False,'runtime not initialized within bound: '+str(last))\n"
         "\n"
         "# sequence 15: sequence 14's postflight1 refused on a transient supervisor-scope member during\n"
         "# initialization. Wait, bounded and read-only, until the quiet scope passes on two consecutive reads 5 s\n"
         "# apart. The postflight capture then checks the scope again exactly.\n"
         "S15_SCOPE_WAIT_NS=180*d.SECOND\n"
         "def s15_wait_scope_settled():\n"
         "    o=c.o;o.GC_SHA=c.NEW\n"
         "    start=time.monotonic_ns();last=None;passes=0\n"
         "    while time.monotonic_ns()-start<S15_SCOPE_WAIT_NS:\n"
         "        try:\n"
         "            c.s.quiet_scope(o.host_observation());passes+=1\n"
         "            if passes>=2:return\n"
         "        except Exception as exc:\n"
         "            last=str(exc);passes=0\n"
         "        time.sleep(5)\n"
         "    o.require(False,'supervisor scope not settled within bound: '+str(last))\n"),
        ("    if after:\n        s14_wait_initialized()\n",
         "    if after:\n        s14_wait_initialized()\n        s15_wait_scope_settled()\n"),
        ("    o.require(host['broker']==dict(MainPID='0',NRestarts='0',ExecMainStartTimestampMonotonic='0',\n"
         "              ActiveState='inactive',SubState='dead',UnitFileState='disabled',Result='success'),\n"
         "              'accepted broker is not exactly inactive')\n"
         "    o.require(host['broker_socket']==dict(ActiveState='active',SubState='listening',\n"
         "              UnitFileState='enabled',Result='success'),'accepted broker socket is not listening')\n"
         "    o.require(scope['dolt_members']['watchdog_image']=='live','accepted watchdog image is not live')\n",
         "    # sequence 15: the broker stayed active after sequence 14 (the accepted record pins its epoch), and the\n"
         "    # watchdog may be the survivor mapping 69d00186.\n"
         "    broker=host['broker']\n"
         "    o.require(broker['ActiveState']=='active' and broker['SubState']=='running' and broker['NRestarts']=='0'\n"
         "              and broker['UnitFileState']=='disabled' and broker['Result']=='success' and int(broker['MainPID'])>1,\n"
         "              'accepted broker is not exactly active and running')\n"
         "    o.require(host['broker_socket']['ActiveState']=='active' and host['broker_socket']['UnitFileState']=='enabled',\n"
         "              'accepted broker socket')\n"
         "    o.require(scope['dolt_members']['watchdog_image'] in ('live','deleted-old'),'accepted watchdog image')\n"),
        ("S14_ACCEPT_ROOT=Path('/var/tmp/ga-e0t1.15-predecessor-20260925-r3')", 'S14_ACCEPT_ROOT=Path(%r)' % accept_root),
    ]


RECOVERY_START = '# --- 9. Recovery acceptance (sequence 13 precedent).'
RECOVERY_END = "    s14_recover(sys.argv[2],sys.argv[3]);sys.exit(0)\n"


def main():
    raw = SOURCE.read_bytes()
    assert sha(raw) == SOURCE_SHA, 'sequence 14 source drift'
    path = HERE/'accepted.json'
    accepted = (json.loads(path.read_text()) if path.exists()
                else {'path': '/nonexistent/accepted-pending.json', 'sha256': '0' * 64})
    assert set(accepted) == {'path', 'sha256'}, accepted
    text = raw.decode()
    r = retry()
    for old, new in header(accepted, r) + overrides(r):
        assert text.count(old) == 1, old[:90]
        text = text.replace(old, new)
    assert text.count(RECOVERY_START) == 1 and text.count(RECOVERY_END) == 1
    start = text.index(RECOVERY_START)
    end = text.index(RECOVERY_END) + len(RECOVERY_END)
    text = (text[:start] + '# --- 9. (sequence 15) The sequence 14 recovery acceptance phase is removed; a sequence 15\n'
            '# recovery would be its own reviewed change.\n' + text[end:])
    OUT.write_text(text)
    print(sha(text.encode()))


if __name__ == '__main__':
    main()
