"""Full native integrity read inside read-only mounts, paired with host proof.

ga-e0t1.20 r11: a rebind of the reviewed ga-y49e observe-platform-integrity-r2.py for a FRESH window on the
post-P11 baseline (M10). It admits the live state against the ga-e0t1.20 s3 TERMINAL record (ga-e0t1.20 window),
through the base `before.json` snapshot check. No prior window lifecycle or restoration observation
exists, so those two historical comparisons are removed. Generated by make_round2a.py.
"""
import json
import os
from pathlib import Path
import sys
import types

HERE=Path('/home/loucmane/gas-city-ops-worktrees/ga-e0t1-orchestrator-bootstrap/docs/ai/work-tracking/active/20260903-ga-e0t1-orchestrator-bootstrap-ACTIVE/designs/ga-e0t1-20-astra-window')
ROOT=Path('/var/tmp/ga-e0t1.20-integrity-20260928-r4')
BUILD=Path('/var/tmp/gct-oak5-platform-inspector-m12-20260927')
W_SHA='271d995918ae711a5031de0b41d27f86bd697c52e2b026d1b2984e8fe4c34cc7'
BINARY_SHA='0da1ff146cb3e1e1ba7329d669f2135bbc7d26c6c0f35999e6dad1bef88d08c6'
MANIFEST=Path('/home/loucmane/gascity/city/.gc/platform/install-manifest.json')
MANIFEST_SHA='114b4a000471ee145d494732db361521ea237b3e4857607b06720b7b105327b9'

def load_window():
    import hashlib
    path=HERE/'window-obs-r11.py';raw=path.read_bytes()
    if hashlib.sha256(raw).hexdigest()!=W_SHA:raise RuntimeError('observer source drift')
    w=types.ModuleType('frozen_window');w.__file__=str(path)
    exec(compile(raw,str(path),'exec'),w.__dict__)
    return w

def verify_preservation(r,before,after):
    w=r.w
    r.preservation(before,after,w.CITY_SHA[0],w.RECEIPT_SHA[0])
    accounting=r.p.compare(before['cache'],after['cache'],
        before['cache_access_clock'],after['cache_access_clock'])
    w.require(not accounting['deltas'],'read-only integrity changed cache atime')

def provider_pins(w,o):
    m=json.loads(w.read(MANIFEST,MANIFEST_SHA))
    providers=m['integrity']['providers']
    # Exact M12 adds the Template candidate wrapper. Manifest digest remains mandatory.
    w.require([p['name'] for p in providers]==['claude-native','codex','claude','claude','claude'],'provider inventory')
    w.require([p['path'] for p in providers[2:]]==['/home/loucmane/gas-city-template/bin/gct-claude-signing-worker',
        '/home/loucmane/gas-city-template/bin/gct-claude-candidate-worker',
        '/home/loucmane/gas-city-template/bin/gct-claude-template-candidate-worker']
        and providers[3]['sha256']=='e4442971fd3188208eaf22974aaaf55f949b8f51041775f041ecb00a66de92a3'
        and providers[4]['sha256']=='229d33557326abc8bafceadb06ae12ba2a2d9189e137ff0e1378d35dcf69491c',
        'M12 provider pins')
    for p in providers:
        w.require(p['version_args']==['--version'],'only version probes')
        w.require(str(Path(p['path']).resolve(strict=True))==p['resolved_path'],'provider resolution')
        pin,_=o.read_file(p['resolved_path'])
        w.require(pin['sha256']==p['sha256'],'provider bytes drift before invocation')
        w.require(pin['metadata']['uid']==1000 and pin['metadata']['gid']==1000
            and pin['metadata']['mode']==0o755,'provider authority')

def main():
    r=load_window();w=r.w;w.require(globals().get('_SOURCE_SHA'),'bound entry')
    w.read(Path(__file__),_SOURCE_SHA)
    # No recovery admission; the accepted image is the ga-e0t1.20 s3 TERMINAL record (window-base).
    b,o,owned=w.load_support();w.pins()
    w.read(BUILD/'platform-inspect',BINARY_SHA)
    result=json.loads(w.read(BUILD/'build-result.json','2ec7df2d33d0fddc9b9204c51cf65879a683f628dfd2cf2109c04c030416aed0'))
    w.require(result['binary_sha256']==BINARY_SHA and result['core_commit']=='f45a626213dc5b8d0b52f097d978cca56e506df0'
        and result['core_tree']=='f1011adaf673937fbda1d254a53c8f0eadf17c5c'
        and result['entrypoint_sha256']=='367056c801f85a4409589d231a0e91243f7ed1d9c6ded9a2e658865c8e3b0ad4',
        'build binding')
    provider_pins(w,o)
    if sys.argv[1:]==['inner']:
        w.ROOT=ROOT;w.mount_proof(None)
        os.execve(BUILD/'platform-inspect',[str(BUILD/'platform-inspect')],dict(b.ENV,BD_DISABLE_METRICS='1'))
    w.require(sys.argv[1:]==[],'unknown action')
    w.host(o);w.read(w.CITY/'city.toml',w.CITY_SHA[0]);w.read(w.RECEIPT,w.RECEIPT_SHA[0])
    # Fresh window: no prior lifecycle chain exists to verify. The suspension state is pinned in the
    # snapshot below and compared exactly with the ga-e0t1.20 s3 TERMINAL record.
    ROOT.mkdir(mode=0o700);w.ROOT=ROOT
    w.save('intent.json',dict(executor_sha256=_SOURCE_SHA,binary_sha256=BINARY_SHA,
        version_probes_only=True,worker_launch=False))
    # The base snapshot named before.json admits the live state against the ga-e0t1.20 s3 TERMINAL record
    # (four keys) and the P11 provider pins, through approved_candidate_cache_image only.
    w.snapshot('before.json',b,o)
    before=w.record('before.json')
    argv=['/usr/bin/bwrap','--ro-bind','/','/','--unshare-net','--unshare-pid',
        '--new-session','--die-with-parent','--proc','/proc','--dev','/dev','--',
        '/usr/bin/python3','-I','-S','-B',str(w.LAUNCH),__file__,_SOURCE_SHA,'inner']
    try:
        phase=w.phase('integrity',argv,b,owned,timeout=90)
        report=json.loads(phase['stdout'])
        w.require(report['schema']=='ga.platform-inspect-observation.v1' and report['ok'] is True
            and report['report']['Drifts'] in (None,[]),'integrity drift')
    except BaseException as exc:
        w.save('primary-failure.json',dict(error=str(exc),preservation_proven=False))
        raise
    finally:
        # Preserve the first failure above. Missing/uncertain terminal containment
        # stops here without treating a snapshot as successful containment.
        w.complete_containment()
        w.snapshot('observed-after.json',b,o)
        after=w.record('observed-after.json')
        verify_preservation(r,before,after)
        w.save('preservation.json',dict(window_preservation=True,cache_atime_deltas=0,
            runtime_child_metadata_policy='unchanged pinned R6',timestamp_writes=False))
    w.save('result.json',dict(ok=True,report=report,actual_host_verified=True,
        root_cache_protected_read_only=True,window_preservation=True,worker_launched=False,
        admitted_against_accepted_image=True))
    print(json.dumps(dict(ok=True,worker_launched=False,full_native_integrity=True)))

if __name__=='__main__':main()
