"""One raw route of the already-bound task; all rigs remain suspended.

ga-e0t1.20 r11: a rebind of the reviewed ga-y49e route-task-r4.py over window-r11.py. The binding ran as
its own reviewed job, so its outputs are bound by provenance: the executor digest and brief digest
in binding-intent.json and the exact result. Generated by make_round2b.py.
"""
import hashlib
import json
import os
from pathlib import Path
import stat
import time
import sys
import types

HERE=Path('/home/loucmane/gas-city-ops-worktrees/ga-e0t1-orchestrator-bootstrap/docs/ai/work-tracking/active/20260903-ga-e0t1-orchestrator-bootstrap-ACTIVE/designs/ga-e0t1-20-astra-window')
ROOT=Path('/var/tmp/ga-e0t1.20-route-20260927-r1')
BIND=Path('/var/tmp/ga-e0t1.20-bind-20260927-r1')
BIND_SHA='9fd6c49adecf7fb991f9b8cd2c6279c25fcf73455bfa0911609a2079928495e7'
DESCRIPTION_SHA='136f2b728a6713c123dab4a79a6fb34934e578bf01cf57658603afdb46166955'
PREROUTE=Path('/home/loucmane/gas-city-ops-worktrees/ga-e0t1-orchestrator-bootstrap/docs/ai/work-tracking/active/20260903-ga-e0t1-orchestrator-bootstrap-ACTIVE/designs/ga-6utp-activation-r10/preroute.py')
PREROUTE_SHA='d52e09214381fb6ce92becc2aed72fd1318821fd327ad3fb07e4974b57a3f4c6'
CANDIDATE_GIT=Path('/home/loucmane/gas-city-ops-worktrees/ga-e0t1-orchestrator-bootstrap/docs/ai/work-tracking/active/20260903-ga-e0t1-orchestrator-bootstrap-ACTIVE/designs/ga-6utp-activation-r10/candidate_git.py')
CANDIDATE_GIT_SHA='d2894e829618ad1fdcb5640b47b99baa3c783173acccb4f7f5918c958823bebe'
# s1 r8: the reviewed preroute.py record refresh after the sequence 16 controller restart (pid 2800348).
RECORD=Path('/home/loucmane/.local/share/gas-city-staging/ga-bebv-process-record-20260927/process-record.json')
RECORD_SHA='df765fd0e357925bab51891c72019018bb43b65fcd6e97addf0582c9bdf5e5d7'
HELPER=HERE/'window-r11.py'
SHA='7e7b8b6b85513f540b3aca31911d2c1539895851fd8626f65b521352405b8e03'
TARGET='gascity/codex'

def completed_binding(w):
    s=BIND.lstat()
    assert stat.S_ISDIR(s.st_mode) and s.st_uid==1000 and stat.S_IMODE(s.st_mode)==0o700,'bind root authority'
    intent=json.loads(w.read(BIND/'binding-intent.json','0f85dbaa6de8c174c3bc4950955777bb23621cb3bc8bd55ce9546c5e029e4b37'))
    assert intent['executor_sha256']==BIND_SHA and intent['description_sha256']==DESCRIPTION_SHA
    assert intent['worker_launched'] is False
    result=json.loads(w.read(BIND/'result.json','0e8003f3fa54558537cd93dcd2863ab5bcd0aef8be8af1ec11c198472ad022d2'))
    assert result==dict(ok=True,bead='ga-e0t1.20',contract_bound=True,routed=False,assigned=False,
        worker_launched=False,live_configuration_changed=False)
    bound=json.loads(w.read(BIND/'task-after.json','e58d90d46f6422aeb6d65a135daf41389fb5d1b9e0115f1019f6b2027abf7dcb'))
    assert bound['metadata']==intent['metadata']
    return bound


def continued_task(current,bound):
    # gc embeds parent audit history in each child read. Retain exact own
    # fields and all parent fields except a monotonic append-only audit update.
    from datetime import datetime
    assert set(current)==set(bound), 'bound task field set'
    for key in bound:
        if key!='dependencies':assert current[key]==bound[key], ('bound task changed',key)
    old=bound['dependencies'];new=current['dependencies']
    assert isinstance(old,list) and isinstance(new,list) and len(old)==len(new)==1
    old=old[0];new=new[0]
    assert set(old)==set(new), 'parent field set'
    for key in old:
        if key not in ('notes','updated_at'):assert new[key]==old[key], ('parent changed',key)
    assert isinstance(new['notes'],str) and new['notes'].startswith(old['notes']), 'parent audit erased'
    a=datetime.fromisoformat(old['updated_at']);z=datetime.fromisoformat(new['updated_at'])
    assert a.tzinfo is not None and z.tzinfo is not None and z>=a, 'parent audit time'


def main():
    assert os.getuid()==os.geteuid()==1000 and globals().get('_SOURCE_SHA')
    assert hashlib.sha256(Path(__file__).read_bytes()).hexdigest()==_SOURCE_SHA
    raw=HELPER.read_bytes();assert hashlib.sha256(raw).hexdigest()==SHA
    m=types.ModuleType('route_window');m.__file__=str(HELPER)
    exec(compile(raw,str(HELPER),'exec',dont_inherit=True),m.__dict__)
    w=m.w;b,o,owned=w.load_support();w.pins()
    assert json.loads(w.read(w.ROOT/'stage-pass.json'))==dict(ok=True,worker_launched=False)
    bound=completed_binding(w)
    w.read(w.CITY/'city.toml',w.CITY_SHA[1]);w.read(w.RECEIPT,w.RECEIPT_SHA[1])
    ROOT.mkdir(mode=0o700);w.ROOT=ROOT
    def run(name,args):return w.phase(name,args,b,owned)
    def bead(name):
        v=json.loads(run(name,w.GC+['--rig','gascity','bd','show','ga-e0t1.20','--json'])['stdout'])
        assert isinstance(v,list) and len(v)==1 and v[0]['id']=='ga-e0t1.20'
        return v[0]
    before_host=w.host(o)
    before=bead('task-before-read');w.save('task-before.json',before)
    continued_task(before,bound)
    assert before['status']=='open' and not before.get('assignee')
    assert 'gc.routed_to' not in before['metadata']
    # ga-e0t1.20: the Template pre-route, built from the reviewed ga-6utp preroute pieces (preroute.check itself
    # requires a root holding only this worktree), is the last step before the sling. pr.survey is given the
    # worktree, not the shared Template root, whose other worktrees are not this window's.
    shown=run('preroute-bead',w.GC+['--rig','gascity','bd','show','ga-e0t1.20','--json'])['stdout']
    bead_json=ROOT/'preroute-bead.json'
    fd=os.open(bead_json,os.O_WRONLY|os.O_CREAT|os.O_EXCL,0o600)
    with os.fdopen(fd,'w') as out:out.write(shown)
    raw=PREROUTE.read_bytes();assert hashlib.sha256(raw).hexdigest()==PREROUTE_SHA
    tools=CANDIDATE_GIT.read_bytes();assert hashlib.sha256(tools).hexdigest()==CANDIDATE_GIT_SHA
    cg=types.ModuleType('candidate_git');cg.__file__=str(CANDIDATE_GIT);sys.modules['candidate_git']=cg
    exec(compile(tools,str(CANDIDATE_GIT),'exec',dont_inherit=True),cg.__dict__)
    pr=types.ModuleType('preroute');pr.__file__=str(PREROUTE);sys.modules['preroute']=pr
    exec(compile(raw,str(PREROUTE),'exec',dont_inherit=True),pr.__dict__)
    # Template variant: the reviewed preroute.check requires the candidate root to hold exactly the worktree,
    # which a Template worktree root cannot. It calls the same reviewed pieces, in the same order.
    record=pr.load_record(RECORD,RECORD_SHA)
    slice_root=pr.user_slice(1000)
    city=pr.city_problems(slice_root,record)
    assert not city,('the city is not quiet',city)
    root=Path('/home/loucmane/gas-city-ops-candidate-worktrees');common=Path('/home/loucmane/gas-city-ops/.git');work=root/'ga-e0t1.20'
    admin=cg.verify_linked(root,common,work,'ga-e0t1.20')
    head=cg.git(admin,work,'rev-parse','--verify','HEAD^{commit}').decode().strip()
    assert head==w.BASE,('worktree HEAD',head)
    cg.no_gitlinks(admin,work,head)
    cg.no_drivers(admin,work)
    w.contract().validate_rule_status(cg.git(admin,work,'status','--porcelain','--ignored','-z','--untracked-files=all'))
    for rel,pin in w.contract().RULES.items():
        w.read(work/rel,pin)
        assert stat.S_IMODE((work/rel).lstat().st_mode)==0o644,'local policy mode'
    w.read(Path('/home/loucmane/.codex/rules/default.rules'),w.contract().DEFAULT_RULES)
    attempts=[]
    for _ in range(5):
        problems=pr.survey(work,1000,slice_root,record['hidden'])
        attempts.append(problems)
        if not problems:
            break
        time.sleep(2)
    w.save('survey-attempts.json',dict(attempts=attempts))
    assert not problems,('processes hold the worktree',problems)
    shown_bead=json.loads(shown);shown_bead=shown_bead[0] if isinstance(shown_bead,list) else shown_bead
    assert shown_bead.get('id')=='ga-e0t1.20','task id'
    assert (shown_bead.get('metadata') or {}).get('gc.work_dir')==str(work),'gc.work_dir'
    assert hashlib.sha256(str(shown_bead.get('description','')).encode()).hexdigest()==DESCRIPTION_SHA,'description'
    w.contract().validate_task(shown_bead,'bound')
    # The full JSON is preserved above. The supported bounded text view omits parent history.
    brief=run('preroute-brief',w.GC+['--rig','gascity','bd','show','ga-e0t1.20'])['stdout']
    assert len(brief.encode())<9000 and 'ga-e0t1.20' in brief,'bounded worker brief'
    checked=dict(ok=True,worktree=str(work),admin=str(admin),bead='ga-e0t1.20',base=head,controller=record['controller'],
        variant='template-root-pieces')
    w.save('preroute.json',checked)
    argv=w.GC+['--rig','gascity','sling',TARGET,'ga-e0t1.20','--no-formula','--no-convoy','--json']
    preview=json.loads(run('route-preview',argv+['--dry-run'])['stdout'])
    assert preview['schema_version']=='1' and preview['success'] and preview['dry_run'] and not preview['routed']
    assert preview['bead_id']=='ga-e0t1.20' and preview['target']==TARGET
    assert bead('after-preview-read')==before
    assert w.host(o)==before_host
    w.save('route-intent.json',dict(before=before,argv=argv,executor_sha256=_SOURCE_SHA))
    result=json.loads(run('route',argv)['stdout'])
    assert result['schema_version']=='1' and result['success'] and result['routed'] and not result['dry_run']
    assert result['bead_id']=='ga-e0t1.20' and result['target']==TARGET
    assert not result.get('convoy_id') and not result.get('molecule_id')
    after=bead('task-after-read');w.save('task-after.json',after)
    assert after['metadata']==dict(before['metadata'],**{'gc.routed_to':TARGET})
    for key in set(before)|set(after):
        if key not in ('metadata','updated_at'):assert before.get(key)==after.get(key),key
    assert w.host(o)==before_host
    w.save('result.json',dict(ok=True,routed_once=True,rigs_suspended=True,worker_launched=False,
        fresh_full_queue_audit_required_before_resume=True))
    print(json.dumps(w.record('result.json')))

if __name__=='__main__':main()
