"""P12 step 1: observe the running revision and derive the receipt input. Read-only except its own records.

gct-oak5 RECEIPT. Generated by make_p12.py from the executed P11 input; the logic is P11's. The installed receipt
06a3f58a minus its generated fields becomes the input draft. Three leaves change: the permission revision
03f16ea2 -> 06076790 (the activated Template candidate lane, traced live from the controller) and the
template_commit and Template member head cfd353f3 -> 3474abfa (Template PR 72, the M11 authority). One typed
profile is appended: gas-city-template/gc.implementation-worker on the claude-template-candidate provider. The
signing and Operations candidate profiles, Core f45a6262, the signing provider version d4e57767 and the argv model
claude-opus-5-5 are asserted unchanged, and all three live wrappers must report their pinned versions.
`m11_acceptance()` verifies M11's reviewed records and that the live metadata pair is the accepted M11 pair
succeeding the M10 file 2b902a83.

  python3 -I -S -B source-launch.py p12-input.py <own sha256>
"""
from datetime import datetime, timezone
import copy
import hashlib
import json
import os
from pathlib import Path
import stat
import subprocess
import sys
import types

HERE = Path(__file__).parent
ROOT = Path('/var/tmp/gct-oak5-p12-input-20260927')
CITY = Path('/home/loucmane/gascity/city')
RECEIPT = CITY/'.gc/runtime/provisioning/receipt.json'
WORKER = Path('/home/loucmane/gas-city-template/bin/gct-claude-signing-worker')
OBS = Path('/home/loucmane/gas-city-ops-worktrees/ga-e0t1-orchestrator-bootstrap/docs/ai/work-tracking/active/'
           '20260903-ga-e0t1-orchestrator-bootstrap-ACTIVE/reports/ga-e0t1.14-rollout-r1/package-r4/resume-r4b/'
           'recovery-source-r2/observe_recovery.py')
OBS_SHA = 'f5357d222f0a2f7ceb9e1a830533f20a4868fe5f3beb247de335843b730bdd78'
GC_SHA = '207a78e27fe4b470ec5926ded186813543568683cf26d7d7487e6c185d8f3e8f'
CORE = 'f45a626213dc5b8d0b52f097d978cca56e506df0'
RECEIPT_OLD_SHA = '06a3f58a060a20b28d0bea86105e22278ef8983f0f80cba4d725788cd3a8bbd5'
TEMPLATE_OLD = 'cfd353f30f465cdf67bbd41fab48812fe5b9617e'
TEMPLATE = '3474abfaec255f7ea4266ce8aa35218afcfc89b0'
REVISION_OLD = '03f16ea2f9d46393f749c93a397f5a6020210d0f2252fe0a45205ee4263ce712'
REVISION = '06076790c31448212545edc1e741f592ed5b23ac54debbefb5e6da847143d753'
VERSION = 'gct-claude-signing-worker 1 dependencies_sha256=d4e57767d03accd708ce8876580096bb17bce023d6dc6e664fffee4367ea3c57'
MODEL = 'claude-opus-5-5'
# The typed candidate profile, under the identity the ga-6utp r12 reload resolved. Its argv and PATH are Core's
# own composition (observed by compose-main.go and re-proven by the observer); its check path is the signing
# lane's; its provider is the M9-pinned wrapper; its toolchain is the reviewed registry record's python pin.
CANDIDATE_WORKER = Path('/home/loucmane/gas-city-template/bin/gct-claude-candidate-worker')
CANDIDATE_POLICY = '/home/loucmane/gas-city-template/templates/claude/candidate-control-policy.json'
CANDIDATE_ROOT = '/home/loucmane/gas-city-ops-candidate-worktrees'
CANDIDATE = {
    'approval_policy': 'dontAsk',
    'argv': [str(CANDIDATE_WORKER), '--permission-mode', 'dontAsk', '--effort', 'max', '--model', MODEL,
             '--settings', CANDIDATE_POLICY, '--add-dir', CANDIDATE_ROOT,
             '--settings', '/home/loucmane/gascity/city/.gc/settings.json'],
    'check_path': {
        'path': '/home/loucmane/gascity/home/cache/repos/954ed14987da288bfb98feee4cdab5043a44de1a8a9cf47afaaa0ce6e438fd5f'
                '/gascity/assets/scripts/checks/build-artifact-valid.sh',
        'sha256': '71f17450e127055c8304a3cb44ce87b2439abe04ba41f225c7b386be3dc73911'},
    'control_policy': {'path': CANDIDATE_POLICY,
                       'sha256': 'a3eda9160871c0f25bbd5f1b6680fbc932692d6cee2c4f7dc702ad355954ae49'},
    'environment': {'PATH': '/home/loucmane/gascity/bin:/usr/local/bin:/usr/bin:/bin'},
    'name': 'gascity/operations-candidate-worker',
    'network_policy': 'no-explicit-egress-denial',
    'profile_kind': 'candidate',
    'provider': {'name': 'claude', 'path': str(CANDIDATE_WORKER), 'resolved_path': str(CANDIDATE_WORKER),
                 'sha256': 'e4442971fd3188208eaf22974aaaf55f949b8f51041775f041ecb00a66de92a3',
                 'version_args': ['--version'],
                 'version': 'gct-claude-candidate-worker 1 '
                            'dependencies_sha256=a35dd4131ed3baa3875b9866aa86e39192d1f96f3f4dd55d8a10d12921eea446'},
    'sandbox_mode': 'claude-native-required-with-five-command-exclusions',
    'signer_identity': 'none',
    'toolchains': [{'name': 'python', 'executable': {
        'path': '/usr/bin/python3.12', 'resolved_path': '/usr/bin/python3.12',
        'sha256': 'e50d468e8b0adfb05733f5b87b3cff34829c4a8c1aea50c865aa8bdfe4bb150f',
        'version_args': ['--version'], 'version': 'Python 3.12.3'}}],
    'writable_roots': [CANDIDATE_ROOT],
}
# The typed Template candidate profile, under the identity the gct-oak5 activation reload resolved. Its argv and
# PATH are Core's own composition (template/compose-main.go, re-proven by the observer). Its check path is the
# Operations candidate's, the signing lane check: the Template rig imports the same gc pack at the same version.
# Its provider is the M11-pinned wrapper; its policy has the same five sandbox exclusions as the Operations
# candidate policy; its toolchain is the Operations candidate's python pin.
TEMPLATE_WORKER = Path('/home/loucmane/gas-city-template/bin/gct-claude-template-candidate-worker')
TEMPLATE_POLICY = '/home/loucmane/gas-city-template/templates/claude/template-candidate-control-policy.json'
TEMPLATE_ROOT = '/home/loucmane/gas-city-template-candidate-worktrees'
TEMPLATE_CANDIDATE = {
    'approval_policy': 'dontAsk',
    'argv': [str(TEMPLATE_WORKER), '--permission-mode', 'dontAsk', '--effort', 'max', '--model', MODEL,
             '--settings', TEMPLATE_POLICY, '--add-dir', TEMPLATE_ROOT,
             '--settings', '/home/loucmane/gascity/city/.gc/settings.json'],
    'check_path': copy.deepcopy(CANDIDATE['check_path']),
    'control_policy': {'path': TEMPLATE_POLICY,
                       'sha256': '6b2f160d4999781db17ddf117b482a9c20432032c1162fed453a06ba7376fec1'},
    'environment': {'PATH': '/home/loucmane/gascity/bin:/usr/local/bin:/usr/bin:/bin'},
    'name': 'gas-city-template/gc.implementation-worker',
    'network_policy': 'no-explicit-egress-denial',
    'profile_kind': 'candidate',
    'provider': {'name': 'claude', 'path': str(TEMPLATE_WORKER), 'resolved_path': str(TEMPLATE_WORKER),
                 'sha256': '229d33557326abc8bafceadb06ae12ba2a2d9189e137ff0e1378d35dcf69491c',
                 'version_args': ['--version'],
                 'version': 'gct-claude-template-candidate-worker 1 '
                            'dependencies_sha256=3cd85706cd98a25bd50ef12c5dfa59e34054396db81913cd4692728e6ca7ffb3'},
    'sandbox_mode': 'claude-native-required-with-five-command-exclusions',
    'signer_identity': 'none',
    'toolchains': copy.deepcopy(CANDIDATE['toolchains']),
    'writable_roots': [TEMPLATE_ROOT],
}
M11 = Path('/home/loucmane/gas-city-ops-worktrees/ga-e0t1-orchestrator-bootstrap/reports/m11/q')
M11_RELEASE = 'gct-oak5-template-candidate-lane-metadata-m11-20260927'
M11_AUTHORITY = ('template-pr72-canonical', '/home/loucmane/gas-city-template', TEMPLATE)
# The succession link is previous_metadata.manifest_sha256, the M10 canonical FILE digest. The top-level
# previous_sha256 is the previous Core binary (gc fce2e9a0) and is not a manifest link.
PREVIOUS_MANIFEST_FILE = '2b902a83577acf71f9dd93a97d43d8478f7c4b291b0992e8ba5a5e44fe66f7f2'
GENERATED = ('canary_runner', 'receipt_sha256')
ENV = dict(HOME='/home/loucmane', USER='loucmane', LOGNAME='loucmane',
           PATH='/home/loucmane/gascity/bin:/usr/local/bin:/usr/bin:/bin', XDG_RUNTIME_DIR='/run/user/1000',
           DBUS_SESSION_BUS_ADDRESS='unix:path=/run/user/1000/bus', GC_HOME='/home/loucmane/gascity/home',
           GIT_OPTIONAL_LOCKS='0', LC_ALL='C.UTF-8', PYTHONDONTWRITEBYTECODE='1', DO_NOT_TRACK='1')


def require(ok, reason):
    if not ok:
        raise RuntimeError(reason)


def read(path, expected=None):
    fd = os.open(path, os.O_RDONLY | os.O_NOFOLLOW | os.O_NOATIME | os.O_CLOEXEC)
    try:
        before = os.fstat(fd)
        require(stat.S_ISREG(before.st_mode) and before.st_uid == 1000 and before.st_nlink == 1,
                'file authority: ' + str(path))
        chunks = []
        while chunk := os.read(fd, 1048576):
            chunks.append(chunk)
        raw = b''.join(chunks)
        require(before == os.fstat(fd) and len(raw) == before.st_size, 'file changed during read: ' + str(path))
    finally:
        os.close(fd)
    require(expected is None or hashlib.sha256(raw).hexdigest() == expected, 'digest drift: ' + str(path))
    return raw


def write(name, value):
    raw = value if isinstance(value, bytes) else (json.dumps(value, indent=2, sort_keys=True) + '\n').encode()
    fd = os.open(ROOT/name, os.O_WRONLY | os.O_CREAT | os.O_EXCL | os.O_NOFOLLOW | os.O_CLOEXEC, 0o600)
    with os.fdopen(fd, 'wb') as stream:
        stream.write(raw); stream.flush(); os.fsync(stream.fileno())
    return hashlib.sha256(raw).hexdigest()


def observer():
    raw = read(OBS, OBS_SHA)
    value = types.ModuleType('observe_recovery'); value.__file__ = str(OBS)
    exec(compile(raw, str(OBS), 'exec', dont_inherit=True), value.__dict__)
    value.GC_SHA = GC_SHA
    return value


def serialize(draft):
    return (json.dumps(draft, indent=2, sort_keys=True) + '\n').encode()


def derive(receipt, revision):
    """Pure: the receipt input for the M11 state, with every predecessor asserted."""
    draft = copy.deepcopy(receipt)
    for key in GENERATED:
        require(key in draft, 'generated field missing: ' + key)
        draft.pop(key)
    require(len(draft['profiles']) == 2, 'profile cardinality')
    for each in draft['profiles']:
        require('worker_profile_sha256' in each, 'generated profile digest missing')
        each.pop('worker_profile_sha256')
    profile, candidate = draft['profiles']
    require(profile['name'] == 'gascity/gc.implementation-worker' and profile['profile_kind'] == 'signing',
            'signing profile predecessor')
    require(candidate == CANDIDATE, 'candidate profile unchanged')
    require(profile['provider']['version'] == VERSION, 'provider version unchanged')
    argv = profile['argv']
    positions = [i for i, token in enumerate(argv) if token == '--model']
    require(len(positions) == 1 and argv[positions[0] + 1] == MODEL, 'argv model unchanged')
    cores = [h for h in draft['member_heads'] if h['name'] == 'core']
    require(len(cores) == 1 and cores[0]['commit'] == CORE, 'core member head unchanged')
    # The changes. The gct-oak5 activation rendered the Template candidate lane, which moved the composed
    # revision to the exact value the controller traced on 2026-09-27; M11 moved the Template authority to the
    # canonical checkout at 3474abfa (Template PR 72); the lane's typed profile is appended.
    require(draft['permission_revision'] == REVISION_OLD and revision == REVISION, 'revision predecessor')
    draft['permission_revision'] = revision
    require(draft['template_commit'] == TEMPLATE_OLD, 'template predecessor')
    draft['template_commit'] = TEMPLATE
    heads = [h for h in draft['member_heads'] if h['name'] == 'template']
    require(len(heads) == 1 and heads[0]['commit'] == TEMPLATE_OLD, 'template member head predecessor')
    heads[0]['commit'] = TEMPLATE
    require(TEMPLATE_CANDIDATE['check_path'] == CANDIDATE['check_path'], 'Template check path is the candidate check')
    require(all(each['name'] != TEMPLATE_CANDIDATE['name'] for each in draft['profiles']), 'Template profile absent')
    draft['profiles'].append(copy.deepcopy(TEMPLATE_CANDIDATE))
    return draft


def proven_draft(root=None):
    """For later P12 steps: the recorded draft must be exactly derive() of the preserved
    old receipt and the recorded revision. Independent of the live receipt."""
    root = ROOT if root is None else root
    result = json.loads(read(root/'result.json'))
    require(result['ok'] is True and result['receipt_before_sha256'] == RECEIPT_OLD_SHA, 'input result')
    revision = json.loads(read(root/'revision.json', result['revision_sha256']))
    require(revision['config_revision'] == result['permission_revision'], 'input revision record')
    receipt = json.loads(read(root/'receipt.before.json', RECEIPT_OLD_SHA))
    raw = read(root/'receipt.input.draft.json', result['draft_sha256'])
    require(raw == serialize(derive(receipt, revision['config_revision'])), 'draft is not the reviewed derivation')
    return dict(path=root/'receipt.input.draft.json', raw=raw, sha256=result['draft_sha256'],
                revision=revision['config_revision'], m11=result['m11'])


def m11_acceptance():
    """The M11 committed pair, proven only from M11 reviewed records and the live files."""
    record = json.loads(read(M11/'commit-pass.json'))
    require(set(record) == {'verdict', 'bindings', 'reviewers'} and record['verdict'] == 'COMMIT_PASS'
            and set(record['bindings']) == {'package_sha256', 'acceptance_sha256'}, 'M11 commit review record')
    people = record['reviewers']
    require(len(people) == 2 and len({p['reviewer_id'] for p in people}) == 2, 'two distinct M11 commit reviews')
    seen = set()
    for person in people:
        require(set(person) == {'reviewer_id', 'provenance_path', 'provenance_sha256'}, 'M11 review provenance')
        raw = read(Path(person['provenance_path']), person['provenance_sha256'])
        info = os.stat(person['provenance_path'], follow_symlinks=False)
        proof = json.loads(raw)
        require(set(proof) == {'reviewer_id', 'verdict', 'bindings', 'assessment'}
                and proof['reviewer_id'] == person['reviewer_id'] and proof['verdict'] == 'COMMIT_PASS'
                and proof['bindings'] == record['bindings'] and isinstance(proof['assessment'], str)
                and proof['assessment'].strip(), 'M11 review content')
        seen |= {('path', person['provenance_path']), ('sha', person['provenance_sha256']),
                 ('inode', info.st_dev, info.st_ino)}
    require(len(seen) == 6, 'duplicate M11 review provenance')
    package = record['bindings']['package_sha256']
    acceptance = json.loads(read(M11/'committed-acceptance.json', record['bindings']['acceptance_sha256']))
    require(acceptance['ok'] is True and acceptance['lease_expired'] is True
            and acceptance['package_sha256'] == package, 'M11 acceptance')
    restored = json.loads(read(M11/'restored.json'))
    require(restored['ok'] is True and restored['accepted'] is True, 'M11 restoration')
    manifest = json.loads(read(M11/'manifest.json'))
    last = manifest['integrity']['repositories'][-1]
    require(manifest['release_id'] == M11_RELEASE
            and manifest['previous_metadata']['manifest_sha256'] == PREVIOUS_MANIFEST_FILE
            and manifest['manifest_sha256'] == acceptance['manifest_sha256']
            and (last['name'], last['path'], last['commit']) == M11_AUTHORITY, 'M11 release binding')
    read(CITY/'.gc/platform/install-manifest.json', acceptance['canonical_file_sha256'])
    read(CITY/'.gc/platform/install-receipt.json', acceptance['receipt_file_sha256'])
    return dict(package_sha256=package, acceptance_path=str(M11/'committed-acceptance.json'),
                acceptance_sha256=record['bindings']['acceptance_sha256'],
                manifest_sha256=acceptance['manifest_sha256'], receipt_sha256=acceptance['receipt_sha256'],
                canonical_file_sha256=acceptance['canonical_file_sha256'],
                receipt_file_sha256=acceptance['receipt_file_sha256'])


def latest_cycle(records, pid):
    require(records, 'no controller cycle in the trace window')
    latest = max(records, key=lambda item: item['seq'])
    require(latest['controller_pid'] == pid and latest['gc_commit'] == CORE
            and latest['completion_status'] == 'completed', 'live controller cycle drift')
    age = (datetime.now(timezone.utc) - datetime.fromisoformat(latest['ts'].replace('Z', '+00:00'))).total_seconds()
    require(0 <= age <= 120 and latest['fields']['active_template_count'] == 0, 'stale or active controller cycle')
    return latest


def main():
    require(globals().get('_SOURCE_SHA') and read(Path(__file__), _SOURCE_SHA), 'source-bound entry required')
    require(len(sys.argv) == 1, 'no arguments')
    require(not os.path.lexists(ROOT), 'input root consumed')
    m11 = m11_acceptance()
    receipt_raw = read(RECEIPT, RECEIPT_OLD_SHA)
    receipt = json.loads(receipt_raw)
    o = observer()
    host = o.host_observation()
    version = subprocess.run([str(WORKER), '--version'], env=ENV, cwd='/', stdin=subprocess.DEVNULL,
                             capture_output=True, text=True, timeout=60, check=False)
    require(version.returncode == 0 and version.stdout.strip() == VERSION, 'live worker dependency version')
    candidate = subprocess.run([str(CANDIDATE_WORKER), '--version'], env=ENV, cwd='/', stdin=subprocess.DEVNULL,
                               capture_output=True, text=True, timeout=60, check=False)
    require(candidate.returncode == 0 and candidate.stdout.strip() == CANDIDATE['provider']['version'],
            'live candidate worker dependency version')
    template = subprocess.run([str(TEMPLATE_WORKER), '--version'], env=ENV, cwd='/', stdin=subprocess.DEVNULL,
                              capture_output=True, text=True, timeout=60, check=False)
    require(template.returncode == 0 and template.stdout.strip() == TEMPLATE_CANDIDATE['provider']['version'],
            'live Template candidate worker dependency version')
    trace = subprocess.run(['/home/loucmane/gascity/bin/gc', '--city', str(CITY), 'trace', 'show', '--type',
                            'cycle_result', '--since', '2m', '--json'], env=ENV, cwd='/',
                           stdin=subprocess.DEVNULL, capture_output=True, text=True, timeout=30, check=False)
    require(trace.returncode == 0, 'trace read refused')
    latest = latest_cycle(json.loads(trace.stdout)['records'], host['host']['pid'])
    draft = derive(receipt, latest['config_revision'])
    require(o.host_observation() == host and m11_acceptance() == m11, 'host or M11 pair changed during observation')
    ROOT.mkdir(mode=0o700)
    require(write('receipt.before.json', receipt_raw) == RECEIPT_OLD_SHA, 'receipt copy')
    draft_sha = write('receipt.input.draft.json', serialize(draft))
    revision_sha = write('revision.json', latest)
    result = dict(ok=True, draft_sha256=draft_sha, revision_sha256=revision_sha,
                  permission_revision=latest['config_revision'], worker_version=version.stdout.strip(),
                  candidate_worker_version=candidate.stdout.strip(),
                  template_candidate_worker_version=template.stdout.strip(),
                  receipt_before_sha256=RECEIPT_OLD_SHA, m11=m11, host=host, receipt_installed=False,
                  worker_launched=False)
    print(json.dumps(dict(result_sha256=write('result.json', result), draft_sha256=draft_sha,
                          permission_revision=latest['config_revision'])))


if __name__ == '__main__':
    main()
