"""Generate the P9 worker receipt refresh from the executed P8 chain by count-checked substitutions.

  python3 -I -B make_p9.py

P9 changes one receipt leaf: permission_revision 2113693e -> the traced running revision, which must differ
(the ga-6utp r12 activation reload moved it to 83c41af6 by composing the candidate agent and provider). The
core member head (deefb98b), the Template (cfd353f3), the provider version (d4e57767) and the model are asserted
unchanged. The platform metadata predecessor is M8 (manifest file 63820eac, reports/m8/q). The Core image is
unchanged, so P9 reuses P8's reviewed diagnostic builds (compose e123ee37, preflight 73d4e14c) and P8's builder
and generator sources in place. The receipt keeps its single signing profile; the candidate lane's typed receipt
belongs to the first candidate window.
"""
import hashlib
import sys
from pathlib import Path

HERE = Path(__file__).parent
P8 = HERE.parent/'p8'
RECEIPT_P8, RECEIPT_P8_NEW = ('7cf59ab9e5a43fd7bca97028e7faaa2b2f9bfb927a663b4588c66e846e4e425d',
                              '23eeb222d6d5c0afcf8dc8c01a99dfc7b57fbecfdbc0a1f7ca83d3319181d78e')
CORE_P8_OLD, CORE = '9faeabc2892d8c7133111e13ad55af66790a2ac6', 'deefb98b2aed07875df31351d081fbac195cb1cd'
REVISION_OLD = '2113693eefd3a9c905554a294e36ab3b5a17bc63004280b7144ff069ef75acc2'
M7_RELEASE, M8_RELEASE = 'template-pr71-core-seq15-metadata-m7-20260926', 'ops-candidate-lane-metadata-m8-20260926'
M6_FILE, M7_FILE = ('7f335ad83091a1a907b628fa5813c7daf6a530340a2ed404476797b5db90fefb',
                    '4bec5ef14bd81f6dc1830ada48fc502937ff91a531981dfff3fde5aaa92a9759')
INPUT_OLD, INPUT_ROOT = '/var/tmp/ga-e0t1.18-p8-input-20260926', '/var/tmp/ga-e0t1.18-p9-input-20260926'
COMPOSE_OLD, COMPOSE_ROOT = '/var/tmp/ga-e0t1.18-p8-compose-20260926', '/var/tmp/ga-e0t1.18-p9-compose-20260926'
READY_OLD, READY_ROOT = '/var/tmp/ga-e0t1.18-p8-readiness-20260926', '/var/tmp/ga-e0t1.18-p9-readiness-20260926'
ADOPT_OLD, ADOPT_ROOT = '/var/tmp/ga-e0t1.18-p8-adoption-20260926', '/var/tmp/ga-e0t1.18-p9-adoption-20260926'


def sha(raw):
    return hashlib.sha256(raw).hexdigest()


def source(path, digest):
    raw = Path(path).read_bytes()
    if sha(raw) != digest:
        raise SystemExit('reviewed source drift: %s' % path)
    return raw.decode()


def substitute(text, substitutions, name):
    for old, new, count in substitutions:
        found = text.count(old)
        if found != count:
            raise SystemExit('%s: expected %d occurrence(s) of %r, found %d' % (name, count, old[:80], found))
        text = text.replace(old, new)
    return text


def write(name, text):
    path = HERE/name
    data = text.encode() if isinstance(text, str) else text
    path.write_bytes(data)
    path.chmod(0o644)
    print(name, sha(data))
    return sha(data)


def docstring(text, new):
    end = text.index('"""\n', 3) + 4
    return new + text[end:]


DERIVE_P8 = (
    "    # Sequence 15 changed no embedded pack path, so the composed revision must be unchanged.\n"
    "    require(draft['permission_revision'] == REVISION and revision == REVISION, 'revision unchanged')\n")
DERIVE_P9 = (
    "    # The ga-6utp r12 activation reload composed the candidate agent and provider, which moved the revision.\n"
    "    require(draft['permission_revision'] == REVISION_OLD and revision != REVISION_OLD\n"
    "            and len(revision) == 64 and all(c in '0123456789abcdef' for c in revision), 'revision predecessor')\n"
    "    draft['permission_revision'] = revision\n")
CORE_P8 = (
    "    require(len(cores) == 1 and cores[0]['commit'] == CORE_OLD, 'core member head predecessor')\n"
    "    cores[0]['commit'] = CORE\n")
CORE_P9 = "    require(len(cores) == 1 and cores[0]['commit'] == CORE, 'core member head unchanged')\n"


def input_script():
    text = source(P8/'p8-input.py', '30f5e510c80c937df64d625a9970431c9e29d776a013102e4553238f1daa5c16')
    header = ('''"""P9 step 1: observe the running revision and derive the receipt input. Read-only except its own records.

ga-e0t1.18 lane adoption. Generated by make_p9.py from the executed P8 input (30f5e510); the logic is P8's.
The installed receipt 23eeb222 minus its generated fields becomes the input draft. Exactly one field changes:
permission_revision 2113693e -> the traced running revision, which must differ (the ga-6utp r12 activation
reload moved it). The core member head deefb98b, the Template cfd353f3, the provider version d4e57767 and the
argv model claude-opus-5-5 are asserted unchanged. `m8_acceptance()` verifies M8's reviewed records and that
the live metadata pair is the accepted M8 pair succeeding the M7 file 4bec5ef1.

  python3 -I -S -B source-launch.py p9-input.py <own sha256>
"""
''')
    text = docstring(text, '')
    text = substitute(text, [
        ("ROOT = Path('%s')" % INPUT_OLD, "ROOT = Path('%s')" % INPUT_ROOT, 1),
        ("RECEIPT_OLD_SHA = '%s'" % RECEIPT_P8, "RECEIPT_OLD_SHA = '%s'" % RECEIPT_P8_NEW, 1),
        ("REVISION = '%s'" % REVISION_OLD, "REVISION_OLD = '%s'" % REVISION_OLD, 1),
        ("CORE_OLD = '%s'\n" % CORE_P8_OLD, "", 1),
        (DERIVE_P8, DERIVE_P9, 1),
        (CORE_P8, CORE_P9, 1),
        ("'%s'" % M7_RELEASE, "'%s'" % M8_RELEASE, 1),
        ("PREVIOUS_MANIFEST_FILE = '%s'" % M6_FILE, "PREVIOUS_MANIFEST_FILE = '%s'" % M7_FILE, 1),
        ("previous_sha256 is the previous Core binary (gc b2760ea4)", "previous_sha256 is the previous Core binary (gc fce2e9a0)", 1),
        ('M7', 'M8', 22),
        ('m7', 'm8', 10),
        ('For later P8 steps', 'For later P9 steps', 1),
        ("the M6 canonical FILE digest.", "the M7 canonical FILE digest.", 1),
    ], 'p8-input.py')
    return write('p9-input.py', header + text)


def compose_script(input_sha):
    text = source(P8/'p8-observe-compose.py', '31444d33fd5e39fe8dc8daa454f1a27a35ceb66f9b5b05a64adfdc2c64a46cdf')
    header = ('''"""P9 step 2: one nonlaunching read-only composition observation; no receipt installation.

ga-e0t1.18 lane adoption. Generated by make_p9.py from the executed P8 observer (31444d33); the logic is P8's.
Only these bindings change: a fresh root, the P9 input, and the M8 metadata pair. The Core, the diagnostic build
(e123ee37), the host epoch, the closure policy (ce310593) and the surviving watchdog image are unchanged.
"""
''')
    text = docstring(text, '')
    text = substitute(text, [
        ("ROOT = Path('%s')" % COMPOSE_OLD, "ROOT = Path('%s')" % COMPOSE_ROOT, 1),
        ("INPUT_SOURCE = HERE/'p8-input.py'", "INPUT_SOURCE = HERE/'p9-input.py'", 1),
        ("INPUT_SHA = '30f5e510c80c937df64d625a9970431c9e29d776a013102e4553238f1daa5c16'", "INPUT_SHA = '%s'" % input_sha, 1),
        ('M7', 'M8', 1),
        ('m7', 'm8', 4),
    ], 'p8-observe-compose.py')
    return write('p9-observe-compose.py', header + text)


def readiness_script(compose_sha):
    text = source(P8/'p8-readiness.py', 'd440a6c0b35425a0e82ffff547d85bd406e8acdf499ec8a88698230308b05ca1')
    header = ('''"""P9 step 3: one native receipt-compatibility/readiness observation; no worker or install.

ga-e0t1.18 lane adoption. Generated by make_p9.py from the executed P8 readiness (d440a6c0); the logic is P8's.
Only these bindings change: a fresh root, the P9 observer and composition, and the pinned diagnostic generator
sources, which stay in the P8 package directory with their reviewed digests.
"""
''')
    text = docstring(text, '')
    text = substitute(text, [
        ("ROOT=Path('%s')" % READY_OLD, "ROOT=Path('%s')" % READY_ROOT, 1),
        ("BASE=HERE/'p8-observe-compose.py'", "BASE=HERE/'p9-observe-compose.py'", 1),
        ("BASE_SHA='31444d33fd5e39fe8dc8daa454f1a27a35ceb66f9b5b05a64adfdc2c64a46cdf'", "BASE_SHA='%s'" % compose_sha, 1),
        ("SUCCESSOR=HERE", "SUCCESSOR=HERE.parent/'p8'", 1),
        ("COMPOSITION=Path('%s/composition.json')" % COMPOSE_OLD, "COMPOSITION=Path('%s/composition.json')" % COMPOSE_ROOT, 1),
        ('# The P8 composition', '# The P9 composition', 1),
    ], 'p8-readiness.py')
    return write('p9-readiness.py', header + text)


def adopt_script(readiness_sha):
    text = source(P8/'p8-adopt.py', 'f75be2518e5132b61f89d741e02ff344b5c50d64f7eb1388c6b3b90ba98fd466')
    header = ('''"""P9 step 4: one receipt-only transaction through the unchanged reviewed provisioner.

ga-e0t1.18 lane adoption. Generated by make_p9.py from the executed P8 adoption (f75be251); the logic is P8's.
Only these bindings change: the P9 readiness, the old receipt 23eeb222, and the M8 accepted-deployment evidence
and platform self digests. The Core consumer, build evidence and controller are unchanged. The readiness-derived
constants stay None until readiness has passed.
"""
''')
    text = docstring(text, '')
    text = substitute(text, [
        ("ROOT=Path('%s')" % ADOPT_OLD, "ROOT=Path('%s')" % ADOPT_ROOT, 1),
        ("READY=Path('%s')" % READY_OLD, "READY=Path('%s')" % READY_ROOT, 1),
        ("READY_SOURCE=HERE/'p8-readiness.py'", "READY_SOURCE=HERE/'p9-readiness.py'", 1),
        ("READY_SHA='d440a6c0b35425a0e82ffff547d85bd406e8acdf499ec8a88698230308b05ca1'", "READY_SHA='%s'" % readiness_sha, 1),
        ("OLD_SHA='%s'" % RECEIPT_P8, "OLD_SHA='%s'" % RECEIPT_P8_NEW, 1),
        ("# Filled from the passed P8 readiness evidence", "# Filled from the passed P9 readiness evidence", 1),
        ("NEW_SHA='23eeb222d6d5c0afcf8dc8c01a99dfc7b57fbecfdbc0a1f7ca83d3319181d78e'\n"
         "NEW_SELF='076fff6631a70657fb11b197f51517c4b040a57fc2d67337de7b538322a8b784'\n"
         "READY_RESULT_SHA='a6cac0b99822e8432fa8b01b2a0c87bb212ff141c165d13d4921b2b75f8c8ee7'\n"
         "READY_BEFORE_SHA='70572871b3df5b63cce041f72fdc392a2ed1f9b8ee075462acedff2994a2c582'\n"
         "READY_PINS_SHA='82a4a70c43fa1e0d581f6d8c72b8c46c0478bdebca761f7b18cf05d43708765b'\n",
         "NEW_SHA=None\nNEW_SELF=None\nREADY_RESULT_SHA=None\nREADY_BEFORE_SHA=None\nREADY_PINS_SHA=None\n", 1),
        ('m7', 'm8', 6),
    ], 'p8-adopt.py')
    return write('p9-adopt.py', header + text)


def scripts():
    input_sha = input_script()
    compose_sha = compose_script(input_sha)
    readiness_sha = readiness_script(compose_sha)
    adopt_script(readiness_sha)
    write('source-launch.py', source(P8/'source-launch.py', '31bdeea83152c5ad0253a74d743f4d4d103dc7e14e7975da00055df6786d6dea'))
    write('typed-interoperability.json',
          source(P8/'typed-interoperability.json', '315dd4109310c13038c7fbcc4cc17f8b791721fbc343133d286dc21ee5776563'))


if __name__ == '__main__':
    if sys.argv[1:]:
        raise SystemExit(__doc__)
    scripts()
