"""Generate test_s2.py and make_envelope.py for sequence 16 from the executed sequence 15 files.

  python3 -I -B make_tests.py

Sources: designs/ga-e0t1.18-deploy/test_s2.py (sha 0cf33557) and make_envelope.py (sha 3649de29). Every change is an exact, count-checked substitution of a sequence 15 identity, pin or root for
its sequence 16 value; no test logic changes. See make_s2.py for what sequence 16 changes.
"""
import hashlib
from pathlib import Path

HERE = Path(__file__).parent
SRC = HERE.parent/'ga-e0t1.18-deploy'
TEST_SHA = '0cf33557e8cbca363ca4cec7ab2387565926934c5e3f90497ba7fee7d44143c0'

S15_ROOT = "/var/tmp/ga-e0t1.18-seq15-20260926"
S16_ROOT = "/var/tmp/ga-bebv-seq16-20260927"


def sha(raw):
    return hashlib.sha256(raw).hexdigest()


def apply(text, pairs):
    for old, new, count in pairs:
        found = text.count(old)
        if found != count:
            raise SystemExit('expected %d occurrence(s) of %r, found %d' % (count, old[:80], found))
        text = text.replace(old, new)
    return text


TEST_PAIRS = [
    ('"""Tests for the ga-e0t1.18 sequence 15 transition package.',
     '"""Tests for the ga-bebv sequence 16 transition package (generated by make_tests.py from sequence 15).', 1),
    ('  python3 -m pytest -q designs/ga-e0t1.18-deploy/test_s2.py',
     '  python3 -m pytest -q designs/ga-bebv-deploy/test_s2.py', 1),
    ("c.OLD='b2760ea407d8a5853fb7fbb3c184870ad4b6e9ccd763241a8ec59a8c3201d489'",
     "c.OLD='fce2e9a0bea6c79f257e55b6424cf9271405d58f916a1017f3c14e232ad5d13b'", 1),
    ("c.NEW='fce2e9a0bea6c79f257e55b6424cf9271405d58f916a1017f3c14e232ad5d13b'",
     "c.NEW='207a78e27fe4b470ec5926ded186813543568683cf26d7d7487e6c185d8f3e8f'", 1),
    ("'c.NEW_SIZE=134062284', \"m['sequence']==15\", \"receipt['sequence']==15\",",
     "'c.NEW_SIZE=134146157', \"m['sequence']==16\", \"receipt['sequence']==16\",", 1),
    ("\"commit='deefb98b2aed07875df31351d081fbac195cb1cd'\", \"tree='af5c3f045c1f50cd62c859f6dc58fa613e5f2f99'\",",
     "\"commit='f45a626213dc5b8d0b52f097d978cca56e506df0'\", \"tree='f1011adaf673937fbda1d254a53c8f0eadf17c5c'\",", 1),
    ("\"blob='e6e9ac576162bcdbde8fc05ecbb1943f55f0ce41'\",", "\"blob='2f4f844927bcbaa89123cd819fcc0b82f33c2eb1'\",", 1),
    ("\"receipt['before']==dict(sha256=c.OLD,size=134052980,\",",
     "\"receipt['before']==dict(sha256=c.OLD,size=134062284,\",", 1),
    ("\"S14_RECOVERY_ROOT=Path('/var/tmp/ga-e0t1.18-seq15-recovery-20260926')\"):",
     "\"S14_RECOVERY_ROOT=Path('/var/tmp/ga-bebv-seq16-recovery-20260927')\"):", 1),
    ("    artifact = Path('/var/tmp/ga-e0t1.18-build-20260926/gc-a')\n"
     "    assert sha(artifact) == 'fce2e9a0bea6c79f257e55b6424cf9271405d58f916a1017f3c14e232ad5d13b'\n"
     "    assert artifact.stat().st_size == 134062284\n",
     "    artifact = Path('/var/tmp/ga-bebv-build-20260927/gc-a')\n"
     "    assert sha(artifact) == '207a78e27fe4b470ec5926ded186813543568683cf26d7d7487e6c185d8f3e8f'\n"
     "    assert artifact.stat().st_size == 134146157\n", 1),
    ("    assert blob == 'e6e9ac576162bcdbde8fc05ecbb1943f55f0ce41'\n",
     "    assert blob == '2f4f844927bcbaa89123cd819fcc0b82f33c2eb1'\n", 1),
    ("\"sha256='7f335ad83091a1a907b628fa5813c7daf6a530340a2ed404476797b5db90fefb'\"),",
     "\"sha256='5a29dc596af192e0f314391453d25d6be548695a0defd64bdfc2fa76554e4993'\"),", 1),
    ("\"sha256='123a01818b86f977ceabab1207c57795a3780261e39599019aa37f7609febaac'\")):",
     "\"sha256='4c19802fc60f12695ec4080497b195278943185c4e8758f41feeac50e5b16092'\")):", 1),
    ("    assert sha('/home/loucmane/gascity/bin/gc') == 'b2760ea407d8a5853fb7fbb3c184870ad4b6e9ccd763241a8ec59a8c3201d489'\n",
     "    assert sha('/home/loucmane/gascity/bin/gc') == 'fce2e9a0bea6c79f257e55b6424cf9271405d58f916a1017f3c14e232ad5d13b'\n", 1),
    ("'--sequence': '15',", "'--sequence': '16',", 1),
    (S15_ROOT + "-t2", S16_ROOT + "-t2", 2),
    ("\"ROOT=Path('%s')\\nROOT=Path('%s-t1')\\n\"" % (S15_ROOT, S15_ROOT),
     "\"ROOT=Path('%s')\\nROOT=Path('%s-t1')\\n\"" % (S16_ROOT, S16_ROOT), 1),
    ("    assert str(s2.ROOT) == '%s'\n" % S15_ROOT, "    assert str(s2.ROOT) == '%s'\n" % S16_ROOT, 1),
    ("    assert s2.ATTEMPT == 'ga-mutg-adoption-20260926-r16'\n",
     "    assert s2.ATTEMPT == 'ga-mutg-adoption-20260927-r17'\n", 1),
    ("    assert str(s2.S14_ACCEPT_ROOT) == '/var/tmp/ga-e0t1.18-predecessor-20260926-r1'\n",
     "    assert str(s2.S14_ACCEPT_ROOT) == '/var/tmp/ga-bebv-predecessor-20260927-r1'\n", 1),
    ("    text = make.read_text().replace(\"HERE.parent/'ga-e0t1.15-deploy'/'s2_transition.py'\",\n"
     "                                    'Path(%r)' % str(HERE.parent/'ga-e0t1.15-deploy'/'s2_transition.py'))\n",
     "    text = make.read_text().replace(\"HERE.parent/'ga-e0t1.18-deploy'/'s2_transition.py'\",\n"
     "                                    'Path(%r)' % str(HERE.parent/'ga-e0t1.18-deploy'/'s2_transition.py'))\n", 1),
    ("    assert \"ROOT=Path('%s-t1')\" in text\n" % S15_ROOT, "    assert \"ROOT=Path('%s-t1')\" in text\n" % S16_ROOT, 1),
    ("    assert \"ATTEMPT='ga-mutg-adoption-20260926-r17'\" in text\n",
     "    assert \"ATTEMPT='ga-mutg-adoption-20260927-r18'\" in text\n", 1),
    ("    assert \"S14_ACCEPT_ROOT=Path('/var/tmp/ga-e0t1.18-predecessor-20260926-r2')\" in text\n",
     "    assert \"S14_ACCEPT_ROOT=Path('/var/tmp/ga-bebv-predecessor-20260927-r2')\" in text\n", 1),
    ("'ga-mutg-adoption-20260926-r16')\n", "'ga-mutg-adoption-20260927-r17')\n", 1),
]

ENVELOPE_PAIRS = [
    ('"""Create the sequence 15 broker envelope for the CURRENT attempt',
     '"""Create the sequence 16 broker envelope for the CURRENT attempt', 1),
    ("        '--artifact', '/var/tmp/ga-e0t1.18-build-20260926/gc-a',\n",
     "        '--artifact', '/var/tmp/ga-bebv-build-20260927/gc-a',\n", 1),
    ("        '--commit', 'deefb98b2aed07875df31351d081fbac195cb1cd',\n",
     "        '--commit', 'f45a626213dc5b8d0b52f097d978cca56e506df0',\n", 1),
    ("        '--tree', 'af5c3f045c1f50cd62c859f6dc58fa613e5f2f99',\n",
     "        '--tree', 'f1011adaf673937fbda1d254a53c8f0eadf17c5c',\n", 1),
    ("        '--sequence', '15']\n", "        '--sequence', '16']\n", 1),
    ("r\"^ROOT=Path\\('(/var/tmp/ga-e0t1\\.18-seq15-20260926(?:-t[0-9]+)?)'\\)$\"",
     "r\"^ROOT=Path\\('(/var/tmp/ga-bebv-seq16-20260927(?:-t[0-9]+)?)'\\)$\"", 1),
]
ENVELOPE_SOURCE_SHA = '3649de2960540cc72a6cb3f2c240b6915900efb4f52c23111524c9d1a125e755'


def main():
    raw = (SRC/'test_s2.py').read_bytes()
    if sha(raw) != TEST_SHA:
        raise SystemExit('sequence 15 test source drift')
    (HERE/'test_s2.py').write_text(apply(raw.decode(), TEST_PAIRS))
    raw = (SRC/'make_envelope.py').read_bytes()
    if sha(raw) != ENVELOPE_SOURCE_SHA:
        raise SystemExit('sequence 15 envelope source drift')
    (HERE/'make_envelope.py').write_text(apply(raw.decode(), ENVELOPE_PAIRS))
    print('test_s2.py', sha((HERE/'test_s2.py').read_bytes()))
    print('make_envelope.py', sha((HERE/'make_envelope.py').read_bytes()))


if __name__ == '__main__':
    main()
