"""Generate s2_transition.py (broker sequence 16) from the executed sequence 15 transition.

  python3 -I -B make_s2.py [output]

Source: designs/ga-e0t1.18-deploy/s2_transition.py (sha c6d74b61), the sequence 15 file that adopted Core
fce2e9a0 on 2026-09-26. Every change is one of the exact, count-checked substitutions below. Reviewers diff
s2_transition.py against the source; test_s2.py proves that the committed file equals this generator's output.

What sequence 16 changes, and why:
- Identity: Core fce2e9a0 -> 207a78e2 (ga-bebv S1, the ga-6umo hotfix: build source f45a6262 / tree f1011ada =
  merge 0b63856a, artifact blob 2f4f8449), broker sequence 16, fresh ROOT, attempt and accept root.
- Metadata preimages: the M9 pair (install manifest 5a29dc59, 129653 bytes; install receipt 4c19802f, 2549 bytes)
  replaces M6; M7, M8 and M9 were adopted after sequence 15.
- Cache: the new Core embeds the same pack content (S1b provenance: no path under internal/bootstrap/packs or
  examples changed, go.mod and go.sum unchanged), so the sequence 15 cache rule stands unchanged.
- City: the live-key inventory re-derived for this package is byte-identical to sequence 15's (143 links and 9
  manifests on 69fe9a2e, TSV digests 25735dc8 and 1ee92cb5), so the TSV pins are unchanged.
- Dolt: the watchdog still maps the deleted 69d00186 (uptime since 2026-09-24); the rule that admits 69d00186 or
  c.OLD stands, with c.OLD now fce2e9a0.
- Broker: active and running with its socket, as sequence 15 accepted; the sequence 15 broker rules stand.
Everything else, including the settled-scope wait, the 240 s budget, the broker-call marker and the recovery gate,
is the executed sequence 15 code.
"""
import hashlib
import json
from pathlib import Path

HERE = Path(__file__).parent
SOURCE = HERE.parent/'ga-e0t1.18-deploy'/'s2_transition.py'
SOURCE_SHA = 'c6d74b61621bdf57b718e55012154f484d621c4ac21526102ca1f7e78fd4379a'
OUT = HERE/'s2_transition.py'
if __name__ == '__main__':
    import sys as _sys
    if len(_sys.argv) == 2:
        OUT = Path(_sys.argv[1])

OLD = 'fce2e9a0bea6c79f257e55b6424cf9271405d58f916a1017f3c14e232ad5d13b'
OLD_SIZE = 134062284
NEW = '207a78e27fe4b470ec5926ded186813543568683cf26d7d7487e6c185d8f3e8f'
NEW_SIZE = 134146157
LINKS_TSV_SHA = '25735dc878f3fe0d0aed8b973d0689b22a8aa939e70c47ea1e356f4be818f172'
MANIFESTS_TSV_SHA = '1ee92cb52715b120b8201344bf43828e92452aa33b526775ee5a7db35dda6e47'


def sha(raw):
    return hashlib.sha256(raw).hexdigest()


def retry():
    """Optional retry.json {"retry": N, "reaccept": bool}, as in ga-e0t1.18 make_s2: N > 0 gives a fresh ROOT
    (-tN) and attempt; reaccept also gives a fresh accept root."""
    path = HERE/'retry.json'
    value = json.loads(path.read_text()) if path.exists() else {'retry': 0, 'reaccept': False}
    assert set(value) == {'retry', 'reaccept'} and type(value['retry']) is int and value['retry'] >= 0
    assert type(value['reaccept']) is bool and (value['retry'] > 0 or not value['reaccept'])
    return value


def inventory_shas():
    return (sha((HERE/'live-key-links.tsv').read_bytes()), sha((HERE/'live-key-manifests.tsv').read_bytes()))


def header(accepted, r):
    n = r['retry']
    root = '/var/tmp/ga-bebv-seq16-20260927' + ('-t%d' % n if n else '')
    return [
        ('"""ga-e0t1.18 sequence 15 adoption of Core fce2e9a0 (generated by make_s2.py from the executed sequence 14 file)."""',
         '"""ga-bebv sequence 16 adoption of Core 207a78e2 (generated by make_s2.py from the executed sequence 15 file)."""'),
        ("ROOT=Path('/var/tmp/ga-e0t1.18-seq15-20260926')", 'ROOT=Path(%r)' % root),
        ("ATTEMPT='ga-mutg-adoption-20260926-r16'", "ATTEMPT='ga-mutg-adoption-20260927-r%d'" % (17 + n)),
        ("ACCEPTED=Path('/var/tmp/ga-e0t1.18-predecessor-20260926-r1/second.json')", 'ACCEPTED=Path(%r)' % accepted['path']),
        ("ACCEPTED_SHA='b0a84b98100a9c691bf923ff24efcab80e0d1da8c88508484b3a39ec97a6b397'",
         'ACCEPTED_SHA=%r' % accepted['sha256']),
        ("ARTIFACT=Path('/var/tmp/ga-e0t1.18-build-20260926/gc-a')", "ARTIFACT=Path('/var/tmp/ga-bebv-build-20260927/gc-a')"),
        ("c.OLD='b2760ea407d8a5853fb7fbb3c184870ad4b6e9ccd763241a8ec59a8c3201d489'", 'c.OLD=%r' % OLD),
        ("c.NEW='fce2e9a0bea6c79f257e55b6424cf9271405d58f916a1017f3c14e232ad5d13b'", 'c.NEW=%r' % NEW),
        ('c.NEW_SIZE=134062284', 'c.NEW_SIZE=%d' % NEW_SIZE),
        ("            commit='deefb98b2aed07875df31351d081fbac195cb1cd',",
         "            commit='f45a626213dc5b8d0b52f097d978cca56e506df0',"),
        ("            tree='af5c3f045c1f50cd62c859f6dc58fa613e5f2f99',",
         "            tree='f1011adaf673937fbda1d254a53c8f0eadf17c5c',"),
        ("            blob='e6e9ac576162bcdbde8fc05ecbb1943f55f0ce41')",
         "            blob='2f4f844927bcbaa89123cd819fcc0b82f33c2eb1')"),
        ("m['sequence']==15", "m['sequence']==16"),
        ("receipt['sequence']==15", "receipt['sequence']==16"),
        ("receipt['before']==dict(sha256=c.OLD,size=134052980,", "receipt['before']==dict(sha256=c.OLD,size=%d," % OLD_SIZE),
        ("os.memfd_create('ga-e0t1.18-reviewed-envelope'", "os.memfd_create('ga-bebv-reviewed-envelope'"),
    ]


def overrides(r):
    links_sha, manifests_sha = inventory_shas()
    assert (links_sha, manifests_sha) == (LINKS_TSV_SHA, MANIFESTS_TSV_SHA), 'live-key inventory changed'
    n = r['retry']
    accept_root = '/var/tmp/ga-bebv-predecessor-20260927-r%d' % (1 + (n if r['reaccept'] else 0))
    return [
        ('# ga-e0t1.18 sequence 15: these blocks are rebound by ga-e0t1.18-deploy/make_s2.py; see its docstring.\n',
         '# ga-e0t1.18 sequence 15: these blocks are rebound by ga-e0t1.18-deploy/make_s2.py; see its docstring.\n'
         '# ga-bebv sequence 16: rebound again by ga-bebv-deploy/make_s2.py; see its docstring.\n'),
        ("S14_HERE=Path('/home/loucmane/gas-city-ops-worktrees/ga-e0t1-orchestrator-bootstrap/docs/ai/work-tracking/active/20260903-ga-e0t1-orchestrator-bootstrap-ACTIVE/designs/ga-e0t1.18-deploy')",
         "S14_HERE=Path('/home/loucmane/gas-city-ops-worktrees/ga-e0t1-orchestrator-bootstrap/docs/ai/work-tracking/active/20260903-ga-e0t1-orchestrator-bootstrap-ACTIVE/designs/ga-bebv-deploy')"),
        ("S14_M5_MANIFEST=dict(sha256='7f335ad83091a1a907b628fa5813c7daf6a530340a2ed404476797b5db90fefb',mode=0o644,uid=1000,gid=1000,size=127719)",
         "# sequence 16: the M9 pair (ga-e0t1.18 M9) replaces M6; the names keep the sequence 14 spelling.\n"
         "S14_M5_MANIFEST=dict(sha256='5a29dc596af192e0f314391453d25d6be548695a0defd64bdfc2fa76554e4993',mode=0o644,uid=1000,gid=1000,size=129653)"),
        ("S14_M5_RECEIPT=dict(sha256='123a01818b86f977ceabab1207c57795a3780261e39599019aa37f7609febaac',mode=0o644,uid=1000,gid=1000,size=2552)",
         "S14_M5_RECEIPT=dict(sha256='4c19802fc60f12695ec4080497b195278943185c4e8758f41feeac50e5b16092',mode=0o644,uid=1000,gid=1000,size=2549)"),
        ("S14_ACCEPT_ROOT=Path('/var/tmp/ga-e0t1.18-predecessor-20260926-r1')", 'S14_ACCEPT_ROOT=Path(%r)' % accept_root),
        ("S14_RECOVERY_ROOT=Path('/var/tmp/ga-e0t1.18-seq15-recovery-20260926')",
         "S14_RECOVERY_ROOT=Path('/var/tmp/ga-bebv-seq16-recovery-20260927')"),
    ]


def main():
    raw = SOURCE.read_bytes()
    assert sha(raw) == SOURCE_SHA, 'sequence 15 source drift'
    path = HERE/'accepted.json'
    accepted = (json.loads(path.read_text()) if path.exists()
                else {'path': '/nonexistent/accepted-pending.json', 'sha256': '0' * 64})
    assert set(accepted) == {'path', 'sha256'}, accepted
    text = raw.decode()
    r = retry()
    for old, new in header(accepted, r) + overrides(r):
        assert text.count(old) == 1, old[:90]
        text = text.replace(old, new)
    OUT.write_text(text)
    print(sha(text.encode()))


if __name__ == '__main__':
    main()
