"""Full native integrity read inside read-only mounts, paired with host proof.

gct-mbg6 r11 terminal observer: a rebind of the reviewed ga-y49e observe-platform-integrity-r2.py.
It verifies the terminal suspension lineage in the window root, admits the window's accepted
restoration (restored.json, bound by the window executor digest and restore-pass.json), and
bounds the cache clock from the window before.json. Generated by make_round2b.py.
"""
import json
import os
from pathlib import Path
import sys
import types

HERE=Path('/home/loucmane/gas-city-ops-worktrees/ga-e0t1-orchestrator-bootstrap/docs/ai/work-tracking/active/20260903-ga-e0t1-orchestrator-bootstrap-ACTIVE/designs/gct-e8ex-window')
ROOT=Path('/var/tmp/gct-mbg6-terminal-20260926-r2')
WINDOW=Path('/var/tmp/gct-mbg6-window-20260926-r2')
WINDOW_SHA='0400a9b1f744b205e66eb4744cc207dd388a7abf8e8fd12768e034c4e59a21e2'
BUILD=Path('/var/tmp/ga-bebv-platform-inspector-m10-20260927')
W_SHA='871fd176c6c1f3e9a65e5cccf1bab04895a7a042d820684265035f0f8f6b769d'
BINARY_SHA='e1bb4fc9ac4884b4ad96710b05006c1148349781e826976d3bfef868752beac8'
MANIFEST=Path('/home/loucmane/gascity/city/.gc/platform/install-manifest.json')
MANIFEST_SHA='2b902a83577acf71f9dd93a97d43d8478f7c4b291b0992e8ba5a5e44fe66f7f2'

def load_window():
    import hashlib
    path=HERE/'window-obs-r11.py';raw=path.read_bytes()
    if hashlib.sha256(raw).hexdigest()!=W_SHA:raise RuntimeError('observer source drift')
    w=types.ModuleType('frozen_window');w.__file__=str(path)
    exec(compile(raw,str(path),'exec'),w.__dict__)
    return w

def verify_preservation(r,before,after):
    w=r.w
    r.preservation(before,after,w.CITY_SHA[0],w.RECEIPT_SHA[0])
    accounting=r.p.compare(before['cache'],after['cache'],
        before['cache_access_clock'],after['cache_access_clock'])
    w.require(not accounting['deltas'],'read-only integrity changed cache atime')

def provider_pins(w,o):
    m=json.loads(w.read(MANIFEST,MANIFEST_SHA))
    providers=m['integrity']['providers']
    # M9 pinned the candidate wrapper as a second claude provider, keyed by path; M10 (file 2b902a83) keeps it.
    w.require([p['name'] for p in providers]==['claude-native','codex','claude','claude'],'provider inventory')
    w.require([p['path'] for p in providers[2:]]==['/home/loucmane/gas-city-template/bin/gct-claude-signing-worker',
        '/home/loucmane/gas-city-template/bin/gct-claude-candidate-worker']
        and providers[3]['sha256']=='e4442971fd3188208eaf22974aaaf55f949b8f51041775f041ecb00a66de92a3',
        'M9 provider pins')
    for p in providers:
        w.require(p['version_args']==['--version'],'only version probes')
        w.require(str(Path(p['path']).resolve(strict=True))==p['resolved_path'],'provider resolution')
        pin,_=o.read_file(p['resolved_path'])
        w.require(pin['sha256']==p['sha256'],'provider bytes drift before invocation')
        w.require(pin['metadata']['uid']==1000 and pin['metadata']['gid']==1000
            and pin['metadata']['mode']==0o755,'provider authority')

def main():
    r=load_window();w=r.w;w.require(globals().get('_SOURCE_SHA'),'bound entry')
    w.read(Path(__file__),_SOURCE_SHA)
    b,o,owned=w.load_support();w.pins()
    w.read(BUILD/'platform-inspect',BINARY_SHA)
    result=json.loads(w.read(BUILD/'build-result.json','ab96575ef37b03e514c3c098a292dac8d7183946f5221b091cfa9cdc97a8bc62'))
    w.require(result['binary_sha256']==BINARY_SHA and result['core_commit']=='f45a626213dc5b8d0b52f097d978cca56e506df0'
        and result['core_tree']=='f1011adaf673937fbda1d254a53c8f0eadf17c5c'
        and result['entrypoint_sha256']=='1f87b7b86afc322c385aed0dbc22491b511b6704f07bb5e9078f342aff7d0e3a',
        'build binding')
    provider_pins(w,o)
    if sys.argv[1:]==['inner']:
        w.ROOT=ROOT;w.mount_proof(None)
        os.execve(BUILD/'platform-inspect',[str(BUILD/'platform-inspect')],dict(b.ENV,BD_DISABLE_METRICS='1'))
    w.require(sys.argv[1:]==[],'unknown action')
    w.host(o);w.read(w.CITY/'city.toml',w.CITY_SHA[0]);w.read(w.RECEIPT,w.RECEIPT_SHA[0])
    # The terminal suspension lineage and the accepted restoration are in the window root.
    w.ROOT=WINDOW
    w.verified_lifecycle(terminal=True)
    w.require(w.record('restore-consumed.json')==dict(executor_sha256=WINDOW_SHA)
        and w.record('restore-pass.json')==dict(ok=True,full_platform_integrity_still_required=True),
        'accepted window restoration')
    accepted=w.record('restored.json');original=w.record('before.json')
    # The window layer adds route-regeneration keys; no reload happens after restore, and this layer
    # compares every other field.
    for key in ('generated_routes','generated_route_chain'):accepted.pop(key)
    ROOT.mkdir(mode=0o700);w.ROOT=ROOT
    w.save('intent.json',dict(executor_sha256=_SOURCE_SHA,binary_sha256=BINARY_SHA,
        version_probes_only=True,worker_launch=False))
    w.snapshot('observed-before.json',b,o)
    before=w.record('observed-before.json')
    verify_preservation(r,accepted,before)
    r.p.bounds(original['cache_access_clock'],before['cache_access_clock'])
    argv=['/usr/bin/bwrap','--ro-bind','/','/','--unshare-net','--unshare-pid',
        '--new-session','--die-with-parent','--proc','/proc','--dev','/dev','--',
        '/usr/bin/python3','-I','-S','-B',str(w.LAUNCH),__file__,_SOURCE_SHA,'inner']
    try:
        phase=w.phase('integrity',argv,b,owned,timeout=90)
        report=json.loads(phase['stdout'])
        w.require(report['schema']=='ga.platform-inspect-observation.v1' and report['ok'] is True
            and report['report']['Drifts'] in (None,[]),'integrity drift')
    except BaseException as exc:
        w.save('primary-failure.json',dict(error=str(exc),preservation_proven=False))
        raise
    finally:
        # Preserve the first failure above. Missing/uncertain terminal containment
        # stops here without treating a snapshot as successful containment.
        w.complete_containment()
        w.snapshot('observed-after.json',b,o)
        after=w.record('observed-after.json')
        verify_preservation(r,before,after)
        r.p.bounds(original['cache_access_clock'],after['cache_access_clock'])
        w.save('preservation.json',dict(window_preservation=True,cache_atime_deltas=0,
            runtime_child_metadata_policy='unchanged pinned R6',timestamp_writes=False))
    w.save('result.json',dict(ok=True,report=report,actual_host_verified=True,
        root_cache_protected_read_only=True,window_preservation=True,worker_launched=False,
        terminal_suspension_endpoint_bound=True,accepted_restoration_bound=True))
    print(json.dumps(dict(ok=True,worker_launched=False,full_native_integrity=True)))

if __name__=='__main__':main()
