"""One raw route of the already-bound task; all rigs remain suspended.

gct-mbg6 r11: a rebind of the reviewed ga-y49e route-task-r4.py over window-r11.py. The binding ran as
its own reviewed job, so its outputs are bound by provenance: the executor digest and brief digest
in binding-intent.json and the exact result. Generated by make_round2b.py.
"""
import hashlib
import json
import os
from pathlib import Path
import stat
import sys
import types

HERE=Path('/home/loucmane/gas-city-ops-worktrees/ga-e0t1-orchestrator-bootstrap/docs/ai/work-tracking/active/20260903-ga-e0t1-orchestrator-bootstrap-ACTIVE/designs/gct-e8ex-window')
ROOT=Path('/var/tmp/gct-mbg6-route-20260926-r1')
BIND=Path('/var/tmp/gct-mbg6-bind-20260926-r1')
BIND_SHA='d3c21b2701c9c71c78e13bdb26add05499f46333f4feb513e8728a85291aa22d'
DESCRIPTION_SHA='c66bab3c40693762c54c998efa8b5f8bab2813391ba15a9318a00b7b33f2ef0c'
PREROUTE=Path('/home/loucmane/gas-city-ops-worktrees/ga-e0t1-orchestrator-bootstrap/docs/ai/work-tracking/active/20260903-ga-e0t1-orchestrator-bootstrap-ACTIVE/designs/ga-6utp-activation-r10/preroute.py')
PREROUTE_SHA='d52e09214381fb6ce92becc2aed72fd1318821fd327ad3fb07e4974b57a3f4c6'
CANDIDATE_GIT=Path('/home/loucmane/gas-city-ops-worktrees/ga-e0t1-orchestrator-bootstrap/docs/ai/work-tracking/active/20260903-ga-e0t1-orchestrator-bootstrap-ACTIVE/designs/ga-6utp-activation-r10/candidate_git.py')
CANDIDATE_GIT_SHA='d2894e829618ad1fdcb5640b47b99baa3c783173acccb4f7f5918c958823bebe'
# s1 r8: the reviewed preroute.py record refresh after the sequence 16 controller restart (pid 2800348).
RECORD=Path('/home/loucmane/.local/share/gas-city-staging/ga-bebv-process-record-20260927/process-record.json')
RECORD_SHA='df765fd0e357925bab51891c72019018bb43b65fcd6e97addf0582c9bdf5e5d7'
HELPER=HERE/'window-r11.py'
SHA='32f106f254dd8a6663718bd2849971dd4737a2d1d66dc71f90ee1e829fbaa0cd'
TARGET='gas-city-template/codex'

def main():
    assert os.getuid()==os.geteuid()==1000 and globals().get('_SOURCE_SHA')
    assert hashlib.sha256(Path(__file__).read_bytes()).hexdigest()==_SOURCE_SHA
    raw=HELPER.read_bytes();assert hashlib.sha256(raw).hexdigest()==SHA
    m=types.ModuleType('route_window');m.__file__=str(HELPER)
    exec(compile(raw,str(HELPER),'exec',dont_inherit=True),m.__dict__)
    w=m.w;b,o,owned=w.load_support();w.pins()
    assert json.loads(w.read(w.ROOT/'stage-pass.json'))==dict(ok=True,worker_launched=False)
    s=BIND.lstat()
    assert stat.S_ISDIR(s.st_mode) and s.st_uid==1000 and stat.S_IMODE(s.st_mode)==0o700,'bind root authority'
    intent=json.loads(w.read(BIND/'binding-intent.json'))
    assert intent['executor_sha256']==BIND_SHA and intent['description_sha256']==DESCRIPTION_SHA
    assert intent['worker_launched'] is False
    result=json.loads(w.read(BIND/'result.json'))
    assert result==dict(ok=True,bead='gct-mbg6',contract_bound=True,routed=False,assigned=False,
        worker_launched=False,live_configuration_changed=False)
    bound=json.loads(w.read(BIND/'task-after.json'))
    assert bound['metadata']==intent['metadata']
    w.read(w.CITY/'city.toml',w.CITY_SHA[1]);w.read(w.RECEIPT,w.RECEIPT_SHA[1])
    ROOT.mkdir(mode=0o700);w.ROOT=ROOT
    def run(name,args):return w.phase(name,args,b,owned)
    def bead(name):
        v=json.loads(run(name,w.GC+['--rig','gas-city-template','bd','show','gct-mbg6','--json'])['stdout'])
        assert isinstance(v,list) and len(v)==1 and v[0]['id']=='gct-mbg6'
        return v[0]
    before_host=w.host(o)
    before=bead('task-before-read');w.save('task-before.json',before)
    assert before==bound and before['status']=='open' and not before.get('assignee')
    assert 'gc.routed_to' not in before['metadata']
    # gct-mbg6: the Template pre-route, built from the reviewed ga-6utp preroute pieces (preroute.check itself
    # requires a root holding only this worktree), is the last step before the sling. pr.survey is given the
    # worktree, not the shared Template root, whose other worktrees are not this window's.
    shown=run('preroute-bead',w.GC+['--rig','gas-city-template','bd','show','gct-mbg6','--json'])['stdout']
    bead_json=ROOT/'preroute-bead.json'
    fd=os.open(bead_json,os.O_WRONLY|os.O_CREAT|os.O_EXCL,0o600)
    with os.fdopen(fd,'w') as out:out.write(shown)
    raw=PREROUTE.read_bytes();assert hashlib.sha256(raw).hexdigest()==PREROUTE_SHA
    tools=CANDIDATE_GIT.read_bytes();assert hashlib.sha256(tools).hexdigest()==CANDIDATE_GIT_SHA
    cg=types.ModuleType('candidate_git');cg.__file__=str(CANDIDATE_GIT);sys.modules['candidate_git']=cg
    exec(compile(tools,str(CANDIDATE_GIT),'exec',dont_inherit=True),cg.__dict__)
    pr=types.ModuleType('preroute');pr.__file__=str(PREROUTE);sys.modules['preroute']=pr
    exec(compile(raw,str(PREROUTE),'exec',dont_inherit=True),pr.__dict__)
    # Template variant: the reviewed preroute.check requires the candidate root to hold exactly the worktree,
    # which a Template worktree root cannot. It calls the same reviewed pieces, in the same order.
    record=pr.load_record(RECORD,RECORD_SHA)
    slice_root=pr.user_slice(1000)
    city=pr.city_problems(slice_root,record)
    assert not city,('the city is not quiet',city)
    root=Path('/home/loucmane/gas-city-template-worktrees');common=Path('/home/loucmane/gas-city-template/.git');work=root/'gct-mbg6'
    admin=cg.verify_linked(root,common,work,'gct-mbg6')
    head=cg.git(admin,work,'rev-parse','--verify','HEAD^{commit}').decode().strip()
    assert head==w.BASE,('worktree HEAD',head)
    cg.no_gitlinks(admin,work,head)
    # Template variant of no_drivers: exactly the pre-existing git-lfs drivers, no repository attributes file,
    # and the one tracked .gitattributes (it selects no filter) at the reviewed blob.
    drivers=cg.git(admin,work,'config','--includes','--get-regexp',r'^(filter|diff|merge)\.',expected=(0,1))
    assert hashlib.sha256(drivers).hexdigest()=='a3cf4a1c62cb600373035123a48f183b55253d98337e4a430c8a483c49b7be70','Template driver config is not the git-lfs set'
    for extra in (admin/'info'/'attributes',admin.parent.parent/'info'/'attributes'):
        assert not os.path.lexists(extra),('repository attributes file present',str(extra))
    attrs=[p for p in cg.split_z(cg.git(admin,work,'ls-tree','-r','-z','--name-only','--full-tree',head))
        if p.rsplit('/',1)[-1]=='.gitattributes']
    assert attrs==['.gitattributes'],('tracked attributes files',attrs)
    assert cg.git(admin,work,'rev-parse','--verify',head+':.gitattributes').decode().strip()=='84c48ec45d32b997de49fa694d00b7e4ba3c677e'
    assert cg.git(admin,work,'status','--porcelain','--ignored','-z','--untracked-files=all')==b'','routed worktree is not freshly clean'
    problems=pr.survey(work,1000,slice_root,record['hidden'])
    assert not problems,('processes hold the worktree',problems)
    shown_bead=json.loads(shown);shown_bead=shown_bead[0] if isinstance(shown_bead,list) else shown_bead
    assert shown_bead.get('id')=='gct-mbg6','task id'
    assert (shown_bead.get('metadata') or {}).get('gc.work_dir')==str(work),'gc.work_dir'
    assert hashlib.sha256(str(shown_bead.get('description','')).encode()).hexdigest()==DESCRIPTION_SHA,'description'
    # gct-e8ex split r8/r9 reviews: the stop check reads the notes, so none may exist before the first session,
    # and the view must still fit the split's 9000-byte cap after BIND stamped its metadata.
    assert not shown_bead.get('notes') and not shown_bead.get('assignee'),'task has notes or an assignee before routing'
    assert len(shown.encode() if isinstance(shown,str) else shown)<9000,'task view over the split cap'
    checked=dict(ok=True,worktree=str(work),admin=str(admin),bead='gct-mbg6',base=head,controller=record['controller'],
        variant='template-root-pieces')
    w.save('preroute.json',checked)
    argv=w.GC+['--rig','gas-city-template','sling',TARGET,'gct-mbg6','--no-formula','--no-convoy','--json']
    preview=json.loads(run('route-preview',argv+['--dry-run'])['stdout'])
    assert preview['schema_version']=='1' and preview['success'] and preview['dry_run'] and not preview['routed']
    assert preview['bead_id']=='gct-mbg6' and preview['target']==TARGET
    assert bead('after-preview-read')==before
    assert w.host(o)==before_host
    w.save('route-intent.json',dict(before=before,argv=argv,executor_sha256=_SOURCE_SHA))
    result=json.loads(run('route',argv)['stdout'])
    assert result['schema_version']=='1' and result['success'] and result['routed'] and not result['dry_run']
    assert result['bead_id']=='gct-mbg6' and result['target']==TARGET
    assert not result.get('convoy_id') and not result.get('molecule_id')
    after=bead('task-after-read');w.save('task-after.json',after)
    assert after['metadata']==dict(before['metadata'],**{'gc.routed_to':TARGET})
    for key in set(before)|set(after):
        if key not in ('metadata','updated_at'):assert before.get(key)==after.get(key),key
    assert w.host(o)==before_host
    w.save('result.json',dict(ok=True,routed_once=True,rigs_suspended=True,worker_launched=False,
        fresh_full_queue_audit_required_before_resume=True))
    print(json.dumps(w.record('result.json')))

if __name__=='__main__':main()
