"""Full native integrity read inside read-only mounts, paired with host proof.

ga-nibd r11: a rebind of the reviewed ga-y49e observe-platform-integrity-r2.py for a FRESH window on the
M5 baseline. It admits the live state against the P6 accepted snapshot plus the reviewed dispositions,
through the base `before.json` snapshot check. No prior window lifecycle or restoration observation
exists, so those two historical comparisons are removed. Generated by make_round2a.py.
"""
import json
import os
from pathlib import Path
import sys
import types

HERE=Path('/home/loucmane/gas-city-ops-worktrees/ga-e0t1-orchestrator-bootstrap/docs/ai/work-tracking/active/20260903-ga-e0t1-orchestrator-bootstrap-ACTIVE/designs/ga-nibd-window')
ROOT=Path('/var/tmp/ga-nibd-integrity-20260925-r5')
BUILD=Path('/var/tmp/ga-4z38-platform-inspector-20260924-r1')
W_SHA='2cc725f6bd932c4d2cc3a58c8c768f81532073c3a815dd1e5712ab15594158d7'
BINARY_SHA='b8ebcde38a9ee8078752949226f6736ea14a25413fba73db4d95076261658d13'
MANIFEST=Path('/home/loucmane/gascity/city/.gc/platform/install-manifest.json')
RECOVER_ROOT='/var/tmp/ga-gegx-recover-20260925-r3'
RECOVER_SHA='b6ad8162b8eec1a26a07b63a3e6f0238e1dad116533b31ed0e7cf494b641c02e'
MANIFEST_SHA='2d7eadce62c4e567697813cc9122414f1e94c3bd9d389aef92015adef7f36319'

def load_window():
    import hashlib
    path=HERE/'window-obs-r11.py';raw=path.read_bytes()
    if hashlib.sha256(raw).hexdigest()!=W_SHA:raise RuntimeError('observer source drift')
    w=types.ModuleType('frozen_window');w.__file__=str(path)
    exec(compile(raw,str(path),'exec'),w.__dict__)
    return w

def verify_preservation(r,before,after):
    w=r.w
    r.preservation(before,after,w.CITY_SHA[0],w.RECEIPT_SHA[0])
    accounting=r.p.compare(before['cache'],after['cache'],
        before['cache_access_clock'],after['cache_access_clock'])
    w.require(not accounting['deltas'],'read-only integrity changed cache atime')

def provider_pins(w,o):
    m=json.loads(w.read(MANIFEST,MANIFEST_SHA))
    providers=m['integrity']['providers']
    w.require([p['name'] for p in providers]==['claude-native','codex','claude'],'provider inventory')
    for p in providers:
        w.require(p['version_args']==['--version'],'only version probes')
        w.require(str(Path(p['path']).resolve(strict=True))==p['resolved_path'],'provider resolution')
        pin,_=o.read_file(p['resolved_path'])
        w.require(pin['sha256']==p['sha256'],'provider bytes drift before invocation')
        w.require(pin['metadata']['uid']==1000 and pin['metadata']['gid']==1000
            and pin['metadata']['mode']==0o755,'provider authority')

def main():
    r=load_window();w=r.w;w.require(globals().get('_SOURCE_SHA'),'bound entry')
    w.read(Path(__file__),_SOURCE_SHA)
    # s6: admit the city.toml the recovery job restored (window-base approved_recovery_image).
    w.RECOVERY=(RECOVER_ROOT,RECOVER_SHA)
    b,o,owned=w.load_support();w.pins()
    w.read(BUILD/'platform-inspect',BINARY_SHA)
    result=json.loads(w.read(BUILD/'build-result.json','39bfcea56f8932623d6b60ffe745de9f7029e76ba01fdd0d7da90c2fc402eaf9'))
    w.require(result['binary_sha256']==BINARY_SHA and result['core_commit']=='796d9a7a67c42294fdc467c107bb59b76e482301'
        and result['core_tree']=='f2c120a5ac9ea25ebc395c1b3cfa4eb30dcafd13'
        and result['entrypoint_sha256']=='e5e9872f2b57d70c9fbde8e3d152978eaf9266453af67dbd1a82a4d1886b7ca3',
        'build binding')
    provider_pins(w,o)
    if sys.argv[1:]==['inner']:
        w.ROOT=ROOT;w.mount_proof(None)
        os.execve(BUILD/'platform-inspect',[str(BUILD/'platform-inspect')],dict(b.ENV,BD_DISABLE_METRICS='1'))
    w.require(sys.argv[1:]==[],'unknown action')
    w.host(o);w.read(w.CITY/'city.toml',w.CITY_SHA[0]);w.read(w.RECEIPT,w.RECEIPT_SHA[0])
    # Fresh window: no prior lifecycle chain exists to verify. The suspension state is pinned in the
    # snapshot below and admitted against the recorded TERMINAL entry (approved_restore_image).
    ROOT.mkdir(mode=0o700);w.ROOT=ROOT
    w.save('intent.json',dict(executor_sha256=_SOURCE_SHA,binary_sha256=BINARY_SHA,
        version_probes_only=True,worker_launch=False))
    # The base snapshot named before.json admits the live state against the P6 accepted snapshot
    # with the reviewed dispositions approved_historical_image, approved_epoch_image,
    # approved_restore_image, approved_coordinator_cache_image and (with RECOVERY set above)
    # approved_recovery_image, and the accepted provider pins.
    w.snapshot('before.json',b,o)
    before=w.record('before.json')
    argv=['/usr/bin/bwrap','--ro-bind','/','/','--unshare-net','--unshare-pid',
        '--new-session','--die-with-parent','--proc','/proc','--dev','/dev','--',
        '/usr/bin/python3','-I','-S','-B',str(w.LAUNCH),__file__,_SOURCE_SHA,'inner']
    try:
        phase=w.phase('integrity',argv,b,owned,timeout=90)
        report=json.loads(phase['stdout'])
        w.require(report['schema']=='ga.platform-inspect-observation.v1' and report['ok'] is True
            and report['report']['Drifts'] in (None,[]),'integrity drift')
    except BaseException as exc:
        w.save('primary-failure.json',dict(error=str(exc),preservation_proven=False))
        raise
    finally:
        # Preserve the first failure above. Missing/uncertain terminal containment
        # stops here without treating a snapshot as successful containment.
        w.complete_containment()
        w.snapshot('observed-after.json',b,o)
        after=w.record('observed-after.json')
        verify_preservation(r,before,after)
        w.save('preservation.json',dict(window_preservation=True,cache_atime_deltas=0,
            runtime_child_metadata_policy='unchanged pinned R6',timestamp_writes=False))
    w.save('result.json',dict(ok=True,report=report,actual_host_verified=True,
        root_cache_protected_read_only=True,window_preservation=True,worker_launched=False,
        admitted_against_p6_with_disposition=True))
    print(json.dumps(dict(ok=True,worker_launched=False,full_native_integrity=True)))

if __name__=='__main__':main()
