"""P8 step 1: observe the running revision and derive the receipt input. Read-only except its own records.

ga-e0t1.18 S3 part 2. Generated by make_p8.py from the executed P7 input (9b711394); the logic is P7's.
The native cycle trace is read (`gc trace show`, a supported read). The live signing worker's `--version`
proves the dependency version it will report. The installed receipt 7cf59ab9 minus its three generated
fields becomes the input draft. Exactly one field changes, from its exact predecessor:

- member_heads[core]: 9faeabc2 -> deefb98b, the sequence 15 build source (Core PR 48).
The Template cfd353f3, the permission revision 2113693e (the traced running revision must equal it: no
embedded pack path changed), the provider version d4e57767 and the argv model claude-opus-5-5 are asserted
unchanged.

`m7_acceptance()` verifies M7's own reviewed records at run time: a COMMIT_PASS review record with two
distinct provenance files, the committed acceptance it binds, restoration, the M7 release manifest naming
Template cfd353f3 and succeeding the M6 file 7f335ad8, and the live metadata pair byte-identical to the
accepted pair.

  python3 -I -S -B source-launch.py p8-input.py <own sha256>
"""
from datetime import datetime, timezone
import copy
import hashlib
import json
import os
from pathlib import Path
import stat
import subprocess
import sys
import types

HERE = Path(__file__).parent
ROOT = Path('/var/tmp/ga-e0t1.18-p8-input-20260926')
CITY = Path('/home/loucmane/gascity/city')
RECEIPT = CITY/'.gc/runtime/provisioning/receipt.json'
WORKER = Path('/home/loucmane/gas-city-template/bin/gct-claude-signing-worker')
OBS = Path('/home/loucmane/gas-city-ops-worktrees/ga-e0t1-orchestrator-bootstrap/docs/ai/work-tracking/active/'
           '20260903-ga-e0t1-orchestrator-bootstrap-ACTIVE/reports/ga-e0t1.14-rollout-r1/package-r4/resume-r4b/'
           'recovery-source-r2/observe_recovery.py')
OBS_SHA = 'f5357d222f0a2f7ceb9e1a830533f20a4868fe5f3beb247de335843b730bdd78'
GC_SHA = 'fce2e9a0bea6c79f257e55b6424cf9271405d58f916a1017f3c14e232ad5d13b'
CORE = 'deefb98b2aed07875df31351d081fbac195cb1cd'
RECEIPT_OLD_SHA = '7cf59ab9e5a43fd7bca97028e7faaa2b2f9bfb927a663b4588c66e846e4e425d'
TEMPLATE = 'cfd353f30f465cdf67bbd41fab48812fe5b9617e'
REVISION = '2113693eefd3a9c905554a294e36ab3b5a17bc63004280b7144ff069ef75acc2'
VERSION = 'gct-claude-signing-worker 1 dependencies_sha256=d4e57767d03accd708ce8876580096bb17bce023d6dc6e664fffee4367ea3c57'
MODEL = 'claude-opus-5-5'
CORE_OLD = '9faeabc2892d8c7133111e13ad55af66790a2ac6'
M7 = Path('/home/loucmane/gas-city-ops-worktrees/ga-e0t1-orchestrator-bootstrap/reports/m7/q')
M7_RELEASE = 'template-pr71-core-seq15-metadata-m7-20260926'
M7_AUTHORITY = ('template-pr71-authority', '/home/loucmane/gas-city-template-worktrees/ga-e0t1-15-pr71-authority',
                TEMPLATE)
# The succession link is previous_metadata.manifest_sha256, the M6 canonical FILE digest. The top-level
# previous_sha256 is the previous Core binary (gc b2760ea4) and is not a manifest link.
PREVIOUS_MANIFEST_FILE = '7f335ad83091a1a907b628fa5813c7daf6a530340a2ed404476797b5db90fefb'
GENERATED = ('canary_runner', 'receipt_sha256')
ENV = dict(HOME='/home/loucmane', USER='loucmane', LOGNAME='loucmane',
           PATH='/home/loucmane/gascity/bin:/usr/local/bin:/usr/bin:/bin', XDG_RUNTIME_DIR='/run/user/1000',
           DBUS_SESSION_BUS_ADDRESS='unix:path=/run/user/1000/bus', GC_HOME='/home/loucmane/gascity/home',
           GIT_OPTIONAL_LOCKS='0', LC_ALL='C.UTF-8', PYTHONDONTWRITEBYTECODE='1', DO_NOT_TRACK='1')


def require(ok, reason):
    if not ok:
        raise RuntimeError(reason)


def read(path, expected=None):
    fd = os.open(path, os.O_RDONLY | os.O_NOFOLLOW | os.O_NOATIME | os.O_CLOEXEC)
    try:
        before = os.fstat(fd)
        require(stat.S_ISREG(before.st_mode) and before.st_uid == 1000 and before.st_nlink == 1,
                'file authority: ' + str(path))
        chunks = []
        while chunk := os.read(fd, 1048576):
            chunks.append(chunk)
        raw = b''.join(chunks)
        require(before == os.fstat(fd) and len(raw) == before.st_size, 'file changed during read: ' + str(path))
    finally:
        os.close(fd)
    require(expected is None or hashlib.sha256(raw).hexdigest() == expected, 'digest drift: ' + str(path))
    return raw


def write(name, value):
    raw = value if isinstance(value, bytes) else (json.dumps(value, indent=2, sort_keys=True) + '\n').encode()
    fd = os.open(ROOT/name, os.O_WRONLY | os.O_CREAT | os.O_EXCL | os.O_NOFOLLOW | os.O_CLOEXEC, 0o600)
    with os.fdopen(fd, 'wb') as stream:
        stream.write(raw); stream.flush(); os.fsync(stream.fileno())
    return hashlib.sha256(raw).hexdigest()


def observer():
    raw = read(OBS, OBS_SHA)
    value = types.ModuleType('observe_recovery'); value.__file__ = str(OBS)
    exec(compile(raw, str(OBS), 'exec', dont_inherit=True), value.__dict__)
    value.GC_SHA = GC_SHA
    return value


def serialize(draft):
    return (json.dumps(draft, indent=2, sort_keys=True) + '\n').encode()


def derive(receipt, revision):
    """Pure: the receipt input for the M7 state, with every predecessor asserted."""
    draft = copy.deepcopy(receipt)
    for key in GENERATED:
        require(key in draft, 'generated field missing: ' + key)
        draft.pop(key)
    require(len(draft['profiles']) == 1, 'profile cardinality')
    profile = draft['profiles'][0]
    require('worker_profile_sha256' in profile, 'generated profile digest missing')
    profile.pop('worker_profile_sha256')
    require(draft['template_commit'] == TEMPLATE, 'template unchanged')
    heads = [h for h in draft['member_heads'] if h['name'] == 'template']
    require(len(heads) == 1 and heads[0]['commit'] == TEMPLATE, 'template member head unchanged')
    # Sequence 15 changed no embedded pack path, so the composed revision must be unchanged.
    require(draft['permission_revision'] == REVISION and revision == REVISION, 'revision unchanged')
    require(profile['provider']['version'] == VERSION, 'provider version unchanged')
    argv = profile['argv']
    positions = [i for i, token in enumerate(argv) if token == '--model']
    require(len(positions) == 1 and argv[positions[0] + 1] == MODEL, 'argv model unchanged')
    cores = [h for h in draft['member_heads'] if h['name'] == 'core']
    require(len(cores) == 1 and cores[0]['commit'] == CORE_OLD, 'core member head predecessor')
    cores[0]['commit'] = CORE
    return draft


def proven_draft(root=None):
    """For later P8 steps: the recorded draft must be exactly derive() of the preserved
    old receipt and the recorded revision. Independent of the live receipt."""
    root = ROOT if root is None else root
    result = json.loads(read(root/'result.json'))
    require(result['ok'] is True and result['receipt_before_sha256'] == RECEIPT_OLD_SHA, 'input result')
    revision = json.loads(read(root/'revision.json', result['revision_sha256']))
    require(revision['config_revision'] == result['permission_revision'], 'input revision record')
    receipt = json.loads(read(root/'receipt.before.json', RECEIPT_OLD_SHA))
    raw = read(root/'receipt.input.draft.json', result['draft_sha256'])
    require(raw == serialize(derive(receipt, revision['config_revision'])), 'draft is not the reviewed derivation')
    return dict(path=root/'receipt.input.draft.json', raw=raw, sha256=result['draft_sha256'],
                revision=revision['config_revision'], m7=result['m7'])


def m7_acceptance():
    """The M7 committed pair, proven only from M7 reviewed records and the live files."""
    record = json.loads(read(M7/'commit-pass.json'))
    require(set(record) == {'verdict', 'bindings', 'reviewers'} and record['verdict'] == 'COMMIT_PASS'
            and set(record['bindings']) == {'package_sha256', 'acceptance_sha256'}, 'M7 commit review record')
    people = record['reviewers']
    require(len(people) == 2 and len({p['reviewer_id'] for p in people}) == 2, 'two distinct M7 commit reviews')
    seen = set()
    for person in people:
        require(set(person) == {'reviewer_id', 'provenance_path', 'provenance_sha256'}, 'M7 review provenance')
        raw = read(Path(person['provenance_path']), person['provenance_sha256'])
        info = os.stat(person['provenance_path'], follow_symlinks=False)
        proof = json.loads(raw)
        require(set(proof) == {'reviewer_id', 'verdict', 'bindings', 'assessment'}
                and proof['reviewer_id'] == person['reviewer_id'] and proof['verdict'] == 'COMMIT_PASS'
                and proof['bindings'] == record['bindings'] and isinstance(proof['assessment'], str)
                and proof['assessment'].strip(), 'M7 review content')
        seen |= {('path', person['provenance_path']), ('sha', person['provenance_sha256']),
                 ('inode', info.st_dev, info.st_ino)}
    require(len(seen) == 6, 'duplicate M7 review provenance')
    package = record['bindings']['package_sha256']
    acceptance = json.loads(read(M7/'committed-acceptance.json', record['bindings']['acceptance_sha256']))
    require(acceptance['ok'] is True and acceptance['lease_expired'] is True
            and acceptance['package_sha256'] == package, 'M7 acceptance')
    restored = json.loads(read(M7/'restored.json'))
    require(restored['ok'] is True and restored['accepted'] is True, 'M7 restoration')
    manifest = json.loads(read(M7/'manifest.json'))
    last = manifest['integrity']['repositories'][-1]
    require(manifest['release_id'] == M7_RELEASE
            and manifest['previous_metadata']['manifest_sha256'] == PREVIOUS_MANIFEST_FILE
            and manifest['manifest_sha256'] == acceptance['manifest_sha256']
            and (last['name'], last['path'], last['commit']) == M7_AUTHORITY, 'M7 release binding')
    read(CITY/'.gc/platform/install-manifest.json', acceptance['canonical_file_sha256'])
    read(CITY/'.gc/platform/install-receipt.json', acceptance['receipt_file_sha256'])
    return dict(package_sha256=package, acceptance_path=str(M7/'committed-acceptance.json'),
                acceptance_sha256=record['bindings']['acceptance_sha256'],
                manifest_sha256=acceptance['manifest_sha256'], receipt_sha256=acceptance['receipt_sha256'],
                canonical_file_sha256=acceptance['canonical_file_sha256'],
                receipt_file_sha256=acceptance['receipt_file_sha256'])


def latest_cycle(records, pid):
    require(records, 'no controller cycle in the trace window')
    latest = max(records, key=lambda item: item['seq'])
    require(latest['controller_pid'] == pid and latest['gc_commit'] == CORE
            and latest['completion_status'] == 'completed', 'live controller cycle drift')
    age = (datetime.now(timezone.utc) - datetime.fromisoformat(latest['ts'].replace('Z', '+00:00'))).total_seconds()
    require(0 <= age <= 120 and latest['fields']['active_template_count'] == 0, 'stale or active controller cycle')
    return latest


def main():
    require(globals().get('_SOURCE_SHA') and read(Path(__file__), _SOURCE_SHA), 'source-bound entry required')
    require(len(sys.argv) == 1, 'no arguments')
    require(not os.path.lexists(ROOT), 'input root consumed')
    m7 = m7_acceptance()
    receipt_raw = read(RECEIPT, RECEIPT_OLD_SHA)
    receipt = json.loads(receipt_raw)
    o = observer()
    host = o.host_observation()
    version = subprocess.run([str(WORKER), '--version'], env=ENV, cwd='/', stdin=subprocess.DEVNULL,
                             capture_output=True, text=True, timeout=60, check=False)
    require(version.returncode == 0 and version.stdout.strip() == VERSION, 'live worker dependency version')
    trace = subprocess.run(['/home/loucmane/gascity/bin/gc', '--city', str(CITY), 'trace', 'show', '--type',
                            'cycle_result', '--since', '2m', '--json'], env=ENV, cwd='/',
                           stdin=subprocess.DEVNULL, capture_output=True, text=True, timeout=30, check=False)
    require(trace.returncode == 0, 'trace read refused')
    latest = latest_cycle(json.loads(trace.stdout)['records'], host['host']['pid'])
    draft = derive(receipt, latest['config_revision'])
    require(o.host_observation() == host and m7_acceptance() == m7, 'host or M7 pair changed during observation')
    ROOT.mkdir(mode=0o700)
    require(write('receipt.before.json', receipt_raw) == RECEIPT_OLD_SHA, 'receipt copy')
    draft_sha = write('receipt.input.draft.json', serialize(draft))
    revision_sha = write('revision.json', latest)
    result = dict(ok=True, draft_sha256=draft_sha, revision_sha256=revision_sha,
                  permission_revision=latest['config_revision'], worker_version=version.stdout.strip(),
                  receipt_before_sha256=RECEIPT_OLD_SHA, m7=m7, host=host, receipt_installed=False,
                  worker_launched=False)
    print(json.dumps(dict(result_sha256=write('result.json', result), draft_sha256=draft_sha,
                          permission_revision=latest['config_revision'])))


if __name__ == '__main__':
    main()
