"""One raw route of the already-bound task; all rigs remain suspended.

ga-3oa7 r11: a rebind of the reviewed ga-y49e route-task-r4.py over window-r11.py. The binding ran as
its own reviewed job, so its outputs are bound by provenance: the executor digest and brief digest
in binding-intent.json and the exact result. Generated by make_round2b.py.
"""
import hashlib
import json
import os
from pathlib import Path
import stat
import sys
import types

HERE=Path('/home/loucmane/gas-city-ops-worktrees/ga-e0t1-orchestrator-bootstrap/docs/ai/work-tracking/active/20260903-ga-e0t1-orchestrator-bootstrap-ACTIVE/designs/ga-3oa7-window')
ROOT=Path('/var/tmp/ga-3oa7-route-20260926-r1')
BIND=Path('/var/tmp/ga-3oa7-bind-20260926-r1')
BIND_SHA='6ddfa89a182282c1fa642039141c59f59fe116201869ef8398a4ae22fab4923c'
DESCRIPTION_SHA='9d6b2e1a1cd9a34fd6d9a05c5ab643fd6a324b62af31dd0bae8f545bf67fb935'
PREROUTE=Path('/home/loucmane/gas-city-ops-worktrees/ga-e0t1-orchestrator-bootstrap/docs/ai/work-tracking/active/20260903-ga-e0t1-orchestrator-bootstrap-ACTIVE/designs/ga-6utp-activation-r10/preroute.py')
PREROUTE_SHA='d52e09214381fb6ce92becc2aed72fd1318821fd327ad3fb07e4974b57a3f4c6'
CANDIDATE_GIT=Path('/home/loucmane/gas-city-ops-worktrees/ga-e0t1-orchestrator-bootstrap/docs/ai/work-tracking/active/20260903-ga-e0t1-orchestrator-bootstrap-ACTIVE/designs/ga-6utp-activation-r10/candidate_git.py')
CANDIDATE_GIT_SHA='d2894e829618ad1fdcb5640b47b99baa3c783173acccb4f7f5918c958823bebe'
RECORD=Path('/home/loucmane/.local/share/gas-city-staging/ga-6utp-activation-r12-20260926/records/process-record.json')
RECORD_SHA='a6aa4b4c3a33dd08ee46b27c7059201cc529eab1d99eb67af9ab05acc195a278'
HELPER=HERE/'window-r11.py'
SHA='16390af81b84e0cc9495e3691d093383f98f43fb7eef01c21dbb133d7bd18ae7'
TARGET='gascity/operations-candidate-worker'

def main():
    assert os.getuid()==os.geteuid()==1000 and globals().get('_SOURCE_SHA')
    assert hashlib.sha256(Path(__file__).read_bytes()).hexdigest()==_SOURCE_SHA
    raw=HELPER.read_bytes();assert hashlib.sha256(raw).hexdigest()==SHA
    m=types.ModuleType('route_window');m.__file__=str(HELPER)
    exec(compile(raw,str(HELPER),'exec',dont_inherit=True),m.__dict__)
    w=m.w;b,o,owned=w.load_support();w.pins()
    assert json.loads(w.read(w.ROOT/'stage-pass.json'))==dict(ok=True,worker_launched=False)
    s=BIND.lstat()
    assert stat.S_ISDIR(s.st_mode) and s.st_uid==1000 and stat.S_IMODE(s.st_mode)==0o700,'bind root authority'
    intent=json.loads(w.read(BIND/'binding-intent.json'))
    assert intent['executor_sha256']==BIND_SHA and intent['description_sha256']==DESCRIPTION_SHA
    assert intent['worker_launched'] is False
    result=json.loads(w.read(BIND/'result.json'))
    assert result==dict(ok=True,bead='ga-3oa7',contract_bound=True,routed=False,assigned=False,
        worker_launched=False,live_configuration_changed=False)
    bound=json.loads(w.read(BIND/'task-after.json'))
    assert bound['metadata']==intent['metadata']
    w.read(w.CITY/'city.toml',w.CITY_SHA[1]);w.read(w.RECEIPT,w.RECEIPT_SHA[1])
    ROOT.mkdir(mode=0o700);w.ROOT=ROOT
    def run(name,args):return w.phase(name,args,b,owned)
    def bead(name):
        v=json.loads(run(name,w.GC+['--rig','gascity','bd','show','ga-3oa7','--json'])['stdout'])
        assert isinstance(v,list) and len(v)==1 and v[0]['id']=='ga-3oa7'
        return v[0]
    before_host=w.host(o)
    before=bead('task-before-read');w.save('task-before.json',before)
    assert before==bound and before['status']=='open' and not before.get('assignee')
    assert 'gc.routed_to' not in before['metadata']
    # ga-3oa7: the reviewed pre-route check (ga-6utp preroute.check) is the last step before the sling.
    shown=run('preroute-bead',w.GC+['--rig','gascity','bd','show','ga-3oa7','--json'])['stdout']
    bead_json=ROOT/'preroute-bead.json'
    fd=os.open(bead_json,os.O_WRONLY|os.O_CREAT|os.O_EXCL,0o600)
    with os.fdopen(fd,'w') as out:out.write(shown)
    raw=PREROUTE.read_bytes();assert hashlib.sha256(raw).hexdigest()==PREROUTE_SHA
    tools=CANDIDATE_GIT.read_bytes();assert hashlib.sha256(tools).hexdigest()==CANDIDATE_GIT_SHA
    cg=types.ModuleType('candidate_git');cg.__file__=str(CANDIDATE_GIT);sys.modules['candidate_git']=cg
    exec(compile(tools,str(CANDIDATE_GIT),'exec',dont_inherit=True),cg.__dict__)
    pr=types.ModuleType('preroute');pr.__file__=str(PREROUTE);sys.modules['preroute']=pr
    exec(compile(raw,str(PREROUTE),'exec',dont_inherit=True),pr.__dict__)
    checked=pr.check(Path('/home/loucmane/gas-city-ops-candidate-worktrees'),Path('/home/loucmane/gas-city-ops/.git'),'ga-3oa7',bead_json,1000,
        pr.load_record(RECORD,RECORD_SHA),w.BASE,DESCRIPTION_SHA)
    assert checked['ok'] is True and checked['worktree']=='/home/loucmane/gas-city-ops-candidate-worktrees/ga-3oa7'
    w.save('preroute.json',checked)
    argv=w.GC+['--rig','gascity','sling',TARGET,'ga-3oa7','--no-formula','--no-convoy','--json']
    preview=json.loads(run('route-preview',argv+['--dry-run'])['stdout'])
    assert preview['schema_version']=='1' and preview['success'] and preview['dry_run'] and not preview['routed']
    assert preview['bead_id']=='ga-3oa7' and preview['target']==TARGET
    assert bead('after-preview-read')==before
    assert w.host(o)==before_host
    w.save('route-intent.json',dict(before=before,argv=argv,executor_sha256=_SOURCE_SHA))
    result=json.loads(run('route',argv)['stdout'])
    assert result['schema_version']=='1' and result['success'] and result['routed'] and not result['dry_run']
    assert result['bead_id']=='ga-3oa7' and result['target']==TARGET
    assert not result.get('convoy_id') and not result.get('molecule_id')
    after=bead('task-after-read');w.save('task-after.json',after)
    assert after['metadata']==dict(before['metadata'],**{'gc.routed_to':TARGET})
    for key in set(before)|set(after):
        if key not in ('metadata','updated_at'):assert before.get(key)==after.get(key),key
    assert w.host(o)==before_host
    w.save('result.json',dict(ok=True,routed_once=True,rigs_suspended=True,worker_launched=False,
        fresh_full_queue_audit_required_before_resume=True))
    print(json.dumps(w.record('result.json')))

if __name__=='__main__':main()
