"""Generate s2_transition.py (broker sequence 14) from the reviewed sequence 13 successor.

Source: staging ga-mutg-custody-adoption-20260920/capture_transition.py, sha 0a87790a. Every change is:
- one of the exact, count-checked SUBSTITUTIONS below; or
- the OVERRIDES block, inserted verbatim before the final `if __name__` line.
Reviewers diff s2_transition.py against the source. test_s2.py proves that the generated file
equals this generator's output.

The accepted predecessor is bound by accepted.json: {"path", "sha256"} from observe_predecessor.py,
after its independent review. Until accepted.json exists, the generator refuses.
"""
import hashlib
import json
from pathlib import Path

HERE = Path(__file__).parent
SOURCE = Path('/home/loucmane/.local/share/gas-city-staging/ga-mutg-20260920/'
              'ga-mutg-custody-adoption-20260920/capture_transition.py')
SOURCE_SHA = '0a87790a659ed86a7c8e2ef1dbbe42754238443e856857886b3cc139c8ae120d'
OUT = HERE / 's2_transition.py'
# An optional first argument redirects the output, so test_s2.py never rewrites the tracked file.
if __name__ == '__main__':
    import sys as _sys
    if len(_sys.argv) == 2:
        OUT = Path(_sys.argv[1])

OLD = '69d00186c098b84efe6658c03d888ce07f6d6528d6c446671b53d92f7bde89f9'
OLD_SIZE = 134048098
NEW = 'b2760ea407d8a5853fb7fbb3c184870ad4b6e9ccd763241a8ec59a8c3201d489'
NEW_SIZE = 134052980


def retry():
    """Pre-submit retry support (review B r4 question 3).

    Optional retry.json {"retry": N, "reaccept": bool}. N > 0 gives a fresh ROOT
    (…-20260925-tN) and attempt r(14+N). reaccept=true also gives a fresh accept root (-r(2+N)).
    Only retry after a terminal in accept (always with reaccept, since accept's root is one-shot),
    prepare, bind-envelope or recheck. After a reaccept: run accept into the new root, review it,
    rewrite accepted.json and regenerate again. A submit-phase terminal counts
    as post-submit unless the receipts directory lacks the request and the broker epoch is unchanged.
    """
    path = HERE / 'retry.json'
    value = json.loads(path.read_text()) if path.exists() else {'retry': 0, 'reaccept': False}
    assert set(value) == {'retry', 'reaccept'} and type(value['retry']) is int and value['retry'] >= 0
    assert type(value['reaccept']) is bool and (value['retry'] > 0 or not value['reaccept'])
    return value


def substitutions(accepted, r):
    n = r['retry']
    root = '/var/tmp/ga-e0t1.15-seq14-20260925' + (f'-t{n}' if n else '')
    return [
        ('"""Fresh seq13 custody-compatible rebuild adoption; only Core changes epoch."""',
         '"""ga-e0t1.15 sequence 14 adoption of Core b2760ea4 (generated by make_s2.py from the seq13 successor)."""'),
        ("ROOT=Path('/tmp/ga-mutg-custody-adoption-20260920')",
         f"ROOT=Path({root!r})"),
        ("ATTEMPT='ga-mutg-adoption-20260920-r8'", f"ATTEMPT='ga-mutg-adoption-20260925-r{14 + n}'"),
        ("ACCEPTED=Path('/tmp/ga-mutg-adoption-20260920-r7/second.json')",
         f"ACCEPTED=Path({accepted['path']!r})"),
        ("ACCEPTED_SHA='29c339b5ca9c4d6bcaf95dc306e55455877cfa0535851083d0d6cc1b1d212563'",
         f"ACCEPTED_SHA={accepted['sha256']!r}"),
        ("ARTIFACT=Path('/var/tmp/ga-mutg-custody-build-20260920/gc-a')",
         "ARTIFACT=Path('/var/tmp/ga-e0t1.15-build-20260925/gc-a')"),
        ("c.OLD='83d098fc6e48b912f2658955bb4180f3433ddb2a0961c40af904eb21023a0f78'", f"c.OLD={OLD!r}"),
        ("c.NEW='69d00186c098b84efe6658c03d888ce07f6d6528d6c446671b53d92f7bde89f9'", f"c.NEW={NEW!r}"),
        ("c.NEW_SIZE=134048098", f"c.NEW_SIZE={NEW_SIZE}"),
        ("            commit='796d9a7a67c42294fdc467c107bb59b76e482301',",
         "            commit='9faeabc2892d8c7133111e13ad55af66790a2ac6',"),
        ("            tree='f2c120a5ac9ea25ebc395c1b3cfa4eb30dcafd13',",
         "            tree='c9f19d215d271a5dda0bce296dc72c32dfc35499',"),
        ("            blob='ebda6377ceac585d0cbdd17a810ff8fe7d89905c')",
         "            blob='db752a382a3c28336d4ddaa370d9d9e58d1c604a')"),
        ("m['sequence']==13", "m['sequence']==14"),
        ("receipt['sequence']==13", "receipt['sequence']==14"),
        ("receipt['before']==dict(sha256=c.OLD,size=134048105,",
         f"receipt['before']==dict(sha256=c.OLD,size={OLD_SIZE},"),
        ("os.memfd_create('ga-mutg-reviewed-envelope'", "os.memfd_create('ga-e0t1.15-reviewed-envelope'"),
    ]


def main():
    raw = SOURCE.read_bytes()
    assert hashlib.sha256(raw).hexdigest() == SOURCE_SHA, 'seq13 source drift'
    path = HERE / 'accepted.json'
    # Before the accept phase has run, the placeholder only permits the 'accept' phase, which never
    # reads ACCEPTED; every later phase refuses on its digest.
    accepted = (json.loads(path.read_text()) if path.exists()
                else {'path': '/nonexistent/accepted-pending.json', 'sha256': '0' * 64})
    assert set(accepted) == {'path', 'sha256'}, accepted
    text = raw.decode()
    r = retry()
    for old, new in substitutions(accepted, r):
        assert text.count(old) == 1, old
        text = text.replace(old, new)
    tail = "if __name__=='__main__':main()\n"
    assert text.endswith(tail) and text.count(tail) == 1
    overrides = (HERE / 's2_overrides.py.txt').read_text()
    if r['reaccept']:
        old = "S14_ACCEPT_ROOT=Path('/var/tmp/ga-e0t1.15-predecessor-20260925-r2')"
        assert overrides.count(old) == 1
        overrides = overrides.replace(old, f"S14_ACCEPT_ROOT=Path('/var/tmp/ga-e0t1.15-predecessor-20260925-r{2 + r['retry']}')")
    text = text[:-len(tail)] + overrides + '\n' + tail
    OUT.write_text(text)
    print(hashlib.sha256(text.encode()).hexdigest())


if __name__ == '__main__':
    main()
