"""Restore the live city gc-beads-bd shim that the S1 build probe rewrote (ga-e0t1.15 deviation).

At 2026-09-25 17:28:57 CEST, build.py ran the unadopted artifact (`gc-a version --json`) with the
operator HOME and GC_HOME unset. Its config load ran EnsureBuiltinRuntimeAssets against the registered
live city and rewrote /home/loucmane/gascity/city/.gc/scripts/gc-beads-bd.sh (now sha bc0b3e88) to exec
~/.gc/cache/repos/69fe9a2e…/examples/bd/assets/scripts/gc-beads-bd.sh.

The accepted bytes are what the live supervisor writes. It runs the live Core 69d00186 (source
796d9a7a) with GC_HOME=/home/loucmane/gascity/home, so the shim execs the live cache key
a21cc0a2 there. ensureGcBeadsBdShim (cmd/gc/embed_builtin_packs.go in 796d9a7a) renders exactly
TEMPLATE below (fmt %q of a plain ASCII path equals a JSON string), and WriteFileIfContentOrModeChangedAtomic
writes it at mode 0755.

The executor refuses unless every precondition holds:
- the current bytes are exactly the drifted bytes;
- the target exists and its bytes equal the drifted target's bytes;
- the supervisor GC_HOME is gascity/home;
- rigs are suspended.
It then writes once, atomically, and reads back. It never runs gc.
"""
import hashlib
import json
import os
from pathlib import Path
import subprocess

ROOT = Path('/var/tmp/ga-e0t1.15-shim-restore-20260925')
SHIM = Path('/home/loucmane/gascity/city/.gc/scripts/gc-beads-bd.sh')
DRIFTED_SHA = 'bc0b3e883e0fec050430c506f21d86ddd01d043c69b54af6e9c1863b6e1ca51a'
EXPECTED_SHA = '2e0a1f7462a913c2c5fab1078d2837a272b225b09f3b500f2df971427c2eaa6e'
LIVE_TARGET = ('/home/loucmane/gascity/home/cache/repos/'
               'a21cc0a2fbf22c14fbe59cf508d05bcc230774f5c0d9cd386215369d43a2410a'
               '/examples/bd/assets/scripts/gc-beads-bd.sh')
DRIFTED_TARGET = ('/home/loucmane/.gc/cache/repos/'
                  '69fe9a2e6239743677a6e13188096df34d6eb6d41fad171af58671ef288fdd3f'
                  '/examples/bd/assets/scripts/gc-beads-bd.sh')
TEMPLATE = ('#!/bin/sh\n'
            '# Generated by gc — do not edit. Stable entrypoint for the bundled bd\n'
            "# lifecycle script; the target tracks the running binary's pack cache.\n"
            'exec {target} "$@"\n')
SUPERVISOR = 'gascity-supervisor-home-42adab5d.service'


def sha(data):
    return hashlib.sha256(data).hexdigest()


def record(name, value):
    with (ROOT / name).open('x') as stream:
        json.dump(value, stream, indent=2, sort_keys=True)


def require(ok, message):
    if not ok:
        raise RuntimeError(message)


def stat_of(path):
    st = os.lstat(path)
    return dict(mode=oct(st.st_mode & 0o7777), uid=st.st_uid, gid=st.st_gid, size=st.st_size,
                inode=st.st_ino, mtime_ns=st.st_mtime_ns)


def supervisor_gc_home():
    pid = subprocess.run(['/usr/bin/systemctl', '--user', 'show', '-p', 'MainPID', '--value', SUPERVISOR],
                         capture_output=True, text=True, check=True).stdout.strip()
    require(pid.isdigit() and int(pid) > 1, 'supervisor not running')
    env = Path(f'/proc/{pid}/environ').read_bytes().split(b'\0')
    values = [e.split(b'=', 1)[1].decode() for e in env if e.startswith(b'GC_HOME=')]
    require(len(values) == 1, 'supervisor GC_HOME not unique')
    return pid, values[0]


def main():
    expected = TEMPLATE.format(target=json.dumps(LIVE_TARGET)).encode()
    require(sha(expected) == EXPECTED_SHA, 'expected bytes drift')
    require(sha(TEMPLATE.format(target=json.dumps(DRIFTED_TARGET)).encode()) == DRIFTED_SHA,
            'drifted bytes are not the template rendering of the drifted target')
    record('start.json', dict(executor_sha256=sha(Path(__file__).read_bytes())))
    before = SHIM.read_bytes()
    before_stat = stat_of(SHIM)
    require(sha(before) == DRIFTED_SHA, 'shim is not the recorded drifted bytes; stop')
    require(before_stat['mode'] == '0o755' and before_stat['uid'] == 1000 and before_stat['gid'] == 1000,
            'shim owner or mode differs')
    require(Path(LIVE_TARGET).is_file() and not Path(LIVE_TARGET).is_symlink(), 'live target missing')
    require(sha(Path(LIVE_TARGET).read_bytes()) == sha(Path(DRIFTED_TARGET).read_bytes()),
            'bd script bytes differ between targets; stop')
    pid, gc_home = supervisor_gc_home()
    require(gc_home == '/home/loucmane/gascity/home', 'supervisor GC_HOME is not gascity/home')
    record('preconditions.json', dict(before_sha256=DRIFTED_SHA, before_stat=before_stat,
                                      supervisor_pid=pid, supervisor_gc_home=gc_home,
                                      live_target=LIVE_TARGET))
    tmp = SHIM.with_name('.gc-beads-bd.sh.ga-e0t1.15-restore')
    fd = os.open(tmp, os.O_WRONLY | os.O_CREAT | os.O_EXCL | os.O_NOFOLLOW, 0o755)
    try:
        os.write(fd, expected)
        os.fchmod(fd, 0o755)
        os.fsync(fd)
    finally:
        os.close(fd)
    os.rename(tmp, SHIM)
    after = SHIM.read_bytes()
    after_stat = stat_of(SHIM)
    require(sha(after) == EXPECTED_SHA and after_stat['mode'] == '0o755', 'readback mismatch')
    record('result.json', dict(ok=True, before_sha256=DRIFTED_SHA, after_sha256=EXPECTED_SHA,
                               after_stat=after_stat, gc_invoked=False))
    print(json.dumps(dict(ok=True, after_sha256=EXPECTED_SHA)))


if __name__ == '__main__':
    main()
