"""Full native integrity read inside read-only mounts, paired with host proof.

ga-qcwl r11: a rebind of the reviewed ga-y49e observe-platform-integrity-r2.py for a FRESH window on the
post-S3 baseline (M6). It admits the live state against the P7 adoption snapshot (ga-e0t1.15 S4),
through the base `before.json` snapshot check. No prior window lifecycle or restoration observation
exists, so those two historical comparisons are removed. Generated by make_round2a.py.
"""
import json
import os
from pathlib import Path
import sys
import types

HERE=Path('/home/loucmane/gas-city-ops-worktrees/ga-e0t1-orchestrator-bootstrap/docs/ai/work-tracking/active/20260903-ga-e0t1-orchestrator-bootstrap-ACTIVE/designs/ga-qcwl-window')
ROOT=Path('/var/tmp/ga-qcwl-integrity-20260925-r5')
BUILD=Path('/var/tmp/ga-e0t1.15-platform-inspector-20260925')
W_SHA='e8ff8bdcd5612b3e7297be84c1ae9f496ee69cef85a2010d9623ff0b6c48fd0c'
BINARY_SHA='334cc3c912858d84582cf980cf7f270ebb6e5250ac3a62dbdf4e720dc0a2564f'
MANIFEST=Path('/home/loucmane/gascity/city/.gc/platform/install-manifest.json')
MANIFEST_SHA='7f335ad83091a1a907b628fa5813c7daf6a530340a2ed404476797b5db90fefb'

def load_window():
    import hashlib
    path=HERE/'window-obs-r11.py';raw=path.read_bytes()
    if hashlib.sha256(raw).hexdigest()!=W_SHA:raise RuntimeError('observer source drift')
    w=types.ModuleType('frozen_window');w.__file__=str(path)
    exec(compile(raw,str(path),'exec'),w.__dict__)
    return w

def verify_preservation(r,before,after):
    w=r.w
    r.preservation(before,after,w.CITY_SHA[0],w.RECEIPT_SHA[0])
    accounting=r.p.compare(before['cache'],after['cache'],
        before['cache_access_clock'],after['cache_access_clock'])
    w.require(not accounting['deltas'],'read-only integrity changed cache atime')

def provider_pins(w,o):
    m=json.loads(w.read(MANIFEST,MANIFEST_SHA))
    providers=m['integrity']['providers']
    w.require([p['name'] for p in providers]==['claude-native','codex','claude'],'provider inventory')
    for p in providers:
        w.require(p['version_args']==['--version'],'only version probes')
        w.require(str(Path(p['path']).resolve(strict=True))==p['resolved_path'],'provider resolution')
        pin,_=o.read_file(p['resolved_path'])
        w.require(pin['sha256']==p['sha256'],'provider bytes drift before invocation')
        w.require(pin['metadata']['uid']==1000 and pin['metadata']['gid']==1000
            and pin['metadata']['mode']==0o755,'provider authority')

def main():
    r=load_window();w=r.w;w.require(globals().get('_SOURCE_SHA'),'bound entry')
    w.read(Path(__file__),_SOURCE_SHA)
    # S4: no recovery admission; the accepted image is the P7 snapshot (window-base).
    b,o,owned=w.load_support();w.pins()
    w.read(BUILD/'platform-inspect',BINARY_SHA)
    result=json.loads(w.read(BUILD/'build-result.json','145a48417718adf62cf607e74424147884b6247f44ff7f33dfa8971767ec1dc4'))
    w.require(result['binary_sha256']==BINARY_SHA and result['core_commit']=='9faeabc2892d8c7133111e13ad55af66790a2ac6'
        and result['core_tree']=='c9f19d215d271a5dda0bce296dc72c32dfc35499'
        and result['entrypoint_sha256']=='585e0d376d90a26cab57d6e676d4aa3567df53b4c8b10816e8fac8071901a7f7',
        'build binding')
    provider_pins(w,o)
    if sys.argv[1:]==['inner']:
        w.ROOT=ROOT;w.mount_proof(None)
        os.execve(BUILD/'platform-inspect',[str(BUILD/'platform-inspect')],dict(b.ENV,BD_DISABLE_METRICS='1'))
    w.require(sys.argv[1:]==[],'unknown action')
    w.host(o);w.read(w.CITY/'city.toml',w.CITY_SHA[0]);w.read(w.RECEIPT,w.RECEIPT_SHA[0])
    # Fresh window: no prior lifecycle chain exists to verify. The suspension state is pinned in the
    # snapshot below and compared exactly with the P7 adoption snapshot.
    ROOT.mkdir(mode=0o700);w.ROOT=ROOT
    w.save('intent.json',dict(executor_sha256=_SOURCE_SHA,binary_sha256=BINARY_SHA,
        version_probes_only=True,worker_launch=False))
    # The base snapshot named before.json admits the live state against the P7 adoption snapshot
    # (two LIVE_PASS readbacks) and its provider pins; no P6-era disposition applies.
    w.snapshot('before.json',b,o)
    before=w.record('before.json')
    argv=['/usr/bin/bwrap','--ro-bind','/','/','--unshare-net','--unshare-pid',
        '--new-session','--die-with-parent','--proc','/proc','--dev','/dev','--',
        '/usr/bin/python3','-I','-S','-B',str(w.LAUNCH),__file__,_SOURCE_SHA,'inner']
    try:
        phase=w.phase('integrity',argv,b,owned,timeout=90)
        report=json.loads(phase['stdout'])
        w.require(report['schema']=='ga.platform-inspect-observation.v1' and report['ok'] is True
            and report['report']['Drifts'] in (None,[]),'integrity drift')
    except BaseException as exc:
        w.save('primary-failure.json',dict(error=str(exc),preservation_proven=False))
        raise
    finally:
        # Preserve the first failure above. Missing/uncertain terminal containment
        # stops here without treating a snapshot as successful containment.
        w.complete_containment()
        w.snapshot('observed-after.json',b,o)
        after=w.record('observed-after.json')
        verify_preservation(r,before,after)
        w.save('preservation.json',dict(window_preservation=True,cache_atime_deltas=0,
            runtime_child_metadata_policy='unchanged pinned R6',timestamp_writes=False))
    w.save('result.json',dict(ok=True,report=report,actual_host_verified=True,
        root_cache_protected_read_only=True,window_preservation=True,worker_launched=False,
        admitted_against_p7_snapshot=True))
    print(json.dumps(dict(ok=True,worker_launched=False,full_native_integrity=True)))

if __name__=='__main__':main()
