"""Read-only admission to the existing reviewed R10 restore; never restore here.

ga-f37t r11: a rebind of the R10 restore-admission-r1.py to window-r11.py. It runs after CONTAIN and
the session close, and RESTORE.sh requires its pass record, so RESTORE is consumed only after this
full preservation check passed. Generated by make_round2b.py.
"""
import hashlib
import json
import os
from pathlib import Path
import types

HERE = Path('/home/loucmane/gas-city-ops-worktrees/ga-e0t1-orchestrator-bootstrap/docs/ai/work-tracking/active/20260903-ga-e0t1-orchestrator-bootstrap-ACTIVE/designs/ga-f37t-window')
SOURCE = HERE / 'window-r11.py'
SHA = 'e0790d39eb2c8b9ca9f3463bc3591c825cc237e1376132e6d387fb787de4d836'

def main():
    assert os.getuid() == os.geteuid() == 1000
    raw = SOURCE.read_bytes()
    assert hashlib.sha256(raw).hexdigest() == SHA
    m = types.ModuleType('window'); m.__file__ = str(SOURCE)
    exec(compile(raw, str(SOURCE), 'exec', dont_inherit=True), m.__dict__)
    w = m.w
    b, o, owned = w.load_support()
    assert not (w.ROOT / 'restore-consumed.json').exists()
    assert not (w.ROOT / 'restore-admission.json').exists()
    w.complete_containment()
    w.verified_lifecycle(terminal=True)
    w.host(o)
    w.read(w.CITY / 'city.toml', w.CITY_SHA[1])
    w.read(w.RECEIPT, w.RECEIPT_SHA[1])
    w.snapshot('restore-admission.json', b, o)
    w.preservation(w.record('before.json'), w.record('restore-admission.json'),
                   w.CITY_SHA[1], w.RECEIPT_SHA[1])
    w.complete_containment()
    w.save('restore-admission-pass.json', dict(ok=True, read_only=True,
        restore_executed=False, full_residue_proof_separately_required=True))
    print(json.dumps(w.record('restore-admission-pass.json')))

if __name__ == '__main__':
    main()
