"""Bounded city/receipt window staging and exact restoration; never starts work.

ga-f37t r11: a rebind of the reviewed ga-y49e base window-state-r6-read-safe.py (b10a3810) onto the
M5 baseline and task ga-f37t. Generated by make_window_base_r11.py with asserted replacements only.
"""
from datetime import datetime, timezone
import hashlib
import json
import os
from pathlib import Path
import re
import select
import stat
import subprocess
import sys
import time
import types

HERE = Path('/home/loucmane/gas-city-ops-worktrees/ga-e0t1-orchestrator-bootstrap/docs/ai/work-tracking/active/20260903-ga-e0t1-orchestrator-bootstrap-ACTIVE/designs/ga-f37t-window')
ROOT = Path('/var/tmp/ga-f37t-window-20260923-r1')
PREP = Path('/var/tmp/ga-f37t-prep-20260923-r2')
SUSPENSION = '/home/loucmane/gascity/city/.gc/runtime/suspension-state.json'
LINEAGE_SHA = '4b0d4c5bb713dc4ac802efc5c45f126d026c83fb5ea03fcb5f40d0c680cacbf0'
SUPPORT = Path('/home/loucmane/gas-city-ops-worktrees/ga-e0t1-orchestrator-bootstrap/docs/ai/work-tracking/active/20260903-ga-e0t1-orchestrator-bootstrap-ACTIVE/designs/gct-m1wh-p6')
LAUNCH = SUPPORT/'source-launch.py'
CITY = Path('/home/loucmane/gascity/city')
RECEIPT = CITY/'.gc/runtime/provisioning/receipt.json'
WORK = Path('/home/loucmane/gascity-core-worktrees/ga-f37t-typed-route-cycles')
BASE = 'e6366b9ececd3a4ceab2bcaa264a5e317e6eab88'
GC = ['/home/loucmane/gascity/bin/gc', '--city', str(CITY)]
PROVISIONER = Path('/home/loucmane/gas-city-template/bin/gct-managed-worker-provision')
WITNESS = Path('/var/tmp/gct-m1wh-p6-adoption-20260923-r2/typed-support.json')
WITNESS_SHA = '5a630443b7b47c0054b96f593b18d3012ac671d4124c25eae3afa54bcfe8cfeb'
CITY_SHA = ('4f7e170fc0503841576c0bb26c33ee5d0aab4e796821f3b1cd874ecef733c591',
            '9774a5692ec5537713b212bc3fef5c88edc34c82cb6fdcc11e949e7eefc8343e')
RECEIPT_SHA = ('0b30c23f4484382fd4918f394599268f4f4005ac71118e8a7f82ca72eb9615ff',
               '0876abb88879ce546502e34228a710a60a69a2b20f85791b3c9ce9f0ebce2451')
REVISION = ('d6ca85cd96c7aab4ea0b6a7954d2d74e5e6bb211cde0bb820f3b6f815023bd88',
            '758aa29b154babfe18468c6e2f650e04c23be18f9ba0c4a2bb4ccb087553d87f')
INPUT = (Path('/var/tmp/gct-m1wh-p6-input-20260923-r2/receipt.input.draft.json'), PREP/'receipt.input.json')
INPUT_SHA = ('24c1ca751303d5cab12a1605599d13cb5e5a152c977088fbb6869c7a052095ec',
             None)  # The isolated input is compared to the exact native-finalized wire below.
RUNNER = Path('/var/tmp/ga-ecwh-preflight-diagnostic-20260920-r1/phase_runner.py')
ACCEPTED = Path('/var/tmp/gct-m1wh-p6-adoption-20260923-r2/after.json')
ACCEPTED_SHA = '1c025ef9ef31d75f7becb6e6ed1fd426f3d318eb53913cf8e24888f163900b70'
PROVIDER_SHA = 'a5f7f8c11a95b48d01f910c5c4668828d61a587a5942545f27d403ebadfeac8f'
CACHE_DIRECTORY = '954ed14987da288bfb98feee4cdab5043a44de1a8a9cf47afaaa0ce6e438fd5f/.git'

def require(ok, message):
    if not ok:
        raise RuntimeError(message)

def digest(raw):
    return hashlib.sha256(raw).hexdigest()

def read(path, pin=None):
    path = Path(path)
    require(path.resolve(strict=True) == path, 'path alias: '+str(path))
    fd = os.open(path, os.O_RDONLY|os.O_NOFOLLOW|os.O_NOATIME|os.O_CLOEXEC)
    try:
        s = os.fstat(fd)
        require(stat.S_ISREG(s.st_mode) and s.st_uid == 1000 and s.st_nlink == 1,
                'file authority: '+str(path))
        chunks = []
        while block := os.read(fd, 1048576):
            chunks.append(block)
        raw = b''.join(chunks)
        require(s == os.fstat(fd) and len(raw) == s.st_size, 'file read drift')
    finally:
        os.close(fd)
    require(pin is None or digest(raw) == pin, 'digest: '+str(path))
    return raw

def module(path, pin):
    raw = read(path, pin)
    m = types.ModuleType(Path(path).stem)
    m.__file__ = str(path)
    sys.modules[m.__name__] = m
    exec(compile(raw, str(path), 'exec', dont_inherit=True), m.__dict__)
    return m

def durable(path, raw, mode=0o600):
    fd = os.open(path, os.O_WRONLY|os.O_CREAT|os.O_EXCL|os.O_CLOEXEC, mode)
    with os.fdopen(fd, 'wb') as f:
        os.fchmod(f.fileno(), mode)
        s = os.fstat(f.fileno())
        require(stat.S_IMODE(s.st_mode) == mode and s.st_uid == s.st_gid == 1000
                and s.st_nlink == 1, 'new file authority')
        f.write(raw); f.flush(); os.fsync(f.fileno())
    d = os.open(Path(path).parent, os.O_RDONLY|os.O_DIRECTORY)
    try:
        os.fsync(d)
    finally:
        os.close(d)

def save(name, value):
    durable(ROOT/name, (json.dumps(value, sort_keys=True, indent=2)+'\n').encode())

def record(name):
    return json.loads(read(ROOT/name))

def load_support():
    b = module(SUPPORT/'p6-observe-compose.py', '43b94ce677dcaa80b6937f7205362063da151f0608a99874b18b692ab8f2c8d6')
    o = b.observe_module()
    o.ENV = dict(o.ENV, BD_DISABLE_METRICS='1')
    owned = module(RUNNER, 'eddf5e1174a7b275abe280e91ea5c8ea0762600d38524ba9631f53fb4874cdf3')
    return b, o, owned

def pins():
    # The R9-era diagnostic pins are not evidence for this window; its evidence is the prep root.
    read(PREP/'result.json', '0c071f7c97706059792bdec16ce3de952bf9114159ba493b5baad62d71e5d6d1')
    read(LAUNCH, '31bdeea83152c5ad0253a74d743f4d4d103dc7e14e7975da00055df6786d6dea')
    read(PROVISIONER, '64425a728fc06a082865f2d53afcc6e4793974f5aadab49492d95f5e0a9f4a35')
    read(WITNESS, WITNESS_SHA)
    read(PREP/'city.baseline.toml', CITY_SHA[0])
    read(PREP/'city.isolated.toml', CITY_SHA[1])
    read(PREP/'receipt.final.json', RECEIPT_SHA[1])
    read(INPUT[0], INPUT_SHA[0])
    p = module(PROVISIONER, '64425a728fc06a082865f2d53afcc6e4793974f5aadab49492d95f5e0a9f4a35')
    runner_path = RECEIPT.parent/'bin/gct-managed-worker-canary'
    runner_sha = '3beeedb2e5ce0723e5f745a05f1e2fdfa3ec27bee468284860e587e63c63e2e2'
    read(runner_path, runner_sha)
    for i in (0, 1):
        normalized = p.load_prototype(INPUT[i], dict(path=str(runner_path), sha256=runner_sha))
        require(digest(p.canonical_json(normalized)) == RECEIPT_SHA[i], 'receipt normalization drift')
        for profile in normalized['profiles']:
            argv = profile['argv']
            require(argv.count('--model') == 1 and argv[argv.index('--model')+1] == 'claude-opus-5-5', 'Opus-only selection')
    return p

def provider_pins(b, o):
    sha = '7b28b3e551e86818a2cdda3e53ed90c7072781e0a9354bd1ebf5d9425d579133'
    r = module(SUPPORT/'p6-readiness.py', sha)
    r._SOURCE_SHA = sha
    r.pin_inputs(b)
    return dict(worker=o.read_file(str(r.WORKER_NATIVE))[0],
        api_package=r.native_package_pair(b), subscription=o.read_file(str(r.SUBSCRIPTION))[0],
        provisioner=o.read_file(str(r.PROVISIONER))[0], runner=o.read_file(str(r.RUNNER))[0],
        api_link=dict(target=os.readlink(r.NATIVE_LINK),metadata=o.metadata(r.NATIVE_LINK.lstat())))

def dependency_image(value):
    # Historical reuse alone excludes read timestamps. Immediate preservation
    # still compares every metadata field, including atime.
    if isinstance(value, dict):
        return {k:dependency_image(v) for k,v in value.items() if k != 'atime_ns'}
    if isinstance(value, list):
        return [dependency_image(v) for v in value]
    return value

def approved_historical_image(prior):
    # ga-4z38 disposition, for independent review: between the P6 accepted snapshot (12:36Z) and
    # this window, coordinator `gc bd` calls made WITHOUT GIT_OPTIONAL_LOCKS=0 advanced only the pack
    # cache repo's .git directory times. The last such call was the 15:51:43Z read test that proved
    # the cause; every coordinator gc call since carries GIT_OPTIONAL_LOCKS=0. A read-only lstat
    # forecast found no other cache, pin or protected-tree change. Never write these values to disk
    # or reuse this exception for fresh drift.
    value=json.loads(json.dumps(prior))
    entry=value['cache']['inventory'][CACHE_DIRECTORY]
    for key in ('mtime_ns','ctime_ns'):
        require(entry[key] == 1790165454882697018, 'historical exception preimage')
        entry[key] = 1790178703592685769
    return value

def shape(value):
    if isinstance(value, dict):
        return {k: shape(v) for k, v in value.items()}
    return type(value).__name__

def approved_epoch_image(prior, h):
    # ga-4z38 r13 disposition, for independent review: the host rebooted on 2026-09-24 after the P6
    # accepted snapshot, so the P6 host block records the old boot. host() has already required the
    # live epoch (boot, and the core, signer and broker service epochs) to equal the rebound pins. The
    # P6 host block is replaced by that verified live block only when both have exactly the same shape.
    # Pins, cache and protected trees stay compared exactly as before. Never reuse this for fresh drift.
    value=json.loads(json.dumps(prior))
    require(shape(value['host']) == shape(h), 'host block shape drift')
    value['host']=h
    return value

RESTORED_PINS = {
    '/home/loucmane/gascity/city/city.toml': 'same-content',
    '/home/loucmane/gascity/city/.gc/runtime/provisioning/receipt.json': 'same-content',
    '/home/loucmane/gascity/city/.gc/runtime/suspension-state.json':
        'a4bcfdc35d60960fe22dfd3b58b6af8f37f09dcd444167c23779157ae3a31056'}

def approved_restore_image(prior):
    # ga-f37t s3 disposition, for independent review: the ga-4z38 window restored the city exactly
    # (RESTORE 2026-09-24 21:53:20Z, TERMINAL 21:54:18Z). RESTORE rewrote city.toml and receipt.json with
    # their accepted content, so only their inode and times changed, and TERMINAL wrote a new
    # suspension-state.json. The P6 image therefore cannot match any restored city. These three pin
    # entries, and only these, are taken from the reviewed TERMINAL record (pinned by digest); the two
    # rewritten files must keep exactly their accepted content digest, and the suspension state must be the
    # one TERMINAL recorded. Every other pin, the cache, the protected trees and the host stay compared as
    # before. Never reuse this for fresh drift.
    record = json.loads(read(Path('/var/tmp/ga-4z38-terminal-20260923-r1/observed-after.json'), '04ad8d3e2c3b32b43b93142190a0013ffc9f068381c63fd05a6526a975d2aa53'))
    value = json.loads(json.dumps(prior))
    require(set(RESTORED_PINS) <= set(value['pins']) and set(RESTORED_PINS) <= set(record['pins']),
            'restore disposition pin set')
    for path, rule in RESTORED_PINS.items():
        after = record['pins'][path]
        if rule == 'same-content':
            require(after['sha256'] == value['pins'][path]['sha256'], 'restored content differs: ' + path)
        else:
            require(after['sha256'] == rule, 'restored suspension state differs')
        require(shape(after) == shape(value['pins'][path]), 'restore pin shape drift')
        value['pins'][path] = after
    return value

def directories(o):
    fd = os.open(CITY, os.O_RDONLY|os.O_DIRECTORY|os.O_NOFOLLOW|os.O_NOATIME)
    try:
        names = sorted(os.listdir(fd))
        city = {'.':o.metadata(os.fstat(fd))}
        for name in names:
            s = os.stat(name, dir_fd=fd, follow_symlinks=False)
            require(not stat.S_ISLNK(s.st_mode), 'city child symlink: '+name)
            city[name] = o.metadata(s)
        require(names == sorted(os.listdir(fd)), 'city entries changed during observation')
    finally:
        os.close(fd)
    provision = o.tree_snapshot(RECEIPT.parent, protected=True)['inventory']
    require(set(provision) == {'.','receipt.json','bin','bin/gct-managed-worker-canary'},
            'unexpected provisioning entry')
    runtime_children={}
    for name in ('.gc','.beads'):
        fd=os.open(CITY/name,os.O_RDONLY|os.O_DIRECTORY|os.O_NOFOLLOW|os.O_NOATIME)
        try:
            names=sorted(os.listdir(fd))
            runtime_children[name]={child:o.metadata(os.stat(child,dir_fd=fd,follow_symlinks=False)) for child in names}
            require(names==sorted(os.listdir(fd)),'runtime children changed during observation')
        finally:os.close(fd)
    return dict(city=city, provision=provision, runtime_children=runtime_children)

def directory_preservation(before, after):
    a=json.loads(json.dumps(before)); z=json.loads(json.dumps(after))
    # Runtime children legitimately receive writes. Bind names and identity,
    # retaining full metadata in evidence; root metadata remains exact below.
    x=a.pop('runtime_children');y=z.pop('runtime_children')
    require(set(x)==set(y)=={'.gc','.beads'},'runtime inventory roots')
    for name in x:
        require(set(x[name])==set(y[name]),'runtime direct-child change')
        for child in x[name]:
            for key in ('device','inode','type','uid','gid','mode'):
                require(x[name][child][key]==y[name][child][key],'runtime child identity/authority drift')
    for section, target in [('city','city.toml'),('provision','receipt.json')]:
        require(set(a[section]) == set(z[section]), 'writable directory entry drift')
        a[section].pop(target); z[section].pop(target)
        # Atomic rename changes the parent directory's time only.
        for key in ('mtime_ns','ctime_ns'):
            a[section]['.'].pop(key); z[section]['.'].pop(key)
    require(a == z, 'unrelated writable directory authority drift')

def host(o):
    h = o.host_observation()
    require(h['host']['boot'] == '3f1f4534-ea17-4cb4-b2f2-a3f8bce1a8fa', 'boot drift')
    for name, pid, start in [('core','2331','39708112'), ('signer','2310','39660502'), ('broker','0','0')]:
        require(h[name]['MainPID'] == pid and h[name]['ExecMainStartTimestampMonotonic'] == start, name+' epoch drift')
    return h

def snapshot(name, b, o):
    prior = json.loads(read(ACCEPTED, ACCEPTED_SHA))
    h = host(o)
    files = {path: o.read_file(path)[0] for path in prior['pins']}
    value = dict(host=h, pins=files, cache=o.tree_snapshot(b.CACHE, cache=True),
                 protected={str(p): o.tree_snapshot(p, protected=True) for p in b.PROTECTED})
    require(h == host(o), 'host changed during snapshot')
    if name == 'before.json':
        if dependency_image(approved_restore_image(approved_epoch_image(approved_historical_image(prior), h))) != dependency_image(value):
            save('before-refused-observation.json',value)
            raise RuntimeError('accepted baseline drift')
    value['providers'] = provider_pins(b,o)
    accepted_provider=json.loads(read(Path(str(ACCEPTED)+'.provider-pins'),PROVIDER_SHA))
    require(dependency_image(value['providers']) == dependency_image(accepted_provider), 'accepted provider drift')
    value['directories'] = directories(o)
    save(name, value)

def preservation(before, after, city_pin, receipt_pin):
    a = json.loads(json.dumps(before)); z = json.loads(json.dumps(after))
    if list(ROOT.glob('suspension-*-intent.json')):
        endpoint = verified_lifecycle(terminal=True)
        require(a['pins'][SUSPENSION] == record('suspension-baseline.json')['pin'], 'suspension original binding')
        require(z['pins'][SUSPENSION] == endpoint, 'suspension final binding')
        a['pins'][SUSPENSION] = endpoint
    directory_preservation(a.pop('directories'),z.pop('directories'))
    for path, expected, mode in [(str(CITY/'city.toml'),city_pin,0o644), (str(RECEIPT),receipt_pin,0o600)]:
        first = a['pins'].pop(path); current = z['pins'].pop(path)
        require(current['sha256'] == expected, 'postimage '+path)
        for key in ('uid','gid','mode','type','nlink'):
            require(first['metadata'][key] == current['metadata'][key], 'authority changed '+path)
        require(current['metadata']['mode'] == mode, 'postimage mode')
    require(a == z, 'unrelated snapshot drift')

def suspension_record(o):
    pin,raw = o.read_file(SUSPENSION,collect=True)
    return dict(pin=pin,raw=raw.decode('utf-8'))

def lifecycle_records(s):
    intents={p.name[len('suspension-'):-len('-intent.json')] for p in ROOT.glob('suspension-*-intent.json')}
    events={p.name[len('suspension-'):-len('-event.json')] for p in ROOT.glob('suspension-*-event.json')}
    require(intents == events and intents <= set(s.ACTIONS), 'incomplete/unreviewed suspension transition')
    records=[]
    for action in s.ACTIONS:
        if action not in events:continue
        e=record('suspension-'+action+'-event.json')
        intent=record('suspension-'+action+'-intent.json')
        require(intent == dict(action=action,before=e['before'],before_sha256=e['before']['pin']['sha256']),
            'suspension pre-command binding')
        require(e['intent'] == record(action+'-started.json') and e['result'] == record(action+'-phase.json'),
            'suspension phase record binding')
        records.append(e)
    return records

def verified_lifecycle(terminal=False):
    s=module(HERE/'suspension-lineage.py',LINEAGE_SHA)
    b,o,owned=load_support()
    current=suspension_record(o)
    return s.chain(record('suspension-baseline.json'),lifecycle_records(s),current,str(ROOT),terminal)

def active_epoch(o):
    # Lifecycle observations cannot use the quiescent observer while the one
    # authorized worker is active. Keep actual process and namespace identity.
    expected=record('before.json')['host']
    pid=expected['host']['pid']; proc=Path('/proc')/str(pid)
    require(Path('/proc/sys/kernel/random/boot_id').read_text().strip()==expected['host']['boot'],'lifecycle boot drift')
    fd=os.pidfd_open(pid)
    try:
        poll=select.poll();poll.register(fd,select.POLLIN)
        require(not poll.poll(0) and proc.stat().st_uid==1000,'supervisor no longer live')
        fields=(proc/'stat').read_text().rsplit(') ',1)[1].split()
        require(fields[0] not in ('Z','X') and fields[19]==expected['host']['start'],'supervisor process drift')
        spaces={key:os.readlink(proc/'ns'/key) for key in o.SPACES}
        require(spaces==expected['namespaces']=={key:os.readlink('/proc/self/ns/'+key) for key in o.SPACES},'lifecycle not actual host')
        require(o.process_image(pid,o.GC)==b_gc_sha(),'supervisor image drift')
        for key,unit,user in [('core',o.SERVICE,True),('signer','gas-city-managed-git-signerd.service',False),
                             ('broker','gas-city-privileged-provision.service',False)]:
            require(o.service(unit,user)==expected[key],'lifecycle service drift '+key)
        require(not poll.poll(0),'supervisor terminated')
    finally:os.close(fd)

def b_gc_sha():
    return '69d00186c098b84efe6658c03d888ce07f6d6528d6c446671b53d92f7bde89f9'

def suspension_atime_stable(flags, metadata, now_ns):
    require(flags & (os.ST_NOATIME|os.ST_RELATIME), 'strict/unknown atime policy')
    if flags & os.ST_NOATIME:
        return True
    # Linux relatime updates on atime <= mtime/ctime or age >= 24h. Require
    # strict freshness and a consumed endpoint; keep exact atime comparisons.
    return (metadata['atime_ns'] > max(metadata['mtime_ns'],metadata['ctime_ns'])
        and 0 <= now_ns-metadata['atime_ns'] < 3600*10**9)

def suspension_status_matches(value, expected):
    require(value.get('ok') is True and value.get('city_path')==str(CITY)
        and value.get('running') is True and not value.get('partial')
        and not value.get('partial_errors')
        and value['controller']['running'] is True and value['controller']['pid']==2331,
        'incomplete/wrong-controller suspension observation')
    rows=value['rigs']; rigs={r['name']:r['suspended'] for r in rows}
    require(len(rows)==len(rigs)==4 and set(rigs)=={'gascity','gas-city-template','hpfetcher','blog'}
        and all(type(v) is bool for v in rigs.values()) and type(value['suspended']) is bool,
        'rig suspension observation schema')
    running=[a for a in value['agents'] if a['running']]
    require(len(running)<=1 and all(a['qualified_name']=='gascity/gc.implementation-worker' for a in running)
        and value['summary']['running_agents']==len(running)
        and value['summary'].get('active_sessions',0)<=1,'unexpected live worker')
    signals=value['health'].get('signals',[])
    require(isinstance(signals,list) and set(signals)<= {'city_suspended','no_agents_running'}
        and ('city_suspended' not in signals or value['suspended'])
        and ('no_agents_running' not in signals or not running),'unexpected city health signal')
    return (value['suspended']==expected['city']['suspended']
        and all(v==expected['rigs'][name]['suspended'] for name,v in rigs.items()))

def observed_suspension_endpoint(action,b,o,owned):
    s=module(HERE/'suspension-lineage.py',LINEAGE_SHA)
    flags=os.statvfs(SUSPENSION).f_flag
    require(flags & (os.ST_NOATIME|os.ST_RELATIME),'strict/unknown atime policy')
    first=suspension_record(o)
    save('suspension-'+action+'-barrier-initial.json',first)
    expected=s.image(first)
    deadline=time.monotonic()+30;index=0
    while True:
        remaining=deadline-time.monotonic()
        require(remaining>0,'suspension observation timeout; no lifecycle retry')
        r=phase(action+'-status-'+str(index),GC+['status','--json'],b,owned,timeout=min(15,remaining))
        current=suspension_record(o)
        save('suspension-'+action+'-barrier-observed-'+str(index)+'.json',current)
        # A normal supported controller read may advance only access time.
        x=json.loads(json.dumps(first));z=json.loads(json.dumps(current))
        x['pin']['metadata'].pop('atime_ns');z['pin']['metadata'].pop('atime_ns')
        require(x==z,'suspension changed during controller observation')
        if (suspension_status_matches(json.loads(r['stdout']),expected)
                and suspension_atime_stable(flags,current['pin']['metadata'],time.time_ns())):
            active_epoch(o)
            require(current==suspension_record(o),'suspension endpoint not stable')
            return current
        index+=1
        time.sleep(min(1,max(0,deadline-time.monotonic())))

def lifecycle(action,b,o,owned):
    # The enclosing reviewed runbook owes the fresh sole-task queue proof before
    # invoking resume. This helper records operations, not dispatch authorization.
    s=module(HERE/'suspension-lineage.py',LINEAGE_SHA)
    require(action in s.ACTIONS,'unknown lifecycle action')
    require(not list(ROOT.glob('restore-*')) and not (ROOT/'restored.json').exists()
        and not (ROOT/'stage-refused.json').exists()
        and not list(ROOT.glob('suspension-*-failure.json'))
        and not list(ROOT.glob('suspension-*-refused-after.json')),
        'window terminal/refusal state forbids lifecycle')
    outputs=[action+'-started.json',action+'-phase.json']+[
        'suspension-'+action+suffix for suffix in ('-intent.json','-event.json',
            '-after-observation.json','-failure.json','-refused-after.json')]
    require(all(not os.path.lexists(ROOT/name) for name in outputs),'lifecycle output already exists')
    require(not list(ROOT.glob(action+'-status-*'))
        and not list(ROOT.glob('suspension-'+action+'-barrier-*')),
        'lifecycle status/barrier output already exists')
    require(record('stage-pass.json')==dict(ok=True,worker_launched=False),'window not staged')
    read(CITY/'city.toml',CITY_SHA[1]);read(RECEIPT,RECEIPT_SHA[1])
    active_epoch(o)
    previous=lifecycle_records(s);seen=[r['action'] for r in previous]
    permitted={():['rig-resume'],('rig-resume',):['city-resume','rig-suspend'],
        ('rig-resume','city-resume'):['city-suspend'],
        ('rig-resume','city-resume','city-suspend'):['rig-suspend']}
    require(action in permitted.get(tuple(seen),[]),'lifecycle operation order')
    before=suspension_record(o)
    s.chain(record('suspension-baseline.json'),previous,before,str(ROOT))
    save('suspension-'+action+'-intent.json',dict(action=action,before=before,before_sha256=before['pin']['sha256']))
    try:
        result=phase(action,s.ACTIONS[action][2],b,owned)
        after=observed_suspension_endpoint(action,b,o,owned)
    except BaseException as exc:
        save('suspension-'+action+'-failure.json',dict(error=str(exc),automatic_replay=False))
        complete_containment()
        save('suspension-'+action+'-refused-after.json',suspension_record(o))
        raise
    save('suspension-'+action+'-after-observation.json',after)
    e=dict(action=action,before=before,after=after,intent=record(action+'-started.json'),result=result)
    s.chain(record('suspension-baseline.json'),previous+[e],after,str(ROOT))
    active_epoch(o)
    save('suspension-'+action+'-event.json',e)
    print(json.dumps(dict(ok=True,action=action,phase_only=True)))

def phase(name, argv, b, owned, expected=(0,), timeout=120):
    require(not (ROOT/(name+'-phase.json')).exists(), 'phase already consumed')
    save(name+'-started.json',dict(phase=name,argv=argv,cwd=str(ROOT)))
    r = owned._run_owned_phase(name=name, argv=argv, cwd=ROOT,
        environment=dict(b.ENV, BD_DISABLE_METRICS='1'), timeout=timeout,
        evidence_path=ROOT/(name+'-phase.json'))
    c = r['cleanup']
    require(c['direct_child_reaped'] and c['owned_process_group_gone'] and not c['failures'] and not c['unexpected_survivors'], 'ambiguous containment '+name)
    require(not r['timed_out'] and not r['primary_error'] and r['exit_code'] in expected, 'command refused '+name)
    return r

def complete_containment():
    starts={p.name[:-len('-started.json')]:p for p in ROOT.glob('*-started.json')}
    terminals={p.name[:-len('-phase.json')]:p for p in ROOT.glob('*-phase.json')}
    require(set(starts) == set(terminals), 'missing phase containment evidence')
    for name,path in terminals.items():
        intent=json.loads(read(starts[name])); r=json.loads(read(path)); c=r['cleanup']
        require(intent == dict(phase=r['phase'],argv=r['argv'],cwd=r['cwd']), 'phase evidence identity drift')
        require(c['direct_child_reaped'] and c['owned_process_group_gone'] and not c['failures']
                and not c['unexpected_survivors'], 'ambiguous prior containment')

def invocation(*args):
    return ['/usr/bin/python3','-I','-S','-B',str(LAUNCH),__file__,_SOURCE_SHA,*args]

def city_entries():
    fd=os.open(CITY,os.O_RDONLY|os.O_DIRECTORY|os.O_NOFOLLOW|os.O_NOATIME|os.O_CLOEXEC)
    try:
        before=os.fstat(fd)
        require(CITY.lstat()==before,'city directory identity changed')
        names=sorted(os.listdir(fd))
        entries={name:os.stat(name,dir_fd=fd,follow_symlinks=False) for name in names}
        require(not any(stat.S_ISLNK(s.st_mode) for s in entries.values()),'city child symlink requires review')
        require(sorted(os.listdir(fd))==names,'city directory entry set changed')
        require(entries=={name:os.stat(name,dir_fd=fd,follow_symlinks=False) for name in names},
                'city child metadata changed')
        require(os.fstat(fd)==before and CITY.lstat()==before,'city directory changed')
        return tuple(CITY/name for name in names)
    finally:os.close(fd)

def confined(args, writable=None):
    argv = ['/usr/bin/bwrap','--ro-bind','/','/']
    if writable == 'receipt':
        argv += ['--bind',str(RECEIPT.parent),str(RECEIPT.parent),
                 '--ro-bind',str(RECEIPT.parent/'bin'),str(RECEIPT.parent/'bin')]
    elif writable == 'city':
        argv += ['--bind',str(CITY),str(CITY)]
        for entry in city_entries():
            require(not entry.is_symlink(), 'city child symlink requires review: '+entry.name)
            if entry.name != 'city.toml':
                argv += ['--ro-bind',str(entry),str(entry)]
    return argv+['--unshare-net','--unshare-pid','--new-session','--die-with-parent',
                 '--proc','/proc','--dev','/dev','--',*invocation(*args)]

def mount_proof(writable):
    rows = []
    for line in Path('/proc/self/mountinfo').read_text().splitlines():
        f = line.split()
        p = re.sub(r'\\([0-7]{3})', lambda m: chr(int(m[1],8)), f[4])
        require('\\' not in p, 'mount escape')
        rows.append((p,f[5].split(',')))
    def flags(path):
        return max(((p,v) for p,v in rows if p=='/' or str(path)==p or str(path).startswith(p+'/')), key=lambda x:len(x[0]))[1]
    for path in [Path('/home/loucmane/gascity/home/cache/repos'),CITY/'.gc/platform/assets',CITY/'.gc/platform/backups',ROOT]:
        require('ro' in flags(path), 'protected writable '+str(path))
        require(not any('rw' in v for p,v in rows if p.startswith(str(path)+'/')), 'protected writable descendant')
    if writable == 'city':
        require('rw' in flags(CITY) and 'rw' in flags(CITY/'city.toml'), 'city not writable')
        for p in city_entries():
            if p.name != 'city.toml':
                require('ro' in flags(p), 'other city child writable')
    elif writable == 'receipt':
        require('rw' in flags(RECEIPT.parent) and 'ro' in flags(RECEIPT.parent/'bin'), 'receipt mount')
    else:
        require('ro' in flags(CITY) and 'ro' in flags(RECEIPT), 'read-only phase mounts')

def atomic_replace(path, raw, expected, mode, suffix):
    require(digest(read(path)) == expected, 'atomic preimage drift')
    s = path.lstat()
    require(s.st_uid == s.st_gid == 1000 and stat.S_IMODE(s.st_mode) == mode, 'atomic authority')
    temp = path.parent/('.ga-f37t-'+suffix+'.tmp')
    durable(temp, raw, mode)
    t = temp.lstat()
    require(t.st_uid == s.st_uid and t.st_gid == s.st_gid and t.st_nlink == 1
            and stat.S_ISREG(t.st_mode) and stat.S_IMODE(t.st_mode) == mode
            and read(temp) == raw, 'atomic staged authority')
    require(path.lstat() == s and digest(read(path)) == expected, 'atomic recheck drift')
    os.replace(temp, path)
    d = os.open(path.parent, os.O_RDONLY|os.O_DIRECTORY)
    try:
        os.fsync(d)
    finally:
        os.close(d)
    require(read(path) == raw and stat.S_IMODE(path.stat().st_mode) == mode, 'atomic postimage')

def inner(kind, direction, b):
    require(direction in ('0','1'), 'direction')
    i = int(direction)
    p = pins()
    if kind == 'city':
        mount_proof('city')
        source = PREP/('city.isolated.toml' if i else 'city.baseline.toml')
        atomic_replace(CITY/'city.toml', read(source, CITY_SHA[i]), CITY_SHA[1-i], 0o644, 'stage' if i else 'restore')
        print(json.dumps(dict(ok=True, city_sha256=CITY_SHA[i])))
        return
    require(kind in ('check','apply','verify'), 'inner kind')
    mount_proof('receipt' if kind == 'apply' else None)
    expected = RECEIPT_SHA[i] if kind == 'verify' else RECEIPT_SHA[1-i]
    read(RECEIPT, expected)
    argv = ['/usr/bin/python3','-I','-S','-B',str(PROVISIONER),'--city',str(CITY),
            '--receipt-input',str(INPUT[i]),'--consumer-witness',str(WITNESS),
            '--consumer-witness-sha256',WITNESS_SHA,'--'+('apply' if kind=='apply' else 'check'),'--json']
    r = subprocess.run(argv, env=b.ENV, stdin=subprocess.DEVNULL, capture_output=True, text=True, check=False)
    value = json.loads(r.stdout)
    require(value['schema']=='gc.managed-worker-provision-check.v1', 'provision schema')
    if kind == 'check':
        require(r.returncode==1 and value['ok'] is False and value['drift']==['receipt.sha256'], 'preflight difference')
    else:
        require(r.returncode==0 and value['ok'] is True and value['drift']==[], 'provision refusal')
        read(RECEIPT, RECEIPT_SHA[i])
    print(json.dumps(dict(ok=True, report=value)))

def reload(name, i, b, owned):
    save(name+'-intent.json',dict(revision=REVISION[i]))
    result = phase(name,GC+['reload','--json'],b,owned)
    v = json.loads(result['stdout'])
    require(v['ok'] and not v['async'] and not v['soft'] and v['outcome'] in ('applied','no_change') and v['revision']==REVISION[i], 'reload acknowledgement')
    deadline=time.monotonic()+30
    index=0
    while True:
        remaining=deadline-time.monotonic()
        require(remaining>0, 'controller revision observation timed out; do not repeat reload')
        trace = phase(name+'-trace-'+str(index),GC+['trace','show','--type','cycle_result','--since','2m','--json'],b,owned,timeout=min(15,remaining))
        rows = json.loads(trace['stdout'])['records']
        newest = max(rows,key=lambda x:x['seq']) if rows else None
        if newest:
            require(newest['controller_pid']==2331, 'controller trace epoch drift')
            age = (datetime.now(timezone.utc)-datetime.fromisoformat(newest['ts'].replace('Z','+00:00'))).total_seconds()
            require(0<=age<=120 and newest['fields']['active_template_count']==0, 'stale/active revision')
            if newest['config_revision']==REVISION[i] and newest['completion_status']=='completed':
                break
        index+=1
        # This existing black-box trace command has no completion subscription.
        time.sleep(min(1,max(0,deadline-time.monotonic())))
    save(name+'-accepted.json',dict(ack=v,cycle=newest))

def transition(i, b, o, owned, prefix):
    host(o)
    current_city = digest(read(CITY/'city.toml'))
    require(current_city in CITY_SHA, 'unknown city image')
    current_receipt = digest(read(RECEIPT))
    require(current_receipt in RECEIPT_SHA, 'unknown receipt image')
    snapshot(prefix+'-immediate.json',b,o)
    preservation(record('before.json'),record(prefix+'-immediate.json'),current_city,current_receipt)
    if current_city != CITY_SHA[i]:
        save(prefix+'-city-intent.json',dict(before=current_city,after=CITY_SHA[i]))
        phase(prefix+'-city',confined(['inner','city',str(i)],'city'),b,owned)
    reload(prefix+'-reload',i,b,owned)
    host(o)
    if current_receipt != RECEIPT_SHA[i]:
        phase(prefix+'-receipt-check',confined(['inner','check',str(i)]),b,owned)
        snapshot(prefix+'-before-receipt.json',b,o)
        preservation(record('before.json'),record(prefix+'-before-receipt.json'),CITY_SHA[i],current_receipt)
        save(prefix+'-receipt-intent.json',dict(before=current_receipt,after=RECEIPT_SHA[i]))
        phase(prefix+'-receipt-apply',confined(['inner','apply',str(i)],'receipt'),b,owned)
    phase(prefix+'-receipt-verify',confined(['inner','verify',str(i)]),b,owned)
    host(o)

def main():
    require(globals().get('_SOURCE_SHA') and os.getuid()==os.geteuid()==1000, 'bound user entry')
    read(Path(__file__),_SOURCE_SHA)
    b,o,owned = load_support()
    pins()
    read(HERE/'suspension-lineage.py',LINEAGE_SHA)
    if len(sys.argv)==4 and sys.argv[1]=='inner':
        inner(sys.argv[2],sys.argv[3],b); return
    if len(sys.argv)==3 and sys.argv[1]=='lifecycle':
        lifecycle(sys.argv[2],b,o,owned);return
    require(len(sys.argv)==2 and sys.argv[1] in ('preflight','stage','restore'), 'unknown action')
    action=sys.argv[1]
    if action=='preflight':
        ROOT.mkdir(mode=0o700)
        save('preflight-intent.json',dict(executor_sha256=_SOURCE_SHA))
        host(o)
        read(CITY/'city.toml',CITY_SHA[0]); read(RECEIPT,RECEIPT_SHA[0])
        durable(ROOT/'city.before.toml',read(CITY/'city.toml'),0o644)
        durable(ROOT/'receipt.before.json',read(RECEIPT))
        # Build bwrap arguments now so unsupported child layouts refuse before staging.
        confined(['inner','city','1'],'city')
        result=phase('git-head',['/usr/bin/git','-C',str(WORK),'rev-parse','HEAD'],b,owned)
        require(result['stdout'].strip()==BASE,'worker base drift')
        result=phase('git-status',['/usr/bin/git','-C',str(WORK),'status','--porcelain=v1','--untracked-files=all'],b,owned)
        require(result['stdout']=='','worker not clean')
        snapshot('before.json',b,o)
        baseline=suspension_record(o)
        module(HERE/'suspension-lineage.py',LINEAGE_SHA).image(baseline)
        require(baseline['pin']==record('before.json')['pins'][SUSPENSION],'suspension baseline drift')
        save('suspension-baseline.json',baseline)
        save('preflight-pass.json',dict(ok=True,executor_sha256=_SOURCE_SHA,worker_launched=False))
    elif action=='stage':
        require(record('preflight-pass.json')['executor_sha256']==_SOURCE_SHA,'preflight binding')
        save('stage-consumed.json',dict(executor_sha256=_SOURCE_SHA))
        try:
            transition(1,b,o,owned,'stage')
            snapshot('staged.json',b,o)
            preservation(record('before.json'),record('staged.json'),CITY_SHA[1],RECEIPT_SHA[1])
            save('stage-pass.json',dict(ok=True,worker_launched=False))
        except BaseException as exc:
            save('stage-refused.json',dict(error=str(exc),automatic_replay=False))
            raise
    else:
        require((ROOT/'stage-consumed.json').exists(),'no owned window to restore')
        save('restore-consumed.json',dict(executor_sha256=_SOURCE_SHA))
        # Restoration is explicit, not an exception handler that guesses whether
        # a timed-out mutation completed. The coordinator must inspect disposition.
        complete_containment()
        verified_lifecycle(terminal=True)
        transition(0,b,o,owned,'restore')
        snapshot('restored.json',b,o)
        preservation(record('before.json'),record('restored.json'),CITY_SHA[0],RECEIPT_SHA[0])
        save('restore-pass.json',dict(ok=True,full_platform_integrity_still_required=True))
    print(json.dumps(dict(ok=True,action=action,worker_launched=False)))

if __name__=='__main__':
    main()
