"""One raw route of the already-bound task; all rigs remain suspended.

ga-n12k r11: a rebind of the reviewed ga-y49e route-task-r4.py over window-r11.py. The binding ran as
its own reviewed job, so its outputs are bound by provenance: the executor digest and brief digest
in binding-intent.json and the exact result. Generated by make_round2b.py.
"""
import hashlib
import json
import os
from pathlib import Path
import stat
import types

HERE=Path('/home/loucmane/gas-city-ops-worktrees/ga-e0t1-orchestrator-bootstrap/docs/ai/work-tracking/active/20260903-ga-e0t1-orchestrator-bootstrap-ACTIVE/designs/ga-n12k-window')
ROOT=Path('/var/tmp/ga-n12k-route-20260923-r1')
BIND=Path('/var/tmp/ga-n12k-bind-20260923-r1')
BIND_SHA='fdbf058bb53026aef36f68cf9549a320a201bac797f928441a065f7fd2907ab1'
BRIEF_SHA='e05e4b1171eb9dda37b71c69c1e3046b151257590f66f64ebdb94049658a5846'
HELPER=HERE/'window-r11.py'
SHA='0fce7b014747012f732312454dfbf8d04c367da4a73ea3f433f3933dd6c7eb22'
TARGET='gascity/gc.implementation-worker'

def main():
    assert os.getuid()==os.geteuid()==1000 and globals().get('_SOURCE_SHA')
    assert hashlib.sha256(Path(__file__).read_bytes()).hexdigest()==_SOURCE_SHA
    raw=HELPER.read_bytes();assert hashlib.sha256(raw).hexdigest()==SHA
    m=types.ModuleType('route_window');m.__file__=str(HELPER)
    exec(compile(raw,str(HELPER),'exec',dont_inherit=True),m.__dict__)
    w=m.w;b,o,owned=w.load_support();w.pins()
    assert json.loads(w.read(w.ROOT/'stage-pass.json'))==dict(ok=True,worker_launched=False)
    s=BIND.lstat()
    assert stat.S_ISDIR(s.st_mode) and s.st_uid==1000 and stat.S_IMODE(s.st_mode)==0o700,'bind root authority'
    intent=json.loads(w.read(BIND/'binding-intent.json'))
    assert intent['executor_sha256']==BIND_SHA and intent['brief_sha256']==BRIEF_SHA
    assert intent['worker_launched'] is False
    result=json.loads(w.read(BIND/'result.json'))
    assert result==dict(ok=True,bead='ga-n12k',contract_bound=True,attempt_state='requested',
        routed=False,assigned=False,worker_launched=False,live_configuration_changed=False)
    bound=json.loads(w.read(BIND/'task-after.json'))
    assert bound['metadata']==intent['metadata']
    w.read(w.CITY/'city.toml',w.CITY_SHA[1]);w.read(w.RECEIPT,w.RECEIPT_SHA[1])
    ROOT.mkdir(mode=0o700);w.ROOT=ROOT
    def run(name,args):return w.phase(name,args,b,owned)
    def bead(name):
        v=json.loads(run(name,w.GC+['--rig','gascity','bd','show','ga-n12k','--json'])['stdout'])
        assert isinstance(v,list) and len(v)==1 and v[0]['id']=='ga-n12k'
        return v[0]
    before_host=w.host(o)
    before=bead('task-before-read');w.save('task-before.json',before)
    assert before==bound and before['status']=='open' and not before.get('assignee')
    assert 'gc.routed_to' not in before['metadata']
    argv=w.GC+['--rig','gascity','sling',TARGET,'ga-n12k','--no-formula','--no-convoy','--json']
    preview=json.loads(run('route-preview',argv+['--dry-run'])['stdout'])
    assert preview['schema_version']=='1' and preview['success'] and preview['dry_run'] and not preview['routed']
    assert preview['bead_id']=='ga-n12k' and preview['target']==TARGET
    assert bead('after-preview-read')==before
    assert w.host(o)==before_host
    w.save('route-intent.json',dict(before=before,argv=argv,executor_sha256=_SOURCE_SHA))
    result=json.loads(run('route',argv)['stdout'])
    assert result['schema_version']=='1' and result['success'] and result['routed'] and not result['dry_run']
    assert result['bead_id']=='ga-n12k' and result['target']==TARGET
    assert not result.get('convoy_id') and not result.get('molecule_id')
    after=bead('task-after-read');w.save('task-after.json',after)
    assert after['metadata']==dict(before['metadata'],**{'gc.routed_to':TARGET})
    for key in set(before)|set(after):
        if key not in ('metadata','updated_at'):assert before.get(key)==after.get(key),key
    assert w.host(o)==before_host
    w.save('result.json',dict(ok=True,routed_once=True,rigs_suspended=True,worker_launched=False,
        fresh_full_queue_audit_required_before_resume=True))
    print(json.dumps(w.record('result.json')))

if __name__=='__main__':main()
