"""Generate the round-2a observer stack from reviewed ga-y49e sources. Every replacement is asserted.

Outputs in <package>:
- window-obs-r11.py: from window-state-r9.py (the base plus the cache-atime envelope), loading
  window-base-r11.py instead of window-state-r6.py.
- observe-integrity-r11.py: from observe-platform-integrity-r2.py, with the fresh-window changes:
  - the baseline admission is the base snapshot `before.json` check against the P6 accepted state
    plus the reviewed disposition;
  - there is no prior window lifecycle and no prior restoration observation;
  - the M5 manifest.
- cache-atime-policy-r1.py and suspension-lineage.py: byte-identical copies.

Usage: python3 -B make_round2a.py <package dir>   (window-base-r11.py must already exist there)
"""
import hashlib
import os
import shutil
import sys
from pathlib import Path

L = Path('/tmp/ga-y49e-launch-20260920')


def sha(raw):
    return hashlib.sha256(raw).hexdigest()


def edit(source, source_sha, pairs):
    raw = source.read_bytes()
    assert sha(raw) == source_sha, source
    s = raw.decode()
    for old, new in pairs:
        assert s.count(old) == 1, (source.name, s.count(old), old[:90])
        s = s.replace(old, new)
    return s


def main(package):
    package = Path(package)
    out = Path(os.environ.get('GA4Z38_OUT', package))
    base_sha = sha((out/'window-base-r11.py').read_bytes())
    for name, digest in (('cache-atime-policy-r1.py', '61c3e38e4475061c658a853036922742ab2ce69d44a4577e3f91490674047783'),
                         ('suspension-lineage.py', '4b0d4c5bb713dc4ac802efc5c45f126d026c83fb5ea03fcb5f40d0c680cacbf0')):
        assert sha((L/name).read_bytes()) == digest
        shutil.copyfile(L/name, out/name)
        assert sha((out/name).read_bytes()) == digest
    obs = edit(L/'window-state-r9.py', sha((L/'window-state-r9.py').read_bytes()), [
        ("HERE=Path('/tmp/ga-y49e-launch-20260920')", "HERE=Path('%s')" % package),
        ("BASE_SHA='15f6f4ac010ac600f4f04d2d9a3d8a692b20e1b78a5a93f91adb87c51e8a2fb0'", "BASE_SHA='%s'" % base_sha),
        ("w=load(HERE/'window-state-r6.py',BASE_SHA,'window_r7_base')", "w=load(HERE/'window-base-r11.py',BASE_SHA,'window_r7_base')"),
        ("w.ROOT=HERE/'window-r9'", "w.ROOT=Path('/var/tmp/ga-4z38-window-obs-20260923-r1')"),
    ])
    (out/'window-obs-r11.py').write_text(obs)
    obs_sha = sha((out/'window-obs-r11.py').read_bytes())
    manifest = sha(Path('/home/loucmane/gascity/city/.gc/platform/install-manifest.json').read_bytes())
    assert manifest.startswith('2d7eadce')
    observer = edit(L/'observe-platform-integrity-r2.py', sha((L/'observe-platform-integrity-r2.py').read_bytes()), [
        ('"""Full native integrity read inside read-only mounts, paired with host proof."""',
         '"""Full native integrity read inside read-only mounts, paired with host proof.\n\n'
         'ga-4z38 r11: a rebind of the reviewed ga-y49e observe-platform-integrity-r2.py for a FRESH window on the\n'
         'M5 baseline. It admits the live state against the P6 accepted snapshot plus the reviewed disposition,\n'
         'through the base `before.json` snapshot check. No prior window lifecycle or restoration observation\n'
         'exists, so those two historical comparisons are removed. Generated by make_round2a.py.\n'
         '"""'),
        ("HERE=Path('/tmp/ga-y49e-launch-20260920')", "HERE=Path('%s')" % package),
        ("ROOT=HERE/'integrity-observation-r2'", "ROOT=Path('/var/tmp/ga-4z38-integrity-20260923-r1')"),
        ("W_SHA='0252bc4072f905bb2e8e7f39efd63a3dc12be6c7742227d12efa8a01fbb905d4'", "W_SHA='%s'" % obs_sha),
        ("MANIFEST_SHA='a6324753cb238f8de5ed3af72eef9e3a425ab491dae62778f462849814eb1852'", "MANIFEST_SHA='%s'" % manifest),
        ("    path=HERE/'window-state-r9.py';raw=path.read_bytes()", "    path=HERE/'window-obs-r11.py';raw=path.read_bytes()"),
        ("""    w.host(o);w.read(w.CITY/'city.toml',w.CITY_SHA[0]);w.read(w.RECEIPT,w.RECEIPT_SHA[0])
    w.verified_lifecycle(terminal=True)
    ROOT.mkdir(mode=0o700);w.ROOT=ROOT""", """    w.host(o);w.read(w.CITY/'city.toml',w.CITY_SHA[0]);w.read(w.RECEIPT,w.RECEIPT_SHA[0])
    # Fresh window: no prior lifecycle chain exists to verify. The suspension state is pinned in the
    # snapshot below and admitted against the P6 accepted state.
    ROOT.mkdir(mode=0o700);w.ROOT=ROOT"""),
        ("""    w.snapshot('observed-before.json',b,o)
    before=w.record('observed-before.json')
    accepted=json.loads(w.read(HERE/'restoration-observation-r1/after.json',
        '464d14cd31ccdcd097b19eb6172977e04377730088ac48e6f0299aff02618430'))
    original=json.loads(w.read(HERE/'window-r9/before.json',
        'f9af9039203cc267a0b11fe2e95a2e4da23797dfad2593b48724a9785eb81c47'))
    verify_preservation(r,accepted,before)
    r.p.bounds(original['cache_access_clock'],before['cache_access_clock'])""",
         """    # The base snapshot named before.json admits the live state against the P6 accepted snapshot
    # with the reviewed disposition (approved_historical_image) and the accepted provider pins.
    w.snapshot('before.json',b,o)
    before=w.record('before.json')"""),
        ("""        verify_preservation(r,before,after)
        r.p.bounds(original['cache_access_clock'],after['cache_access_clock'])""",
         """        verify_preservation(r,before,after)"""),
        # The ga-y49e restoration-comparator claim is history of that window, not of this one.
        ("""        root_cache_protected_read_only=True,window_preservation=True,worker_launched=False,
        original_restoration_comparator_remains_hold=True))""",
         """        root_cache_protected_read_only=True,window_preservation=True,worker_launched=False,
        admitted_against_p6_with_disposition=True))"""),
    ])
    (out/'observe-integrity-r11.py').write_text(observer)
    for name in ('window-obs-r11.py', 'observe-integrity-r11.py'):
        text = (out/name).read_text()
        assert '/tmp/ga-y49e-launch-20260920' not in text, name
        print(name, sha((out/name).read_bytes()))


if __name__ == '__main__':
    main(sys.argv[1])
