"""Generate the round-2b window stack from reviewed ga-y49e sources. Every replacement is asserted.

Each source is pinned to its reviewed digest (the review record is named beside it). Outputs, written to
$GA4Z38_OUT or <package>; window-base-r11.py, window-obs-r11.py, observe-integrity-r11.py and
worker-brief.md must already be there:
- restore-r9-routes-r3.py and route-chain-r1.py: byte-identical copies.
- window-r11.py: from window-state-r10.py, over window-base-r11.py. The fresh integrity observation is
  bound by provenance, because the observer runs as the job immediately before preflight.
- bind-task-r3.py: from bind-task-r2.py; binds ga-4z38 before the window exists.
- route-task-r5.py: from route-task-r4.py, over window-r11.py; the binding outputs are bound by provenance.
- audit-queue-r3.py: from audit-routed-queue-r2.py, with a route mode and a resume mode.
- observe-terminal-r11.py: from observe-platform-integrity-r2.py; admits the window's accepted restoration
  and its terminal suspension lineage.

Usage: python3 -B make_round2b.py <package dir>
"""
import hashlib
import os
import shutil
import sys
from pathlib import Path

L = Path('/tmp/ga-y49e-launch-20260920')
P6 = ('/home/loucmane/gas-city-ops-worktrees/ga-e0t1-orchestrator-bootstrap/docs/ai/work-tracking/active/'
      '20260903-ga-e0t1-orchestrator-bootstrap-ACTIVE/designs/gct-m1wh-p6')
WINDOW = '/var/tmp/ga-4z38-window-20260923-r1'
INSPECTOR_SHA = '77685c663383d7b61e61e41f5e833a90be19bbfecfd8d95dcabe868d30a06237'


def sha(raw):
    return hashlib.sha256(raw).hexdigest()


def edit(name, source_sha, pairs):
    raw = (L/name).read_bytes()
    assert sha(raw) == source_sha, name
    s = raw.decode()
    for old, new, *count in pairs:
        n = count[0] if count else 1
        assert s.count(old) == n, (name, s.count(old), old[:90])
        s = s.replace(old, new)
    # Normalize the file end to one newline (route-task-r4.py ends with a blank line).
    return s.rstrip('\n') + '\n'


def main(package):
    package = Path(package)
    out = Path(os.environ.get('GA4Z38_OUT', package))
    digest = {name: sha((out/name).read_bytes()) for name in
              ('window-base-r11.py', 'window-obs-r11.py', 'observe-integrity-r11.py', 'worker-brief.md')}
    manifest = sha(Path('/home/loucmane/gascity/city/.gc/platform/install-manifest.json').read_bytes())
    assert manifest == '2d7eadce62c4e567697813cc9122414f1e94c3bd9d389aef92015adef7f36319'
    compose = sha(Path(P6, 'p6-observe-compose.py').read_bytes())
    assert compose == '43b94ce677dcaa80b6937f7205362063da151f0608a99874b18b692ab8f2c8d6'
    # Pure route functions and the route-event chain policy (window-r10-package.md).
    for name, value in (('restore-r9-routes-r3.py', '8d041af74297b44c0bedecdbcaa776ac92f433eba801afa0ee0a89a71eecc7c2'),
                        ('route-chain-r1.py', 'e408e2ddf98d6cb403a45b26f72aba0e47817a3b8dd2adb19adade696a35eacf')):
        assert sha((L/name).read_bytes()) == value
        shutil.copyfile(L/name, out/name)
        assert sha((out/name).read_bytes()) == value

    # window-state-r10.py e51b5fa8 (window-r10-package.md, window-r10-source-review.md).
    window = edit('window-state-r10.py', 'e51b5fa82368cfab26829265f4131c79138d834739e544dad3ed139dc142a3cf', [
        ('"""Fresh integrity-bound window with strict reads and observed route regeneration."""',
         '"""Fresh integrity-bound window with strict reads and observed route regeneration.\n\n'
         'ga-4z38 r11: a rebind of the reviewed ga-y49e window-state-r10.py over window-base-r11.py. The fresh\n'
         'integrity observation runs as the job immediately before preflight, so it is bound by provenance\n'
         '(executor digest, exact content, digests recorded once at before.json) instead of reviewed output\n'
         'digests. Generated by make_round2b.py.\n'
         '"""'),
        ("HERE=Path('/tmp/ga-y49e-launch-20260920')", "HERE=Path('%s')" % package),
        ("BASE_SHA='b10a3810c9627b626dd8e5bebf54f406ee5248b0578b373b0d924dcb367355bd'",
         "BASE_SHA='%s'" % digest['window-base-r11.py']),
        ("w=load(HERE/'window-state-r6-read-safe.py',BASE_SHA,'window_r7_base')",
         "w=load(HERE/'window-base-r11.py',BASE_SHA,'window_r7_base')"),
        ("w.ROOT=HERE/'window-r10'", "w.ROOT=Path('%s')" % WINDOW),
        ("""INTEGRITY=HERE/'integrity-observation-r2'
INTEGRITY_SHA='d806cc8f4ec66f56cbf0e34ac3d3e944eee0ad05d3a0a59ed50d85dc98f4a55b'
INTEGRITY_RESULT_SHA='d421b626e29e2722ad0f8fcb0f261414d5a68d88dd3fa3affcbb235d750fb646'
""", """INTEGRITY=Path('/var/tmp/ga-4z38-integrity-20260923-r1')
OBSERVER_SHA='%s'
INSPECTOR_SHA='%s'

def integrity_baseline(first):
    # The reviewed observer creates INTEGRITY exclusively (0700) and records its executor digest
    # before observing. Its outputs are bound by exact content here; their digests are recorded once,
    # at before.json, and every later snapshot requires the same bytes.
    s=INTEGRITY.lstat()
    w.require(stat.S_ISDIR(s.st_mode) and s.st_uid==1000 and stat.S_IMODE(s.st_mode)==0o700,
        'integrity root authority')
    w.require(json.loads(w.read(INTEGRITY/'intent.json'))==dict(executor_sha256=OBSERVER_SHA,
        binary_sha256=INSPECTOR_SHA,version_probes_only=True,worker_launch=False),'integrity executor')
    w.require(not os.path.lexists(INTEGRITY/'primary-failure.json'),'integrity primary failure')
    raw=w.read(INTEGRITY/'result.json')
    w.require(json.loads(raw)==dict(ok=True,actual_host_verified=True,
        admitted_against_p6_with_disposition=True,
        report=dict(ok=True,report={'Drifts':None},schema='ga.platform-inspect-observation.v1'),
        root_cache_protected_read_only=True,window_preservation=True,worker_launched=False),
        'fresh native integrity result')
    w.require(json.loads(w.read(INTEGRITY/'preservation.json'))==dict(window_preservation=True,
        cache_atime_deltas=0,runtime_child_metadata_policy='unchanged pinned R6',timestamp_writes=False),
        'integrity preservation')
    after=w.read(INTEGRITY/'observed-after.json')
    binding=dict(root=str(INTEGRITY),observer_sha256=OBSERVER_SHA,result_sha256=w.digest(raw),
        observed_after_sha256=w.digest(after))
    if first:
        w.require(not os.path.lexists(w.ROOT/'integrity-binding.json'),'integrity binding already recorded')
        original_save('integrity-binding.json',binding)
    else:
        w.require(w.record('integrity-binding.json')==binding,'integrity baseline changed after admission')
    return json.loads(after)
""" % (digest['observe-integrity-r11.py'], INSPECTOR_SHA)),
        ("""    prior=json.loads(w.read(INTEGRITY/'observed-after.json',INTEGRITY_SHA))
    result=json.loads(w.read(INTEGRITY/'result.json',INTEGRITY_RESULT_SHA))
    w.require(result==dict(ok=True,actual_host_verified=True,
        original_restoration_comparator_remains_hold=True,
        report=dict(ok=True,report={'Drifts':None},schema='ga.platform-inspect-observation.v1'),
        root_cache_protected_read_only=True,window_preservation=True,worker_launched=False),
        'fresh native integrity result')
""", """    prior=integrity_baseline(name=='before.json')
"""),
        ("""        # Bind the proven restored postimage, not the obsolete pre-restoration
        # inode image. The failed R9 result and every timestamp remain untouched.
""", """        # Bind the fresh observer postimage. Every timestamp remains untouched.
"""),
        ("        baseline_integrity_sha256=INTEGRITY_SHA,timestamp_writes=False)",
         "        baseline_integrity_sha256=w.record('integrity-binding.json')['observed_after_sha256'],\n"
         "        timestamp_writes=False)"),
    ])
    assert 'INTEGRITY_SHA' not in window and 'INTEGRITY_RESULT_SHA' not in window
    (out/'window-r11.py').write_text(window)
    digest['window-r11.py'] = sha((out/'window-r11.py').read_bytes())

    # bind-task-r2.py 17ce31a4 (consolidated-r2-source-review-20260920.md).
    bind = edit('bind-task-r2.py', '17ce31a4fb39e2054704b46623628232577fd033659905f1d6a213608ea37198', [
        ('"""One supported ga-y49e contract/enrollment patch; never route or resume."""',
         '"""One supported ga-4z38 contract/enrollment patch; never route or resume.\n\n'
         'ga-4z38 r11: a rebind of the reviewed ga-y49e bind-task-r2.py. It runs as its own job BEFORE the\n'
         'window, so no window root may exist yet; route-task-r5.py binds these outputs by provenance.\n'
         'Generated by make_round2b.py.\n'
         '"""'),
        ("HERE=Path('/tmp/ga-y49e-launch-20260920')", "HERE=Path('%s')" % package),
        ("ROOT=HERE/'task-binding-r2'", "ROOT=Path('/var/tmp/ga-4z38-bind-20260923-r1')"),
        ("HELPER=HERE/'window-state-r6.py'", "HELPER=HERE/'window-base-r11.py'"),
        ("HELPER_SHA='15f6f4ac010ac600f4f04d2d9a3d8a692b20e1b78a5a93f91adb87c51e8a2fb0'",
         "HELPER_SHA='%s'" % digest['window-base-r11.py']),
        ("BRIEF_SHA='193b2420e85a91224b5fa1196f9e043ca3af7d8e5a22401338469e6469aa9d35'",
         "BRIEF_SHA='%s'" % digest['worker-brief.md']),
        ("BEAD='ga-y49e'", "BEAD='ga-4z38'"),
        ("WORK='/home/loucmane/gascity-core-worktrees/ga-y49e-typed-route-cycles'",
         "WORK='/home/loucmane/gascity-core-worktrees/ga-4z38-typed-route-cycles'"),
        ("BRANCH='codex/ga-y49e-typed-route-cycles'", "BRANCH='codex/ga-4z38-typed-route-cycles'"),
        ("    assert json.loads(w.read(HERE/'window-r6/preflight-pass.json'))==dict(ok=True,executor_sha256=HELPER_SHA,worker_launched=False)\n",
         "    # Binding precedes the window: the base ROOT is the window root, which must not exist yet.\n"
         "    assert not os.path.lexists(w.ROOT), 'binding must precede the window'\n"),
        ('"bead_id":"ga-y49e"', '"bead_id":"ga-4z38"'),
        ("'.gc/worker-evidence/ga-y49e/implementation-summary.md'", "'.gc/worker-evidence/ga-4z38/implementation-summary.md'"),
    ])
    assert 'ga-y49e' not in bind.replace('reviewed ga-y49e', '')
    (out/'bind-task-r3.py').write_text(bind)
    digest['bind-task-r3.py'] = sha((out/'bind-task-r3.py').read_bytes())

    # route-task-r4.py 2f6ec34b (window-r10-package.md, window-r10-preflight-review.md).
    route = edit('route-task-r4.py', '2f6ec34b4fff94dfff4da01538d22391da9b74870dadd6f9eb866f6bfc58a45a', [
        ('"""One raw route of the already-bound task; all rigs remain suspended."""',
         '"""One raw route of the already-bound task; all rigs remain suspended.\n\n'
         'ga-4z38 r11: a rebind of the reviewed ga-y49e route-task-r4.py over window-r11.py. The binding ran as\n'
         'its own reviewed job, so its outputs are bound by provenance: the executor digest and brief digest\n'
         'in binding-intent.json and the exact result. Generated by make_round2b.py.\n'
         '"""'),
        ("HERE=Path('/tmp/ga-y49e-launch-20260920')", "HERE=Path('%s')" % package),
        ("ROOT=HERE/'task-route-r4'", "ROOT=Path('/var/tmp/ga-4z38-route-20260923-r1')\n"
         "BIND=Path('/var/tmp/ga-4z38-bind-20260923-r1')\n"
         "BIND_SHA='%s'\n"
         "BRIEF_SHA='%s'" % (digest['bind-task-r3.py'], digest['worker-brief.md'])),
        ("from pathlib import Path\nimport types\n", "from pathlib import Path\nimport stat\nimport types\n"),
        ("HELPER=HERE/'window-state-r10.py'", "HELPER=HERE/'window-r11.py'"),
        ("SHA='e51b5fa82368cfab26829265f4131c79138d834739e544dad3ed139dc142a3cf'", "SHA='%s'" % digest['window-r11.py']),
        ("    assert json.loads(w.read(HERE/'window-r10/stage-pass.json'))==dict(ok=True,worker_launched=False)",
         "    assert json.loads(w.read(w.ROOT/'stage-pass.json'))==dict(ok=True,worker_launched=False)"),
        ("""    result=json.loads(w.read(HERE/'task-binding-r2/result.json',
        '74e72aab238f367986d9ad289d6a1b3525ac15e457b3d997e1eb13c244609b4d'))
    assert result['ok'] is True and result['attempt_state']=='requested' and result['routed'] is False
    bound=json.loads(w.read(HERE/'task-binding-r2/task-after.json',
        '863a860431dbe09706d1864aa0730897a780060644bae7b429f44dd4485bc37c'))
""", """    s=BIND.lstat()
    assert stat.S_ISDIR(s.st_mode) and s.st_uid==1000 and stat.S_IMODE(s.st_mode)==0o700,'bind root authority'
    intent=json.loads(w.read(BIND/'binding-intent.json'))
    assert intent['executor_sha256']==BIND_SHA and intent['brief_sha256']==BRIEF_SHA
    assert intent['worker_launched'] is False
    result=json.loads(w.read(BIND/'result.json'))
    assert result==dict(ok=True,bead='ga-4z38',contract_bound=True,attempt_state='requested',
        routed=False,assigned=False,worker_launched=False,live_configuration_changed=False)
    bound=json.loads(w.read(BIND/'task-after.json'))
    assert bound['metadata']==intent['metadata']
"""),
        ("'ga-y49e'", "'ga-4z38'", 5),
    ])
    assert 'ga-y49e' not in route.replace('reviewed ga-y49e', '')
    (out/'route-task-r5.py').write_text(route)

    # audit-routed-queue-r2.py 280d86ca (atime-final-package-r1.md, atime-amendment-and-review-r1.md).
    audit = edit('audit-routed-queue-r2.py', '280d86caf6f7490d1179c01c8ebc2de2934e837dc9628352ecb8259699ed8bd5', [
        ('"""Read-only sole eligible native task audit after route, before resume."""',
         '"""Read-only sole eligible native task audit after route, before resume.\n\n'
         'ga-4z38 r11: a rebind of the reviewed ga-y49e audit-routed-queue-r2.py. Mode `route` runs right after\n'
         'the route (every rig suspended). Mode `resume` runs after rig-resume and before city-resume (only\n'
         'the gascity rig resumed). Generated by make_round2b.py.\n'
         '"""'),
        ("from pathlib import Path\nimport types\n", "from pathlib import Path\nimport sys\nimport types\n"),
        ("ROOT = Path('/tmp/ga-y49e-launch-20260920/queue-audit-after-route-r2')",
         "MODE = sys.argv[1] if len(sys.argv) == 2 else None\n"
         "assert MODE in ('route', 'resume'), 'audit mode'\n"
         "ROOT = Path('/var/tmp/ga-4z38-audit-%s-20260923-r1' % MODE)"),
        ("SUPPORT=Path('/tmp/ga-ecwh-provisioning-successor-20260920/observe-compose.py')",
         "SUPPORT=Path('%s/p6-observe-compose.py')" % P6),
        ("assert hashlib.sha256(raw).hexdigest()=='be8461f48192ccadcafebb26619650fc9378a46e425026fc9aa6357c0a276c01'",
         "assert hashlib.sha256(raw).hexdigest()=='%s'" % compose),
        ("'ga-y49e'", "'ga-4z38'", 4),
        ("'/home/loucmane/gascity-core-worktrees/ga-y49e-typed-route-cycles'",
         "'/home/loucmane/gascity-core-worktrees/ga-4z38-typed-route-cycles'"),
        ("assert len(state['rigs']) == 4 and all(r['suspended'] for r in state['rigs'])",
         "# route mode: every rig suspended. resume mode: only the gascity rig resumed.\n"
         "assert len(state['rigs']) == 4 and all(r['suspended'] == (MODE == 'route' or r['name'] != 'gascity')\n"
         "                                       for r in state['rigs'])"),
        ("result = dict(ok=True, observations=observations,", "result = dict(ok=True, mode=MODE, observations=observations,"),
    ])
    assert 'ga-y49e' not in audit.replace('reviewed ga-y49e', '')
    (out/'audit-queue-r3.py').write_text(audit)

    # observe-platform-integrity-r2.py 050cb878 (native-integrity-r2-review.md).
    terminal = edit('observe-platform-integrity-r2.py', '050cb878b46a453da9afc9c197f78a57c6f38ac56439510cd1fd353b9522f839', [
        ('"""Full native integrity read inside read-only mounts, paired with host proof."""',
         '"""Full native integrity read inside read-only mounts, paired with host proof.\n\n'
         'ga-4z38 r11 terminal observer: a rebind of the reviewed ga-y49e observe-platform-integrity-r2.py.\n'
         'It verifies the terminal suspension lineage in the window root, admits the window\'s accepted\n'
         'restoration (restored.json, bound by the window executor digest and restore-pass.json), and\n'
         'bounds the cache clock from the window before.json. Generated by make_round2b.py.\n'
         '"""'),
        ("HERE=Path('/tmp/ga-y49e-launch-20260920')", "HERE=Path('%s')" % package),
        ("ROOT=HERE/'integrity-observation-r2'", "ROOT=Path('/var/tmp/ga-4z38-terminal-20260923-r1')\n"
         "WINDOW=Path('%s')\n"
         "WINDOW_SHA='%s'" % (WINDOW, digest['window-r11.py'])),
        ("W_SHA='0252bc4072f905bb2e8e7f39efd63a3dc12be6c7742227d12efa8a01fbb905d4'", "W_SHA='%s'" % digest['window-obs-r11.py']),
        ("MANIFEST_SHA='a6324753cb238f8de5ed3af72eef9e3a425ab491dae62778f462849814eb1852'", "MANIFEST_SHA='%s'" % manifest),
        ("    path=HERE/'window-state-r9.py';raw=path.read_bytes()", "    path=HERE/'window-obs-r11.py';raw=path.read_bytes()"),
        ("""    if sys.argv[1:]==['inner']:
        w.mount_proof(None)""",
         """    if sys.argv[1:]==['inner']:
        w.ROOT=ROOT;w.mount_proof(None)"""),
        ("""    w.verified_lifecycle(terminal=True)
    ROOT.mkdir(mode=0o700);w.ROOT=ROOT""", """    # The terminal suspension lineage and the accepted restoration are in the window root.
    w.ROOT=WINDOW
    w.verified_lifecycle(terminal=True)
    w.require(w.record('restore-consumed.json')==dict(executor_sha256=WINDOW_SHA)
        and w.record('restore-pass.json')==dict(ok=True,full_platform_integrity_still_required=True),
        'accepted window restoration')
    accepted=w.record('restored.json');original=w.record('before.json')
    # The window layer adds route-regeneration keys; no reload happens after restore, and this layer
    # compares every other field.
    for key in ('generated_routes','generated_route_chain'):accepted.pop(key)
    ROOT.mkdir(mode=0o700);w.ROOT=ROOT"""),
        ("""    accepted=json.loads(w.read(HERE/'restoration-observation-r1/after.json',
        '464d14cd31ccdcd097b19eb6172977e04377730088ac48e6f0299aff02618430'))
    original=json.loads(w.read(HERE/'window-r9/before.json',
        'f9af9039203cc267a0b11fe2e95a2e4da23797dfad2593b48724a9785eb81c47'))
""", ""),
        ("""        root_cache_protected_read_only=True,window_preservation=True,worker_launched=False,
        original_restoration_comparator_remains_hold=True))""",
         """        root_cache_protected_read_only=True,window_preservation=True,worker_launched=False,
        terminal_suspension_endpoint_bound=True,accepted_restoration_bound=True))"""),
    ])
    (out/'observe-terminal-r11.py').write_text(terminal)

    # reconcile-predecessor.py 4a66d443 (isolation-and-reconciliation-checkpoint.md): the reviewed
    # status-only hold that moved ga-e0t1.14 to blocked, rebound to ga-y49e.
    reconcile = edit('reconcile-predecessor.py', '4a66d4430222966be12bd8f7b6d884fb1325acd68b548f400fcdc384ba1e45c0', [
        ('"""One reviewed status-only failed-attempt reconciliation; never retry mutation."""',
         '"""One reviewed status-only failed-attempt reconciliation; never retry mutation.\n\n'
         'ga-4z38 r11: a rebind of the reviewed reconcile-predecessor.py (the ga-e0t1.14 hold) to ga-y49e, whose\n'
         'consumed attempt still routes it to the worker template. Runs before BIND. Generated by\n'
         'make_round2b.py.\n'
         '"""'),
        ("ROOT=Path('/tmp/ga-y49e-launch-20260920/predecessor-hold-r2')",
         "ROOT=Path('/var/tmp/ga-4z38-reconcile-20260923-r1')"),
        ("""NOTE=('Failed-attempt hold 2026-09-20: the September-17 native Write negative '
      'unexpectedly succeeded; ci-m4urh was contained and closed. Its native attempt '
      'remains permanently consumed. Fresh successor ga-y49e owns the remaining '
      'implementation proof. This task is blocked pending successor disposition, '
      'not PASS, reset, retry, reroute or claim. All existing metadata, route, '
      'session/worktree bindings, evidence and dependency edges are preserved. '
      'This reviewed status-only reconciliation supersedes the preparation draft '
      'promise of leaving status untouched; no previous evidence is rewritten.')""",
         """NOTE=('Failed-attempt hold 2026-09-23: session ci-b24ev failed-create on '
      '2026-09-21 (the positional-prompt defect, since fixed and live through M5); '
      'its native attempt remains permanently consumed. Fresh successor ga-4z38 owns '
      'the remaining implementation proof. This task is blocked pending successor '
      'disposition, not PASS, reset, retry, reroute or claim. All existing metadata, '
      'route, session/worktree bindings, evidence and dependency edges are preserved. '
      'This reviewed status-only reconciliation follows the ga-e0t1.14 precedent; '
      'no previous evidence is rewritten.')"""),
        ("before=bead('ga-e0t1.14');other=bead('ga-5ot6');new=bead('ga-y49e')",
         "before=bead('ga-y49e');other=bead('ga-e0t1.14');new=bead('ga-4z38')"),
        ("assert attempt['state']=='started' and attempt['session_id']=='ci-m4urh' and attempt['limit']==1",
         "assert attempt['state']=='started' and attempt['session_id']=='ci-b24ev' and attempt['limit']==1"),
        ("closed=run('bd','show','ci-m4urh','--json','--readonly')",
         "closed=run('bd','show','ci-b24ev','--json','--readonly')"),
        ("assert len(closed)==1 and closed[0]['id']=='ci-m4urh' and closed[0]['status']=='closed'",
         "assert len(closed)==1 and closed[0]['id']=='ci-b24ev' and closed[0]['status']=='closed'\n"
         "assert closed[0]['metadata']['state']=='failed-create'"),
        ("assert 'Probe 2 FAIL' in before['notes'] and '12:28:06Z' in before['notes']",
         "assert m['gc.work_dir']=='/home/loucmane/gascity-core-worktrees/ga-y49e-typed-route-cycles'"),
        ("assert {v['id'] for v in prior}=={'ga-e0t1.14'} and cityprior==[]",
         "assert {v['id'] for v in prior}=={'ga-y49e'} and cityprior==[]\n"
         "# No dependency edge names ga-y49e, so no joined view of another Bead changes with this write.\n"
         "for row in (other,new):\n"
         "    assert 'ga-y49e' not in json.dumps([row.get('dependencies'),row.get('dependents')]),row['id']"),
        ("assert bead('ga-e0t1.14')==before,'pre-mutation ledger drift'",
         "assert bead('ga-y49e')==before,'pre-mutation ledger drift'"),
        ("save('mutation-intent.json',dict(task='ga-e0t1.14',", "save('mutation-intent.json',dict(task='ga-y49e',"),
        ("result=run('--rig','gascity','bd','update','ga-e0t1.14','--status','blocked',",
         "result=run('--rig','gascity','bd','update','ga-y49e','--status','blocked',"),
        ("after=bead('ga-e0t1.14');save('task.after.json',after)", "after=bead('ga-y49e');save('task.after.json',after)"),
        ("""otherafter=bead('ga-5ot6');save('predecessor.after.json',otherafter)
# The expanded dependency payload reflects this status change. Its identity and
# all actual ga-5ot6 fields remain exact; do not mistake a joined view for a write.
expectedother=copy.deepcopy(other)
for d in expectedother.get('dependencies',[]):
    if d['id']=='ga-e0t1.14':d['status']='blocked'
assert otherafter==expectedother,'unrelated predecessor delta'
assert bead('ga-y49e')==new and run('bd','show','ci-m4urh','--json','--readonly')==closed""",
         """otherafter=bead('ga-e0t1.14');save('predecessor.after.json',otherafter)
# ga-y49e has no dependency edges, so the earlier predecessor stays exact.
assert otherafter==other,'unrelated predecessor delta'
assert bead('ga-4z38')==new and run('bd','show','ci-b24ev','--json','--readonly')==closed"""),
        ("print(json.dumps(dict(ok=True,root=str(ROOT),task='ga-e0t1.14',status='blocked')))",
         "print(json.dumps(dict(ok=True,root=str(ROOT),task='ga-y49e',status='blocked')))"),
    ])
    assert 'ga-5ot6' not in reconcile and 'ci-m4urh' not in reconcile
    (out/'reconcile-predecessor-r3.py').write_text(reconcile)

    # restore-admission-r1.py 90328ee7: the read-only admission R10 ran before its restore (it passed in
    # /tmp/ga-y49e-launch-20260920/window-r10). Rebound to window-r11.py.
    admission = edit('restore-admission-r1.py', '90328ee7833a0cc008019e529bb599ab18f0c90c7bbfb0598ba19244f67cb6f2', [
        ('"""Read-only admission to the existing reviewed R10 restore; never restore here."""',
         '"""Read-only admission to the existing reviewed R10 restore; never restore here.\n\n'
         'ga-4z38 r11: a rebind of the R10 restore-admission-r1.py to window-r11.py. It runs after CONTAIN and\n'
         'the session close, and RESTORE.sh requires its pass record, so RESTORE is consumed only after this\n'
         'full preservation check passed. Generated by make_round2b.py.\n'
         '"""'),
        ("HERE = Path('/tmp/ga-y49e-launch-20260920')", "HERE = Path('%s')" % package),
        ("SOURCE = HERE / 'window-state-r10.py'", "SOURCE = HERE / 'window-r11.py'"),
        ("SHA = 'e51b5fa82368cfab26829265f4131c79138d834739e544dad3ed139dc142a3cf'", "SHA = '%s'" % digest['window-r11.py']),
    ])
    (out/'restore-admission-r3.py').write_text(admission)
    for name in ('window-r11.py', 'bind-task-r3.py', 'route-task-r5.py', 'audit-queue-r3.py', 'observe-terminal-r11.py',
                 'reconcile-predecessor-r3.py', 'restore-admission-r3.py'):
        text = (out/name).read_text()
        assert '/tmp/ga-y49e-launch-20260920' not in text and '/tmp/ga-ecwh-provisioning' not in text, name
        print(name, sha((out/name).read_bytes()))


if __name__ == '__main__':
    main(sys.argv[1])
