"""Generate window-base-r11.py from the reviewed ga-y49e base window-state-r6-read-safe.py (b10a3810).

Every replacement asserts its exact count, and the output is written only after all of them pass.
The only changes are the rebind below: baseline, task, support modules, the prep outputs, the model
string, the accepted-state disposition and the temp-file prefix. Nothing else changes.

Usage: python3 -B make_window_base_r11.py <package dir> <prep root>
"""
import hashlib
import json
import os
import sys
from pathlib import Path

SOURCE = Path('/tmp/ga-y49e-launch-20260920/window-state-r6-read-safe.py')
SOURCE_SHA = 'b10a3810c9627b626dd8e5bebf54f406ee5248b0578b373b0d924dcb367355bd'
P6 = ('/home/loucmane/gas-city-ops-worktrees/ga-e0t1-orchestrator-bootstrap/docs/ai/work-tracking/active/'
      '20260903-ga-e0t1-orchestrator-bootstrap-ACTIVE/designs/gct-m1wh-p6')


def sha(raw):
    return hashlib.sha256(raw).hexdigest()


def main(package, prep):
    raw = SOURCE.read_bytes()
    assert sha(raw) == SOURCE_SHA
    s = raw.decode()
    result = json.loads(Path(prep, 'result.json').read_bytes())
    assert result['ok'] is True and result['installed'] is False and result['worker_launched'] is False
    assert result['city_after_sha256'] == '5f3b60e1c1e391b5a1f66de62a2e767ea226570ce7549c6dfb526cd072e6530d'
    assert result['city_before_sha256'] == '4f7e170fc0503841576c0bb26c33ee5d0aab4e796821f3b1cd874ecef733c591'
    assert result['receipt_before_sha256'] == '0b30c23f4484382fd4918f394599268f4f4005ac71118e8a7f82ca72eb9615ff'
    assert result['revision_before'] == 'd6ca85cd96c7aab4ea0b6a7954d2d74e5e6bb211cde0bb820f3b6f815023bd88'
    assert result['changed_receipt_fields'] == ['permission_revision', 'receipt_sha256']
    # Full reviewed digests of every input this generator reads (P6 adoption, prep result, P6 modules).
    for path, digest in ((Path(prep, 'result.json'), 'c0d1959c4e0df67e8f02b8716f43f2adf542c9d2b358d75f4027d92f91480c03'),
                         (Path('/var/tmp/gct-m1wh-p6-adoption-20260923-r2/typed-support.json'),
                          '5a630443b7b47c0054b96f593b18d3012ac671d4124c25eae3afa54bcfe8cfeb'),
                         (Path('/var/tmp/gct-m1wh-p6-adoption-20260923-r2/after.json'),
                          '1c025ef9ef31d75f7becb6e6ed1fd426f3d318eb53913cf8e24888f163900b70'),
                         (Path('/var/tmp/gct-m1wh-p6-adoption-20260923-r2/after.json.provider-pins'),
                          'a5f7f8c11a95b48d01f910c5c4668828d61a587a5942545f27d403ebadfeac8f'),
                         (Path(P6, 'p6-observe-compose.py'), '43b94ce677dcaa80b6937f7205362063da151f0608a99874b18b692ab8f2c8d6'),
                         (Path(P6, 'p6-readiness.py'), '7b28b3e551e86818a2cdda3e53ed90c7072781e0a9354bd1ebf5d9425d579133')):
        assert sha(path.read_bytes()) == digest, path
    receipt_after = result['receipt_after_sha256']
    revision_after = result['revision_after']
    assert sha(Path(prep, 'receipt.final.json').read_bytes()) == receipt_after
    assert sha(Path(prep, 'city.isolated.toml').read_bytes()) == result['city_after_sha256']

    def rep(old, new, count=1):
        nonlocal s
        assert s.count(old) == count, (s.count(old), old[:90])
        s = s.replace(old, new)

    rep('"""Bounded city/receipt window staging and exact restoration; never starts work."""',
        '"""Bounded city/receipt window staging and exact restoration; never starts work.\n\n'
        'ga-4z38 r11: a rebind of the reviewed ga-y49e base window-state-r6-read-safe.py (b10a3810) onto the\n'
        'M5 baseline and task ga-4z38. Generated by make_window_base_r11.py with asserted replacements only.\n'
        '"""')
    rep("HERE = Path('/tmp/ga-y49e-launch-20260920')", "HERE = Path('%s')" % package)
    rep("ROOT = HERE/'window-r6'", "ROOT = Path('/var/tmp/ga-4z38-window-20260923-r1')\n"
        "PREP = Path('%s')" % prep)
    rep("SUPPORT = Path('/tmp/ga-ecwh-provisioning-successor-20260920')", "SUPPORT = Path('%s')" % P6)
    rep("WORK = Path('/home/loucmane/gascity-core-worktrees/ga-y49e-typed-route-cycles')",
        "WORK = Path('/home/loucmane/gascity-core-worktrees/ga-4z38-typed-route-cycles')")
    rep("WITNESS = Path('/var/tmp/ga-ecwh-receipt-adoption-20260920-r1/typed-support.json')",
        "WITNESS = Path('/var/tmp/gct-m1wh-p6-adoption-20260923-r2/typed-support.json')")
    rep("WITNESS_SHA = '21714f5bedd22044d83a8d6df96b27d6e891f932cdf804e97cfb0ba88fd6a538'",
        "WITNESS_SHA = '%s'" % sha(Path('/var/tmp/gct-m1wh-p6-adoption-20260923-r2/typed-support.json').read_bytes()))
    rep("""CITY_SHA = ('6594ee77b3efc30cd2f4cfa412541a5a1076fb324118fb8aec3df1d29b81528b',
            'abf1af0b4a11f056f5217473a8068db92abb8ad8d6cdbbda27df598fc027fe70')""",
        """CITY_SHA = ('4f7e170fc0503841576c0bb26c33ee5d0aab4e796821f3b1cd874ecef733c591',
            '5f3b60e1c1e391b5a1f66de62a2e767ea226570ce7549c6dfb526cd072e6530d')""")
    rep("""RECEIPT_SHA = ('01ed1bce0b99d5c6043804cdacb2b25bc725bffb00dba3450888284e570d0a8a',
               'ab11fa9163a58d1e237f6dd161f6f0f2a78ede178b795b699c7aae96d2044c47')""",
        """RECEIPT_SHA = ('0b30c23f4484382fd4918f394599268f4f4005ac71118e8a7f82ca72eb9615ff',
               '%s')""" % receipt_after)
    rep("""REVISION = ('ebeefe97a230678b812b164096ec7fccf1c1f2516d8c96ef546c92bcd645acc1',
            '165a515105c3ba007f432c1746519b4032343e0e05897c7e2e1b38ae01143684')""",
        """REVISION = ('d6ca85cd96c7aab4ea0b6a7954d2d74e5e6bb211cde0bb820f3b6f815023bd88',
            '%s')""" % revision_after)
    rep("""INPUT = (SUPPORT/'receipt.input.draft.json', HERE/'receipt-candidate-r1/receipt.input.json')
INPUT_SHA = ('7dd1e9eaa22c0158f1172da647b207e2bb966eea799bc3d3e67301c2225c15e7',""",
        """INPUT = (Path('/var/tmp/gct-m1wh-p6-input-20260923-r2/receipt.input.draft.json'), PREP/'receipt.input.json')
INPUT_SHA = ('24c1ca751303d5cab12a1605599d13cb5e5a152c977088fbb6869c7a052095ec',""")
    rep("ACCEPTED = Path('/var/tmp/ga-ecwh-receipt-adoption-20260920-r1/after.json')",
        "ACCEPTED = Path('/var/tmp/gct-m1wh-p6-adoption-20260923-r2/after.json')")
    rep("ACCEPTED_SHA = '151192ffa44b71e3e80977107327a4957e937f4dc065b3b6eb6d6ecb91db408b'",
        "ACCEPTED_SHA = '%s'" % sha(Path('/var/tmp/gct-m1wh-p6-adoption-20260923-r2/after.json').read_bytes()))
    rep("PROVIDER_SHA = '1d731ccd1c3b283f30f6092954037cc4187be605289f06b6c5f5674f27427f2d'",
        "PROVIDER_SHA = '%s'" % sha(Path('/var/tmp/gct-m1wh-p6-adoption-20260923-r2/after.json.provider-pins').read_bytes()))
    rep("    b = module(SUPPORT/'observe-compose.py', 'be8461f48192ccadcafebb26619650fc9378a46e425026fc9aa6357c0a276c01')",
        "    b = module(SUPPORT/'p6-observe-compose.py', '43b94ce6%s')" % '__OBSERVE_TAIL__')
    rep("""    for relative,sha in [
        ('second-refusal-diagnosis.json','0d5460a3b76ff0c7f4cc81da15952976524afc96887ee41706e1c2b7cd67b291'),
        ('window-r2/before-refused-observation.json','65da5cbfc03acb0ceff29149034e076372a5c1f9b98de13825390098d63b4494'),
        ('baseline-difference-r1/differences.json','4850a505905414548b3510ea9afb971476dd8de190161d35c794243877668237'),
        ('baseline-difference-r1/observed.json','72614c36e772460783149c422a6df868eccc9c1e918900cdd1b218a105476aad'),
        ('baseline-difference-r1/command-history.json','afc618e721901ebf9d471d69124dfbc0df6f3ace7c9fe947b702c6b1ecb332f2'),
        ('git-read-metadata-fixture-r2/result.json','e0e8f05c5124c069dccce65a5152e89b8b2680e9d19d8cb086ed9ffdcc31c87f'),
        ('cache-directory-diagnosis.md','0b4bac0938900c511a54ecbea9d740541b9d9320bfc62ab0ef387322689a697e'),
    ]:
        read(HERE/relative,sha)
""", "    # The R9-era diagnostic pins are not evidence for this window; its evidence is the prep root.\n"
       "    read(PREP/'result.json', '%s')\n" % sha(Path(prep, 'result.json').read_bytes()))
    rep("    read(HERE/'isolation-candidate-r2/city.baseline.toml', CITY_SHA[0])",
        "    read(PREP/'city.baseline.toml', CITY_SHA[0])")
    rep("    read(HERE/'isolation-candidate-r2/city.isolated.toml', CITY_SHA[1])",
        "    read(PREP/'city.isolated.toml', CITY_SHA[1])")
    rep("    read(HERE/'receipt-candidate-r1/receipt.final.json', RECEIPT_SHA[1])",
        "    read(PREP/'receipt.final.json', RECEIPT_SHA[1])")
    rep("argv[argv.index('--model')+1] == 'claude-opus-5', 'Opus-only selection')",
        "argv[argv.index('--model')+1] == 'claude-opus-5-5', 'Opus-only selection')")
    rep("    sha = '6ac87f25ab5aeea1811404a53b58aae4069743a0cead3eafacee644d2ebd34da'\n    r = module(SUPPORT/'run-readiness.py', sha)",
        "    sha = '7b28b3e5%s'\n    r = module(SUPPORT/'p6-readiness.py', sha)" % '__READINESS_TAIL__')
    rep("""def approved_historical_image(prior):
    # Independent Astra DISPOSITION_PASS binds only the incidental Git lock
    # directory times from the recorded 16:04:43–16:04:58 read command.
    # Never write these values to disk or reuse this exception for fresh drift.
    value=json.loads(json.dumps(prior))
    entry=value['cache']['inventory'][CACHE_DIRECTORY]
    for key in ('mtime_ns','ctime_ns'):
        require(entry[key] == 1789908652707220822, 'historical exception preimage')
        entry[key] = 1789920290808834863
        # Second independently reviewed logging-command disposition. The
        # coordinator now also supplies GIT_OPTIONAL_LOCKS=0 to workflow calls.
        require(entry[key] == 1789920290808834863, 'second historical preimage')
        entry[key] = 1789923360712391421
    return value""", """def approved_historical_image(prior):
    # ga-4z38 disposition, for independent review: between the P6 accepted snapshot (12:36Z) and
    # this window, coordinator `gc bd` calls made WITHOUT GIT_OPTIONAL_LOCKS=0 advanced only the pack
    # cache repo's .git directory times. The last such call was the 15:51:43Z read test that proved
    # the cause; every coordinator gc call since carries GIT_OPTIONAL_LOCKS=0. A read-only lstat
    # forecast found no other cache, pin or protected-tree change. Never write these values to disk
    # or reuse this exception for fresh drift.
    value=json.loads(json.dumps(prior))
    entry=value['cache']['inventory'][CACHE_DIRECTORY]
    for key in ('mtime_ns','ctime_ns'):
        require(entry[key] == 1790165454882697018, 'historical exception preimage')
        entry[key] = 1790178703592685769
    return value""")
    rep("    temp = path.parent/('.ga-y49e-'+suffix+'.tmp')", "    temp = path.parent/('.ga-4z38-'+suffix+'.tmp')")
    rep("        source = HERE/'isolation-candidate-r2'/('city.isolated.toml' if i else 'city.baseline.toml')",
        "        source = PREP/('city.isolated.toml' if i else 'city.baseline.toml')")
    # Full digests of the two P6 modules, filled from the files themselves.
    observe = sha(Path(P6, 'p6-observe-compose.py').read_bytes())
    readiness = sha(Path(P6, 'p6-readiness.py').read_bytes())
    assert observe.startswith('43b94ce6') and readiness.startswith('7b28b3e5')
    rep("'43b94ce6__OBSERVE_TAIL__'", "'%s'" % observe)
    rep("'7b28b3e5__READINESS_TAIL__'", "'%s'" % readiness)
    assert 'ga-y49e' not in s.replace('ga-y49e base', '').replace('reviewed ga-y49e', ''), 'leftover ga-y49e reference'
    assert '/tmp/ga-y49e-launch-20260920' not in s
    out = Path(os.environ.get('GA4Z38_OUT', package), 'window-base-r11.py')
    out.write_text(s)
    print('window-base-r11.py', sha(out.read_bytes()))


if __name__ == '__main__':
    main(sys.argv[1], sys.argv[2])
