"""One supported ga-4z38 contract/enrollment patch; never route or resume.

ga-4z38 r11: a rebind of the reviewed ga-y49e bind-task-r2.py. It runs as its own job BEFORE the
window, so no window root may exist yet; route-task-r5.py binds these outputs by provenance.
Generated by make_round2b.py.
"""
import hashlib
import json
import os
from pathlib import Path
import sys
import types

HERE=Path('/home/loucmane/gas-city-ops-worktrees/ga-e0t1-orchestrator-bootstrap/docs/ai/work-tracking/active/20260903-ga-e0t1-orchestrator-bootstrap-ACTIVE/designs/ga-4z38-window')
ROOT=Path('/var/tmp/ga-4z38-bind-20260923-r1')
HELPER=HERE/'window-base-r11.py'
HELPER_SHA='cad1d660b872a352bce7e8c3c5bffda5ca7ac663a732575f48a3b7a9847926cd'
BRIEF_SHA='7bfe154a8d321c9f051509e824a79aa40c7ecab7e20b179bbe5d374d24e457f3'
BEAD='ga-4z38'
TARGET='gascity/gc.implementation-worker'
WORK='/home/loucmane/gascity-core-worktrees/ga-4z38-typed-route-cycles'
BRANCH='codex/ga-4z38-typed-route-cycles'
CHECK='/home/loucmane/gascity/home/cache/repos/954ed14987da288bfb98feee4cdab5043a44de1a8a9cf47afaaa0ce6e438fd5f/gascity/assets/scripts/checks/build-artifact-valid.sh'

def main():
    assert os.getuid()==os.geteuid()==1000 and globals().get('_SOURCE_SHA')
    assert hashlib.sha256(Path(__file__).read_bytes()).hexdigest()==_SOURCE_SHA
    raw=HELPER.read_bytes();assert hashlib.sha256(raw).hexdigest()==HELPER_SHA
    w=types.ModuleType('binding_window');w.__file__=str(HELPER)
    exec(compile(raw,str(HELPER),'exec',dont_inherit=True),w.__dict__)
    w._SOURCE_SHA=HELPER_SHA
    b,o,owned=w.load_support();w.pins()
    brief=w.read(HERE/'worker-brief.md',BRIEF_SHA).decode()
    # Binding precedes the window: the base ROOT is the window root, which must not exist yet.
    assert not os.path.lexists(w.ROOT), 'binding must precede the window'
    w.read(w.CITY/'city.toml',w.CITY_SHA[0]);w.read(w.RECEIPT,w.RECEIPT_SHA[0])
    ROOT.mkdir(mode=0o700);w.ROOT=ROOT
    def run(name,args):return w.phase(name,args,b,owned)
    def bead(name):
        rows=json.loads(run(name,w.GC+['--rig','gascity','bd','show',BEAD,'--json'])['stdout'])
        assert isinstance(rows,list) and len(rows)==1 and rows[0]['id']==BEAD
        return rows[0]
    def pristine(prefix):
        assert run(prefix+'-head',['/usr/bin/git','-C',WORK,'rev-parse','HEAD'])['stdout'].strip()==w.BASE
        assert run(prefix+'-branch',['/usr/bin/git','-C',WORK,'branch','--show-current'])['stdout'].strip()==BRANCH
        assert run(prefix+'-status',['/usr/bin/git','-C',WORK,'status','--porcelain=v1','--untracked-files=all'])['stdout']==''
    before_host=w.host(o);pristine('before')
    before=bead('task-before-read');w.save('task-before.json',before)
    assert before['status']=='open' and not before.get('assignee')
    assert not before.get('metadata') and not before.get('dependencies')
    request=json.dumps(dict(schema='gc.native-task-attempt.v1',store_ref='rig:gascity',
        bead_id=BEAD,template=TARGET,limit=1,state='requested'),separators=(',',':'))
    assert request=='{"schema":"gc.native-task-attempt.v1","store_ref":"rig:gascity","bead_id":"ga-4z38","template":"gascity/gc.implementation-worker","limit":1,"state":"requested"}'
    metadata={'gc.work_dir':WORK,'gc.work_branch':BRANCH,'gc.check_path':CHECK,
        'gc.build.artifact_schema':'gc.build.implementation-summary.v1',
        'gc.build.artifact_path_keys':'gc.implementation.summary_path',
        'gc.implementation.summary_path':'.gc/worker-evidence/ga-4z38/implementation-summary.md',
        'gc.native_task_attempt':request}
    argv=w.GC+['--rig','gascity','bd','update',BEAD,'--append-notes',brief]
    for key,value in metadata.items():argv+=['--set-metadata',key+'='+value]
    w.save('binding-intent.json',dict(before=before,metadata=metadata,brief_sha256=BRIEF_SHA,
        executor_sha256=_SOURCE_SHA,worker_launched=False))
    run('task-bind',argv)
    after=bead('task-after-read');w.save('task-after.json',after)
    assert after['metadata']==metadata
    old_notes=before.get('notes') or '';new_notes=after.get('notes') or ''
    assert new_notes.startswith(old_notes) and new_notes.endswith(brief)
    assert new_notes[len(old_notes):len(new_notes)-len(brief)].strip()==''
    for key in set(before)|set(after):
        if key not in ('metadata','notes','updated_at'):
            assert before.get(key)==after.get(key),key
    assert w.host(o)==before_host
    pristine('after')
    w.save('result.json',dict(ok=True,bead=BEAD,contract_bound=True,attempt_state='requested',
        routed=False,assigned=False,worker_launched=False,live_configuration_changed=False))
    print(json.dumps(w.record('result.json')))

if __name__=='__main__':main()
