"""Full native integrity read inside read-only mounts, paired with host proof.

ga-4z38 r11: a rebind of the reviewed ga-y49e observe-platform-integrity-r2.py for a FRESH window on the
M5 baseline. It admits the live state against the P6 accepted snapshot plus the reviewed disposition,
through the base `before.json` snapshot check. No prior window lifecycle or restoration observation
exists, so those two historical comparisons are removed. Generated by make_round2a.py.
"""
import json
import os
from pathlib import Path
import sys
import types

HERE=Path('/home/loucmane/gas-city-ops-worktrees/ga-e0t1-orchestrator-bootstrap/docs/ai/work-tracking/active/20260903-ga-e0t1-orchestrator-bootstrap-ACTIVE/designs/ga-4z38-window')
ROOT=Path('/var/tmp/ga-4z38-integrity-20260923-r1')
BUILD=Path('/var/tmp/ga-y49e-platform-inspector-20260920-r1')
W_SHA='85dfb406daada228b7b5f46c27ad6ca027d66c1510466f1cbb79b9754551c358'
BINARY_SHA='77685c663383d7b61e61e41f5e833a90be19bbfecfd8d95dcabe868d30a06237'
MANIFEST=Path('/home/loucmane/gascity/city/.gc/platform/install-manifest.json')
MANIFEST_SHA='2d7eadce62c4e567697813cc9122414f1e94c3bd9d389aef92015adef7f36319'

def load_window():
    import hashlib
    path=HERE/'window-obs-r11.py';raw=path.read_bytes()
    if hashlib.sha256(raw).hexdigest()!=W_SHA:raise RuntimeError('observer source drift')
    w=types.ModuleType('frozen_window');w.__file__=str(path)
    exec(compile(raw,str(path),'exec'),w.__dict__)
    return w

def verify_preservation(r,before,after):
    w=r.w
    r.preservation(before,after,w.CITY_SHA[0],w.RECEIPT_SHA[0])
    accounting=r.p.compare(before['cache'],after['cache'],
        before['cache_access_clock'],after['cache_access_clock'])
    w.require(not accounting['deltas'],'read-only integrity changed cache atime')

def provider_pins(w,o):
    m=json.loads(w.read(MANIFEST,MANIFEST_SHA))
    providers=m['integrity']['providers']
    w.require([p['name'] for p in providers]==['claude-native','codex','claude'],'provider inventory')
    for p in providers:
        w.require(p['version_args']==['--version'],'only version probes')
        w.require(str(Path(p['path']).resolve(strict=True))==p['resolved_path'],'provider resolution')
        pin,_=o.read_file(p['resolved_path'])
        w.require(pin['sha256']==p['sha256'],'provider bytes drift before invocation')
        w.require(pin['metadata']['uid']==1000 and pin['metadata']['gid']==1000
            and pin['metadata']['mode']==0o755,'provider authority')

def main():
    r=load_window();w=r.w;w.require(globals().get('_SOURCE_SHA'),'bound entry')
    w.read(Path(__file__),_SOURCE_SHA)
    b,o,owned=w.load_support();w.pins()
    w.read(BUILD/'platform-inspect',BINARY_SHA)
    result=json.loads(w.read(BUILD/'build-result.json','c79a3165ccfb3c35fd50a5a781f91b46755d67c27f94efb6c62cf230c946676a'))
    w.require(result['binary_sha256']==BINARY_SHA and result['core_commit']=='796d9a7a67c42294fdc467c107bb59b76e482301'
        and result['core_tree']=='f2c120a5ac9ea25ebc395c1b3cfa4eb30dcafd13'
        and result['entrypoint_sha256']=='e9f1fa42cdd5120c97c21ba37b7ca20f5fd14d94282575e4a08b3e17c80fec35',
        'build binding')
    provider_pins(w,o)
    if sys.argv[1:]==['inner']:
        w.mount_proof(None)
        os.execve(BUILD/'platform-inspect',[str(BUILD/'platform-inspect')],dict(b.ENV,BD_DISABLE_METRICS='1'))
    w.require(sys.argv[1:]==[],'unknown action')
    w.host(o);w.read(w.CITY/'city.toml',w.CITY_SHA[0]);w.read(w.RECEIPT,w.RECEIPT_SHA[0])
    # Fresh window: no prior lifecycle chain exists to verify. The suspension state is pinned in the
    # snapshot below and admitted against the P6 accepted state.
    ROOT.mkdir(mode=0o700);w.ROOT=ROOT
    w.save('intent.json',dict(executor_sha256=_SOURCE_SHA,binary_sha256=BINARY_SHA,
        version_probes_only=True,worker_launch=False))
    # The base snapshot named before.json admits the live state against the P6 accepted snapshot
    # with the reviewed disposition (approved_historical_image) and the accepted provider pins.
    w.snapshot('before.json',b,o)
    before=w.record('before.json')
    argv=['/usr/bin/bwrap','--ro-bind','/','/','--unshare-net','--unshare-pid',
        '--new-session','--die-with-parent','--proc','/proc','--dev','/dev','--',
        '/usr/bin/python3','-I','-S','-B',str(w.LAUNCH),__file__,_SOURCE_SHA,'inner']
    try:
        phase=w.phase('integrity',argv,b,owned,timeout=90)
        report=json.loads(phase['stdout'])
        w.require(report['schema']=='ga.platform-inspect-observation.v1' and report['ok'] is True
            and report['report']['Drifts'] in (None,[]),'integrity drift')
    except BaseException as exc:
        w.save('primary-failure.json',dict(error=str(exc),preservation_proven=False))
        raise
    finally:
        # Preserve the first failure above. Missing/uncertain terminal containment
        # stops here without treating a snapshot as successful containment.
        w.complete_containment()
        w.snapshot('observed-after.json',b,o)
        after=w.record('observed-after.json')
        verify_preservation(r,before,after)
        w.save('preservation.json',dict(window_preservation=True,cache_atime_deltas=0,
            runtime_child_metadata_policy='unchanged pinned R6',timestamp_writes=False))
    w.save('result.json',dict(ok=True,report=report,actual_host_verified=True,
        root_cache_protected_read_only=True,window_preservation=True,worker_launched=False,
        admitted_against_p6_with_disposition=True))
    print(json.dumps(dict(ok=True,worker_launched=False,full_native_integrity=True)))

if __name__=='__main__':main()
