"""Fresh integrity-bound window with strict reads and observed route regeneration.

ga-4z38 r11: a rebind of the reviewed ga-y49e window-state-r10.py over window-base-r11.py. The fresh
integrity observation runs as the job immediately before preflight, so it is bound by provenance
(executor digest, exact content, digests recorded once at before.json) instead of reviewed output
digests. Generated by make_round2b.py.
"""
from datetime import datetime, timezone
import hashlib
import json
import os
from pathlib import Path
import stat
import sys
import time
import types

HERE=Path('/home/loucmane/gas-city-ops-worktrees/ga-e0t1-orchestrator-bootstrap/docs/ai/work-tracking/active/20260903-ga-e0t1-orchestrator-bootstrap-ACTIVE/designs/ga-4z38-window')
BASE_SHA='e573b5618367281a28932b8fe03fe30f3c5ba4397e08158f86d6b669bc0fce2c'
POLICY_SHA='61c3e38e4475061c658a853036922742ab2ce69d44a4577e3f91490674047783'

def load(path,expected,name):
    assert path.resolve(strict=True)==path
    fd=os.open(path,os.O_RDONLY|os.O_NOFOLLOW|os.O_NOATIME|os.O_CLOEXEC)
    try:
        s=os.fstat(fd)
        assert stat.S_ISREG(s.st_mode) and s.st_uid==1000 and s.st_nlink==1 and s.st_size<=1024*1024
        raw=b''
        while chunk:=os.read(fd,65536):raw+=chunk
        assert os.fstat(fd)==s and len(raw)==s.st_size and hashlib.sha256(raw).hexdigest()==expected
    finally:os.close(fd)
    m=types.ModuleType(name);m.__file__=str(path);sys.modules[name]=m
    exec(compile(raw,str(path),'exec',dont_inherit=True),m.__dict__)
    return m

w=load(HERE/'window-base-r11.py',BASE_SHA,'window_r7_base')
p=load(HERE/'cache-atime-policy-r1.py',POLICY_SHA,'window_r7_atime')
w.ROOT=Path('/var/tmp/ga-4z38-window-20260923-r1')
original_save=w.save
original_snapshot=w.snapshot
original_preservation=w.preservation
active_snapshot=None

CACHE=Path('/home/loucmane/gascity/home/cache/repos')

def cache_mounts(text=None):
    rows=[]
    for line in (Path('/proc/self/mountinfo').read_text() if text is None else text).splitlines():
        fields=line.split()
        w.require(len(fields)>=10 and '-' in fields,'mountinfo shape')
        path=w.re.sub(r'\\([0-7]{3})',lambda m:chr(int(m[1],8)),fields[4])
        w.require('\\' not in path,'mount path escape')
        options=set(fields[5].split(','))
        rows.append(dict(id=fields[0],parent=fields[1],device=fields[2],root=fields[3],
            path=path,options=sorted(options),tail=fields[fields.index('-')+1:]))
    covering=[x for x in rows if x['path']=='/' or str(CACHE)==x['path'] or str(CACHE).startswith(x['path']+'/')]
    w.require(bool(covering),'cache covering mount absent')
    longest=max(len(x['path']) for x in covering)
    top=[x for x in covering if len(x['path'])==longest]
    w.require(len(top)==1,'ambiguous cache covering mount')
    selected=top+[x for x in rows if x['path'].startswith(str(CACHE)+'/')]
    w.require(len({x['path'] for x in selected})==len(selected),'ambiguous nested cache mounts')
    for row in selected:
        opts=set(row['options'])
        w.require(len(opts & {'noatime','relatime'})==1 and not (opts & {'strictatime','nodiratime'}),
            'unsupported cache access-time mount policy')
    return sorted(selected,key=lambda x:x['path'])

def clock_sample():
    boot=Path('/proc/sys/kernel/random/boot_id').read_text().strip()
    first=time.clock_gettime_ns(time.CLOCK_BOOTTIME)
    real=time.time_ns()
    last=time.clock_gettime_ns(time.CLOCK_BOOTTIME)
    return dict(boot=boot,real_ns=real,boot_before_ns=first,boot_after_ns=last)

def save(name,value):
    if active_snapshot is not None and name==active_snapshot['name']:
        w.require('cache_access_clock' not in value,'unexpected observation clock')
        mounts=cache_mounts()
        w.require(mounts==active_snapshot['mounts'],'cache mount changed during observation')
        value=dict(value,cache_access_clock=dict(start=active_snapshot['start'],end=clock_sample()),
            cache_access_mounts=mounts)
    original_save(name,value)

def snapshot(name,b,o):
    global active_snapshot
    w.require(active_snapshot is None,'nested snapshot')
    active_snapshot=dict(name=name,start=clock_sample(),mounts=cache_mounts())
    try:original_snapshot(name,b,o)
    finally:active_snapshot=None

def cache_preservation(before,after,city_pin,receipt_pin):
    a=json.loads(json.dumps(before));z=json.loads(json.dumps(after))
    w.require('cache_access_clock' in a and 'cache_access_clock' in z,'missing prospective clock envelope')
    ac=a.pop('cache_access_clock');zc=z.pop('cache_access_clock')
    w.require('cache_access_mounts' in a and 'cache_access_mounts' in z,'missing cache mount proof')
    mounts=a.pop('cache_access_mounts')
    w.require(mounts==z.pop('cache_access_mounts') and mounts==cache_mounts(),'cache mount policy drift')
    accounting=p.compare(a['cache'],z['cache'],ac,zc)
    for delta in accounting['deltas']:
        path=str(CACHE) if delta['path']=='.' else str(CACHE/delta['path'])
        covering=[x for x in mounts if x['path']=='/' or path==x['path'] or path.startswith(x['path']+'/')]
        row=max(covering,key=lambda x:len(x['path']))
        w.require(not (set(row['options']) & {'noatime','ro'}),'atime changed on read-only/noatime cache mount')
    accounting['mounts']=mounts
    # Only the comparison copies are aligned, after exhaustive cache validation.
    # Original observations and every timestamp remain preserved, never rewritten.
    z['cache']=a['cache']
    original_preservation(a,z,city_pin,receipt_pin)
    before_sha=w.digest(json.dumps(before,sort_keys=True,separators=(',',':')).encode())
    after_sha=w.digest(json.dumps(after,sort_keys=True,separators=(',',':')).encode())
    result=dict(accounting,before_observation_sha256=before_sha,after_observation_sha256=after_sha,
        base_source_sha256=BASE_SHA,policy_sha256=POLICY_SHA)
    name='cache-atime-'+before_sha+'-'+after_sha+'.json'
    if os.path.lexists(w.ROOT/name):
        w.require(w.record(name)==result,'access accounting collision')
    else:original_save(name,result)


routes=load(HERE/'restore-r9-routes-r3.py',
    '8d041af74297b44c0bedecdbcaa776ac92f433eba801afa0ee0a89a71eecc7c2','window_routes')
routes_policy=load(HERE/'route-chain-r1.py',
    '55fd9fefb9c512a486084e3c1e0900b3ad63a315f919b3c4213701e51b0a2144','window_route_chain')
INTEGRITY=Path('/var/tmp/ga-4z38-integrity-20260923-r1')
OBSERVER_SHA='d700295d6a20270fb388b9f11e8d42dbfaa331698999c4fea8b1cb0ce6433b7a'
INSPECTOR_SHA='77685c663383d7b61e61e41f5e833a90be19bbfecfd8d95dcabe868d30a06237'

def integrity_baseline(first):
    # The reviewed observer creates INTEGRITY exclusively (0700) and records its executor digest
    # before observing. Its outputs are bound by exact content here; their digests are recorded once,
    # at before.json, and every later snapshot requires the same bytes.
    s=INTEGRITY.lstat()
    w.require(stat.S_ISDIR(s.st_mode) and s.st_uid==1000 and stat.S_IMODE(s.st_mode)==0o700,
        'integrity root authority')
    w.require(json.loads(w.read(INTEGRITY/'intent.json'))==dict(executor_sha256=OBSERVER_SHA,
        binary_sha256=INSPECTOR_SHA,version_probes_only=True,worker_launch=False),'integrity executor')
    w.require(not os.path.lexists(INTEGRITY/'primary-failure.json'),'integrity primary failure')
    raw=w.read(INTEGRITY/'result.json')
    w.require(json.loads(raw)==dict(ok=True,actual_host_verified=True,
        admitted_against_p6_with_disposition=True,
        report=dict(ok=True,report={'Drifts':None},schema='ga.platform-inspect-observation.v1'),
        root_cache_protected_read_only=True,window_preservation=True,worker_launched=False),
        'fresh native integrity result')
    w.require(json.loads(w.read(INTEGRITY/'preservation.json'))==dict(window_preservation=True,
        cache_atime_deltas=0,runtime_child_metadata_policy='unchanged pinned R6',timestamp_writes=False),
        'integrity preservation')
    after=w.read(INTEGRITY/'observed-after.json')
    binding=dict(root=str(INTEGRITY),observer_sha256=OBSERVER_SHA,result_sha256=w.digest(raw),
        observed_after_sha256=w.digest(after))
    if first:
        w.require(not os.path.lexists(w.ROOT/'integrity-binding.json'),'integrity binding already recorded')
        original_save('integrity-binding.json',binding)
    else:
        w.require(w.record('integrity-binding.json')==binding,'integrity baseline changed after admission')
    return json.loads(after)

def reload_events():
    names=sorted(path.name for path in w.ROOT.glob('*-generated-routes.json'))
    chain=[name for name in routes_policy.ORDER if name+'-generated-routes.json' in names]
    w.require(len(names)==len(chain),'unexpected route-event file')
    routes_policy.valid_chain(chain)
    events={}
    for name in chain:
        event=w.record(name+'-generated-routes.json')
        w.require(event['phase']==w.record(name+'-phase.json')
            and event['accepted']==w.record(name+'-accepted.json'),'route-event phase binding')
        phase=event['phase']
        w.require(w.record(name+'-started.json')==dict(phase=phase['phase'],
            argv=phase['argv'],cwd=phase['cwd']) and phase['cwd']==str(w.ROOT),'reload intent binding')
        trace=event['trace'];trace_name=trace['phase']
        w.require(trace==w.record(trace_name+'-phase.json') and
            w.record(trace_name+'-started.json')==dict(phase=trace_name,
                argv=trace['argv'],cwd=trace['cwd']),'trace phase/intent binding')
        routes_policy.validate_event(event,name,routes,p,w.REVISION,w.GC+['reload','--json'])
        events[name]=event
    return chain,events

def collect_snapshot(name,b,o):
    prior=integrity_baseline(name=='before.json')
    first_routes=routes.capture_routes(w,o)
    chain,_=reload_events()
    h=w.host(o)
    value=dict(host=h,pins={path:o.read_file(path)[0] for path in prior['pins']},
        cache=o.tree_snapshot(b.CACHE,cache=True),
        protected={str(path):o.tree_snapshot(path,protected=True) for path in b.PROTECTED},
        providers=w.provider_pins(b,o),directories=w.directories(o),
        generated_routes=routes.capture_routes(w,o),generated_route_chain=chain)
    w.require(first_routes==value['generated_routes'],'routes changed during snapshot')
    w.require(chain==reload_events()[0] and h==w.host(o),'snapshot epoch/event drift')
    w.require(w.dependency_image(value['providers'])==w.dependency_image(prior['providers']),
        'native-integrity provider drift')
    w.save(name,value)
    if name=='before.json':
        w.require(not chain,'fresh window unexpectedly has reload history')
        # Bind the fresh observer postimage. Every timestamp remains untouched.
        admission=dict(prior,generated_routes=value['generated_routes'],generated_route_chain=[])
        preservation(admission,w.record(name),w.CITY_SHA[0],w.RECEIPT_SHA[0])

def preservation(before,after,city_pin,receipt_pin):
    chain,events=reload_events()
    w.require(after['generated_route_chain']==chain,'observation route-chain is stale')
    a,z,proof=routes_policy.project(before,after,events,routes,p,w.REVISION,w.GC+['reload','--json'])
    cache_preservation(a,z,city_pin,receipt_pin)
    first=w.digest(json.dumps(before,sort_keys=True,separators=(',',':')).encode())
    last=w.digest(json.dumps(after,sort_keys=True,separators=(',',':')).encode())
    result=dict(proof,before_sha256=first,after_sha256=last,
        baseline_integrity_sha256=w.record('integrity-binding.json')['observed_after_sha256'],
        timestamp_writes=False)
    name='route-accounting-'+first+'-'+last+'.json'
    if os.path.lexists(w.ROOT/name):w.require(w.record(name)==result,'route accounting collision')
    else:original_save(name,result)

def precheck_reload(name,i):
    w.require(i in (0,1) and name==routes_policy.ORDER[0 if i==1 else 1],'reload direction/name')
    w.require(not list(w.ROOT.glob(name+'-*')),'reload output namespace already consumed')
    chain,_=reload_events()
    w.require(chain==([] if i==1 else ['stage-reload']),'reload chain precondition')

def reload(name,i,b,owned):
    precheck_reload(name,i)
    before=routes.capture_routes(w,w.load_support()[1])
    start=dict(start=clock_sample(),end=clock_sample())
    p.bounds(w.record('before.json')['cache_access_clock'],start)
    w.save(name+'-intent.json',dict(revision=w.REVISION[i]))
    phase=w.phase(name,w.GC+['reload','--json'],b,owned)
    ack=json.loads(phase['stdout'])
    w.require(ack['ok'] is True and ack['async'] is False and ack['soft'] is False
        and ack['outcome']=='applied' and ack['revision']==w.REVISION[i],'reload acknowledgement')
    # A timed-out observation never repeats reload. The 15s observation in the
    # preserved R3 restore was contained but too short; the successful read-only
    # successor established this bounded 90s per-read/120s total observation.
    deadline=time.monotonic()+120;index=0
    while True:
        remaining=deadline-time.monotonic()
        w.require(remaining>0,'revision observation timeout; no mutation replay')
        result=w.phase(name+'-trace-'+str(index),w.GC+[
            'trace','show','--type','cycle_result','--since','2m','--json'],
            b,owned,timeout=min(90,remaining))
        rows=json.loads(result['stdout'])['records']
        newest=max(rows,key=lambda row:row['seq']) if rows else None
        if newest:
            observed=time.time_ns()
            age=observed/10**9-datetime.fromisoformat(newest['ts'].replace('Z','+00:00')).timestamp()
            w.require(newest['controller_pid']==2331 and 0<=age<=120
                and newest['fields']['active_template_count']==0,'stale/active controller revision')
            if newest['config_revision']==w.REVISION[i] and newest['completion_status']=='completed':break
        index+=1
        time.sleep(min(1,max(0,deadline-time.monotonic())))
    accepted=dict(ack=ack,cycle=newest)
    w.save(name+'-accepted.json',accepted)
    after=routes.capture_routes(w,w.load_support()[1])
    finish=dict(start=clock_sample(),end=clock_sample())
    event=dict(name=name,before=before,after=after,before_clock=start,after_clock=finish,
        phase=phase,accepted=accepted,trace=result,observed_at_ns=observed)
    routes_policy.validate_event(event,name,routes,p,w.REVISION,w.GC+['reload','--json'])
    p.bounds(w.record('before.json')['cache_access_clock'],finish)
    w.save(name+'-generated-routes.json',event)

original_snapshot=collect_snapshot
w.reload=reload
original_transition=w.transition

def transition(i,b,o,owned,prefix):
    # Check orphan outputs before city replacement as well as before reload.
    precheck_reload(prefix+'-reload',i)
    return original_transition(i,b,o,owned,prefix)

w.transition=transition

w.save=save
w.snapshot=snapshot
w.preservation=preservation

if __name__=='__main__':
    w.require(globals().get('_SOURCE_SHA'),'bound source launcher required')
    # Inner confined invocations must re-enter this exact wrapper, not bare R6.
    w.__file__=__file__
    w._SOURCE_SHA=_SOURCE_SHA
    w.main()
